### ISSUE TITLE
function : enable / disable mainbody component

### ISSUE THREAD

**Issue by ghost** [GavickPro/Music-Free-Responsive-Joomla-Template#1]
is missing !

**Comment by dziudek** [comment]
This function was removed in Gavern for Joomla! 1.6+, because disabling mainbody component on the subpages caused a lot of problems with 3rd party components. Currently user can remove the mainbody component only from the frontpage and only if he enabled the module on the mainbody module position.

**Comment by ghost** [comment]
thanks, that solves the problem.
