### ISSUE TITLE
template styling : complete support for K2Store / J2Store shopping cart module

### ISSUE THREAD

**Issue by ghost** [GavickPro/Music-Free-Responsive-Joomla-Template#10]
complete styling for K2Store / J2Store shopping cart module ... and so on ... 

check out attached url, you will find really nice interface :) : http://www.graphicsfuel.com/2011/11/shopping-cart-popup-interface-psd/

**Comment by dziudek** [comment]
It is not a shopping template and we have no plans to implement support for the shopping extensions in this template on the nearest future.

**Comment by ghost** [comment]
okay, let the people talk ;)
