### ISSUE TITLE
prefix " double" does not work in tablet.css

### ISSUE THREAD

**Issue by responsive-cms** [GavickPro/Music-Free-Responsive-Joomla-Template#100]
i have 2 modules with the " double" prefix, in desktop + mobile view they work as they should, but in tablet view the are displayed as "one" not "double". I updated the template with all newer files posted here, espcial the "Final fix for the media queries and the retina displays", but the problem still exists. What can i do?

**Comment by bkrztuk** [comment]
Could you provide me URL to site where the problem exist?

**Comment by responsive-cms** [comment]
i send you an email at 17th February, did you see it?

**Comment by bkrztuk** [comment]
No surely not if you don't get respond since 17th Feb I don't get it. Please write a message as soon as you re-send me details.

**Comment by responsive-cms** [comment]
Hi. I just send the email again to your gavick.com emailadress.
Thank you.

**Comment by bkrztuk** [comment]
Ok I got it. Please update template firstly to 3.8 version which I've uploaded today >> https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/commit/1a70413ffcac60830cd3a6a106d8d92a980ee795

**Comment by responsive-cms** [comment]
Thank you. Just updated all files.
Problem still exists.
I will temporarily post the link to the site, so you can check if u need to:
http://goo.gl/mTS6S

The modules on the right side "... music video clips" & "Facebook".
(see my 1st posting for the problem description).
see this screenshot: http://goo.gl/8r216

template settings/Layout:
Grid base width: 252
Tablet min. width: 800px
Grid spaces: 6px
Mainbody width: 3
Maximal number of columns: 5
Maximal scale: 1

Thx a lot!

**Comment by bkrztuk** [comment]
The double prefix is designed in tablet view to have always 50% width but you can try add this code to override.css file. 

.box.double {width: 100% !important} to css/tablet.css file.

**Comment by responsive-cms** [comment]
I add:
.box.double {
    width: 100%!important;
    }
to
tablet.css = no effect.
And in the template settings/advanced settings/Custom CSS code (+ directly in override.css) = no effect ?

**Comment by bkrztuk** [comment]
I don't see this code, probably because of compression of cache systems.

**Comment by responsive-cms** [comment]
Joomla cache was and is not activated.
I now deactivated in the template: Advanced settings/CSS compression
the code is in tablet.css from line 188...

**Comment by responsive-cms** [comment]
Do you see the code now?

**Comment by bkrztuk** [comment]
No there is still only 50% value, please look >> http://d.pr/i/kX1I

**Comment by responsive-cms** [comment]
Hmm. I just downloaded my tablet.css, and from line 192 to 194:
.box.double {
    width: 100%!important;
    }

here´s the direct link to te css file:
http://goo.gl/DwgsZ

**Comment by bkrztuk** [comment]
Please try with this :  
#gkPage .box.double {width: 100% !important}

**Comment by responsive-cms** [comment]
now they are displayed in 100%, but not arranged among each other, but about each other.
Screenshot: http://goo.gl/FNVtj

**Comment by bkrztuk** [comment]
So probably this solution is to make it like on mobile view so set all to 100% or change tablet width in template settings to show default desktop view.

**Comment by responsive-cms** [comment]
"so set all to 100%"
What do you mean by "all" ? And how to do this?
So i can delete the css changings in tablet.css (#gkPage .box.double {width: 100% !important})?
Thank you for your help.

**Comment by bkrztuk** [comment]
Could you provide temp link again ? the old one is not working please check >> http://wp1137341.wp236.webpack.hosteurope.de/www.synapsenkitzler.de_2012/

**Comment by responsive-cms** [comment]
My Hoster has problems since this morning. I will post a message here if it runs. thx.

**Comment by responsive-cms** [comment]
Hi.
The new URL is: http://goo.gl/MQgez
Please delete the text of the old URL in your posting from yesterday. Thank you.

**Comment by bkrztuk** [comment]
Please add to tablet.css 

<code>#gkTop .box.half, #gkBottom .box.half, #gkPage .box.half, #gkTop .box.one, #gkBottom .box.one, #gkPage .box.one, #gkTop > .box, #gkBottom > .box, #gkPage > .box, #gkTop .box.double, #gkBottom .box.double, #gkPage .box.double, #gkTop .box.triple, #gkBottom .box.triple, #gkPage .box.triple, #gkTop .box.fourfold, #gkBottom .box.fourfold, #gkPage .box.fourfold, #gkTop .box.full, #gkBottom .box.full, #gkPage .box.full { width: 100%!important; max-width: 100%}</code>

**Comment by responsive-cms** [comment]
Thx, but doesn´t work.

**Comment by bkrztuk** [comment]
After this code will surely have the same view like on mobile view because this is just copy/paste form mobile.css file.

**Comment by responsive-cms** [comment]
well, check the link.

**Comment by bkrztuk** [comment]
could you unpublish the fb module for tests ? to get the same structure like on mobile ?

**Comment by responsive-cms** [comment]
done

**Comment by responsive-cms** [comment]
and please check it now in IE, cause by resizing the window-widt, now i get a scrollbar at the bottom.

**Comment by bkrztuk** [comment]
so with masonry srcipt you can achieve this effect, you need to restore original CSS, sorry but I want to help you but this is impossible in this configuraiton.

**Comment by responsive-cms** [comment]
belonging to the tablet.css ?

**Comment by bkrztuk** [comment]
yes, exactly

**Comment by responsive-cms** [comment]
I thought, actually, it should be possible just to copy all the code of the mobile.css to the tablet.css, cause in mobile.css all modules are shown in full width, but it doesn´t work.

Then I thought, maybe it is possible to override / ignore tablet.css, and set mobile.css to the width, from where the tablet.css at the moment will take affect. But that would be a lot of manual coding.

BUT:
Now i have a workaround/solution :-) :
I make a new module for mediaplayer and facebook for desktop and tablet, 
desktop:suffix: double onlydesktop; position: sidebar
tablet: suffix: onlytablet; position: mainboy_bottom

Wow, that was a lot of trying. thx for your help.
