### ISSUE TITLE
please help me to find how to edit this module or delete?

### ISSUE THREAD

**Issue by gunzy** [GavickPro/Music-Free-Responsive-Joomla-Template#101]
![untitled](https://f.cloud.github.com/assets/3619237/165232/bd5b8caa-792a-11e2-9f6d-46ad6d205a76.jpg)
I can't find to edit and delete this module
please help me for this image 1 and image 2
I was used free template is ' music free - responsive template '
where I can find it? how?

**Comment by bkrztuk** [comment]
This are custom HTML modules and you will find them in modules list via module manager, if you still have problem please show me your site URL

**Comment by gunzy** [comment]
This template, virtuemart can support it or not on homepage the template?all plugin and module or not?like make catalog on template homepage?
Live from BlackBerry® on esia max-d, Internet Max, Biaya Mini.

-----Original Message-----

**Comment by bkrztuk** [comment]
Supported 3rd party extensions you can find in template download page (only K2), but of course you can use any Joomla! extension with our product.

**Comment by MsShona** [comment]
Did you install the quickstart? If so, then I believe these modules are called "bubble" and "quote"; both are located in the sidebar position.
