### ISSUE TITLE
Images Issue

### ISSUE THREAD

**Issue by footibet** [GavickPro/Music-Free-Responsive-Joomla-Template#104]
First, many thanks for this excellent template. Really enjoying it. I do have an issue with images and how they are sized in articles when a user selects an article to read. I would like to know either how to resize the image or article to ensure the image looks right.

Please have a look at www.footibet.com - I will happily give you back end access.

regards

Andrew

**Comment by bkrztuk** [comment]
First of all - your site extremaly slow, probably it is time to change hosting :)

The images issue depends of your K2 settings, in category or global K2 settings you set to display large images so when the original image is smaller it is scaled-up to the desired site. Please change the width for the image in k2 settings because now the template shows the images scaled as you can see here is original image http://www.footibet.com/media/k2/items/cache/f7a0a54c92471ac4480e727e4ccf93df_L.jpg

**Comment by footibet** [comment]
Many thanks for taking time to have a look.

The image you examined should only have a natural width of 180 pixels.

I have ensured the settings in K2 global are correct. The small setting has a width of 200 - which is about right. I have then tried to alter the K2 category and item settings - but no change. Would you be willing to go in the back end and show me what to do? I can email you a password etc.

Many thanks again. Your time is appreciated.

regards

Andrew

**Comment by bkrztuk** [comment]
What size you set for images inside articles ? Please switch to Beez template and see what happend.

**Comment by footibet** [comment]
I have created an account Admin2 with password music. 

When I switched to beez no articles appear. 

Happy for you to have a quick look in the back end. Will identify the problem much quicker. 

Again many thanks for your help.

**Comment by footibet** [comment]
Hi, I have given you admin access through the user name Admin2 and password
music. Grateful if you could go in the back end and see what the issue is.
You can change anything as the site is brand new and hardly has any traffic at
the moment. Otherwise we will be talking for the next year!

cheers

Andrew

**Comment by bkrztuk** [comment]
I've tried to login and this is what I see >> http://d.pr/i/T3AI

**Comment by footibet** [comment]
bkrztuk, sorry if I have screwed up on the user name and password. I think I have found a solution though. I read that if you don't upload the image correctly the first time in K2 then you have to delete it and start again. I have done that and it works. However, I have used your advice to ensure it is configured correctly. Many thanks and good luck for the future - andrew
