### ISSUE TITLE
embedded Youtube-Video overlays/hides menu-items. (Internet Explorer)

### ISSUE THREAD

**Issue by responsive-cms** [GavickPro/Music-Free-Responsive-Joomla-Template#105]
tested with IE8 (latest available version for Windows XP).
Youtube-Video (embedded by youtube iframe-code) overlays/hides menu-items.
F.e. menu-items of the menu-entry "music" at http://goo.gl/wyDLX

**Comment by bkrztuk** [comment]
Could you look at this screenshot and mark me where is the problem ? >> http://d.pr/i/Er6U

**Comment by responsive-cms** [comment]
Hi. Do you use Internet Explorer 8?
Check my screenshot, where you can see the problem.
http://goo.gl/TyV6Q

**Comment by bkrztuk** [comment]
Here you can see screenshot from IE8 http://d.pr/i/nFUN

**Comment by responsive-cms** [comment]
mine is from IE8 too.? 
btw. on your screenshot you can see another IE (8?)problem at the right side:
The small modules are not displayed, only the facebook thumb.

**Comment by responsive-cms** [comment]
is there a way to fix this?
I tried it with giving the menu a higher z-index than the video container, but does´t have any effect.
http://goo.gl/5DAUn

**Comment by bkrztuk** [comment]
Here are solutions >> http://maxmorgandesign.com/fix_youtube_iframe_overlay_and_z_index_issues/

This problem is related with IE8 and iframe video.

**Comment by responsive-cms** [comment]
Oh, I didn´t know that it is not caused by the template/.... Thanks a lot for your answer.
Shame on Internet Explorer. ,-o ,-)
