### ISSUE TITLE
modules overlay other modules (IE8 + FF)

### ISSUE THREAD

**Issue by responsive-cms** [GavickPro/Music-Free-Responsive-Joomla-Template#106]
in desktop view the small modules on the right "Free MP3" & "social bookmarks" lay over the "Facebook" module:
Always in Internet Explorer 8 at the first time the site is loaded, after reloading = ok.
Often in Firefox.
Any idea to that?
screenshot: http://goo.gl/fVYfA
website: http://goo.gl/2EqRL

**Comment by responsive-cms** [comment]
is there a way to fix this? i updated the screenshot + url. The problem appears often. Maybe the problem is caused by the loading time of the content of the facebook and youtube component ?

**Comment by bkrztuk** [comment]
If it is working fine with any other module content like (clean HTML) it is not template issue, probably the script can't compute the size of the box. Please make test with some example 'Lorem ipsum ...' module to detect where is the problem.

**Comment by responsive-cms** [comment]
Thx for the input.
I put the div with the facebook code inside another div and give this one a fixed height. Now it seems to work / not to overlay 2 modules anymore.
