### ISSUE TITLE
Register link in module not available

### ISSUE THREAD

**Issue by ExtKerwejugend** [GavickPro/Music-Free-Responsive-Joomla-Template#107]
Hello together!

I have a problem I absolutely not understand:
If I use a login module there is not link for registering.
If I use a menu entry with a login form (so it's a seperate site like any other site, too), the register link appear. Why doesn't it in module?! How to fix?

Many thanks in advance,
Stefan

**Comment by bkrztuk** [comment]
Login module and default Joomla! login page are different things, if you want to modify login pop-up you need to modify code in template/html/mod_login directory.

**Comment by ExtKerwejugend** [comment]
But this module works fine in other templates. And the details of this module say that if user registration is enabled, a register link will be shown?!

**Comment by bkrztuk** [comment]
Yes, because template override module view - when you change name or delete template/html/mod_login directory you will ge the same view like in other templates.

**Comment by ExtKerwejugend** [comment]
Great, thanks!

**Comment by ExtKerwejugend** [comment]
One last question: This template supports the masonry (moomasonry.js?) effect. It uses this effect with a special duration and "ways", modules move. So you can see how and where them move. Is it possible to use this special effect on other templates? Other templates use the masonry effect as well but without duration and "ways". Can you help me here, too?

**Comment by bkrztuk** [comment]
Sorry but I don't understand what you mean by other templates ? Only music_free and fashion from our templates use masonry script.

**Comment by ExtKerwejugend** [comment]
May be I'm wrong, but I thought masonry effect is when different blocks order themself regarding to the size of the screen?!

**Comment by bkrztuk** [comment]
Please look here for Masonry layout description >> http://www.gavick.com/documentation/joomla-templates/templates-for-joomla-1-6/gavern-3-0/responsive-layout/

"In general, MooMasonry fixes the block positions to avoid problems due to blank spaces resulting from floating elements."

Other templates use media queries to achieve 'responsive' design.

**Comment by ExtKerwejugend** [comment]
Alright, thank you for this information!
