### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by footibet** [GavickPro/Music-Free-Responsive-Joomla-Template#108]
Hi. I have placed the google analytics code in the box but google says the code cannot be tracked. According to Google the code must appear before the </head> tag. 

When I look at my source code it appears after the </head> tag. How can I change this?

Cheers

Andrew

**Comment by bkrztuk** [comment]
Usually it takes some time until google track results. Please only make sure that you've inserted clean tracking number like UA-XXXXXX not full code.
