### ISSUE TITLE
framework / core enhancement : google+ content share button 

### ISSUE THREAD

**Issue by ghost** [GavickPro/Music-Free-Responsive-Joomla-Template#11]
this one is free and better than +1

url : https://developers.google.com/+/plugins/share/

suggestion  : g+ share button instead +1 button

@dziudek  what do you think ?
## 

i've added this suggestion because i'm not sure how you'll add the [custom field to paste their code ] for SN , which you called "dziwne" ;), but it seems that the major social networking buttons you'll leave as they are.

**Comment by dziudek** [comment]
@bkrztuk - do you have it on your updates list for Gavern 2.11/3.4? Because as I remember we have a similar feature to add. If not - please add it as option like FB "Send" button.

**Comment by dziudek** [comment]
BTW @partizanpl - what are you doing with your messages? I'm getting always 7-10 notifications about your one post.

**Comment by ghost** [comment]
@dziudek, nie mam pojęcia, zwykle - jeśli edytuję to raz, ale Twoje powiadomienia też mam 3x dla tematu. dosłownie każde.

**Comment by dziudek** [comment]
@partizanpl - strasznie dziwne, to chyba jakiś bug githuba w takim razie, ale np. teraz dostałem jedno powiadomienie.

**Comment by bkrztuk** [comment]
Strasznie dziwna ta sprawa z powiadomieniami, @dziudek  Twoje dostaje tylko raz, te od @partizanpl  kilkanaście razy i wygląda to tak jakby za każdym razem cytował sam siebie :) może po prostu przy każdej edycji wysyłane jest info ? 

This is one of the item in my to-do list, I'll make standard issue.

**Comment by ghost** [comment]
no tak @bkrztuk tylko, że ja edytuję raz, od ciebie nie miałem żadnego powiadomienia, a od @dziudek 3 x po raz kolejny.

**Comment by ghost** [comment]
dokładnie teraz dostałem twoje powiadomienie @bkrztuk x 2 ... :/

**Comment by bkrztuk** [comment]
Faktycznie wygląda na jakiegoś bug'a, najdziwniejszy w tym wszystkim jest ten interwał czasowy, ja dostaje to samo powiadomienie na przedziale 20 minut :)

**Comment by ghost** [comment]
popatrzcie też na to :

http://imageshack.us/photo/my-images/526/gitq.png/

komentarz wysłany wcześniej, ma znacznie niższy czas dodania, niż komentarz dodany później.

**Comment by bkrztuk** [comment]
Chyba nic z tym nie zrobimy :) przy tej ilości powiadomień na pewno nic nie pominiemy :) BTW u mnie czasy postów są ok.

**Comment by ghost** [comment]
dopóki mało tematów, łatwo można się odnaleźć @bkrztuk ;) twoje tylko duplikuje, te od @dziudek mam zawsze x3

**Comment by ghost** [comment]
panowie, jeśli plugin wprowadzony na listę - zamykam temat.
