### ISSUE TITLE
visible problem with the main menu (background) in Internet Explorer 8

### ISSUE THREAD

**Issue by responsive-cms** [GavickPro/Music-Free-Responsive-Joomla-Template#110]
visible problem with the main menu (background) in Internet Explorer 8, with resized browser-window-width.
see screenshot: http://goo.gl/BWUO2
(left side: Firefox, right side: IE8)
see livesite: http://goo.gl/xZvIj

**Comment by bkrztuk** [comment]
Please try to add this code to ie8.css  :  

<code>body #gkPageTop { overflow: hidden !important}</code>

**Comment by responsive-cms** [comment]
Perfect. Thank you a lot.

**Comment by responsive-cms** [comment]
But now. no submenu-item of the mainmenu is displayed in IE8.
compare FF & IE8:
http://wp1137341.server-he.de/www.synapsenkitzler.de_2012/music
/music has a lot os submenu-.items f.e.

**Comment by bkrztuk** [comment]
I really don't see problem on IE8, please look http://d.pr/i/Jlqi

**Comment by responsive-cms** [comment]
Yes, cause i deleted the code you posed 12 days ago.

(cite)
Please try to add this code to ie8.css :
body #gkPageTop { overflow: hidden !important}
(cite)

But, now, i have the same issue that causes you to post that.

**Comment by responsive-cms** [comment]
@bkrztuk 
I found the reason causes this problem:
If the searchbox is activated, and the browserwindow width is resized, the gkMainMenu break/wrap down. 
The problem now is, that the gkPageContent is not shifted by the now bigger gkPageTop.
But only in Internet Explorer, version 8 tested.

see screenshot: http://goo.gl/BWUO2 (left side: Firefox ok, right side: IE8 not ok)
see livesite: http://goo.gl/xZvIj

How to fix this?

Problem should be also appear in the original template. But the original demo has no activated search box http://demo.gavick.com/free/may2012/

**Comment by bkrztuk** [comment]
Maybe I don't uderstand your point but I have given you the code for fix problem with menu now I see it is removed. Then check this issue on IE don't have any problem. You attach a screenshot where previously prepared code is not added to the site. Please tell me what else I can do for you ? I really don't saw a device which use IE8 browser and have lower screen resolution that 800px wide (because this kind of screenshot you've attached)

**Comment by responsive-cms** [comment]
Your code which fixed the problem causes a new problem ( no submenu-items are displayed), i posted here 14 days ago, see https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/issues/110#issuecomment-15694958

But you are right. It will be very rare to have a device which will use IE8 with lower res. than 800px. But maybe the mobile Browser of Microsoft in their mobiles will have this problem. But i have no possibility to test this.

**Comment by bkrztuk** [comment]
Surely mobile devices with Microsoft OS use better render engine that IE8 browser.
