### ISSUE TITLE
uninstall k2 but still k2 tags in URL

### ISSUE THREAD

**Issue by responsive-cms** [GavickPro/Music-Free-Responsive-Joomla-Template#112]
I uninstall k2 (component + plugins) long time ago. If i create a new mainmenu-item (tested it with linking to an article/category-blog/main-articles), the url (+ related articles) always has a lot of k2 entrys:
http://wp1137341.server-he.de/www.synapsenkitzler.de_2012/k2-tags/k2-categories/k2-extra-field-groups/k2-extra-fields/test

and i have some older menu-items, which have less, but have k2 tags:
menu: http://wp1137341.server-he.de/www.synapsenkitzler.de_2012/k2-users/frazy-versions/
article: http://wp1137341.server-he.de/www.synapsenkitzler.de_2012/k2-users/frazy-versions/123-synapsenkitzler-28-tracks-mixed

and i have some older menu-items, which have no k2 tags at all:
menu: http://wp1137341.server-he.de/www.synapsenkitzler.de_2012/music
article: http://wp1137341.server-he.de/www.synapsenkitzler.de_2012/music/142-heiliger-stuhl

article URL has also k2 tags, when click on them at /home (/home = lists all main-articles).

I tested to create a new category, and a new article inside this category, and the url is fine:
http://wp1137341.server-he.de/www.synapsenkitzler.de_2012/109-testttt/146-testttt
After creating a main-menu-item to this article, now it is:
http://wp1137341.server-he.de/www.synapsenkitzler.de_2012/k2-tags/k2-categories/k2-extra-field-groups/k2-extra-fields/testttt

How to fix this?
I checked the .sql database in a texteditor, and there are still a lot of k2 entrys.

**Comment by bkrztuk** [comment]
When you're removing component in Joomla! the uninstaller don't clean all references to extensions just remove files and component/modules entry in database. It is really not related with template - you can always run clean Joomla! installation + clean template then you will surely not get any K2 references.

**Comment by responsive-cms** [comment]
Thx a lot for oyur help.
There were some k2 entrys ( k2-tags , k2-categories , k2-extra-field-groups , k2-extra-fields ) in database _menu in menutype: mainmenu + footmenu. After deleting the k2 entrys there are no more k2 tags in the URL, if u create a new menu item.
I found some problem reports in google, without any solution, so maybe those will find ths posting.
:-)

btw. @bkrztuk : 
at /administrator/index.php?option=com_menus&view=menus the alias/menutype/systemname of the usermenu is named "mainemu". Don´t know if this is joomla or gavick related. 
Can I change this to "usermenu", or will this cause maybe any problem? In the databse its a bit confusing if the usermenu is called mainemu.

**Comment by bkrztuk** [comment]
You can change menu name if you want to but then remeber to refresh template settings with the new name.
