### ISSUE TITLE
Picture motion in MusicFreeTemplate

### ISSUE THREAD

**Issue by Sokal** [GavickPro/Music-Free-Responsive-Joomla-Template#114]
Hi

I've just started new web site:

http://ubezpieczeniadlarolników.pl

I've decided to choose responsive template for the first time. The question is:

How to make a picture motion (zoom in) that are above an article. Demo looks great http://demo.gavick.com/free/may2012/!!

Are those pictures preview of the aricle?

Does K2 has anythitg to do with it?

Regards 

Michael

**Comment by bkrztuk** [comment]
This zoom efect works on News Show Pro module, when you publish NSP module and select data source with images you will see this exactly like on our demo site.

**Comment by Sokal** [comment]
Ok works fine. Great module type. THX
