### ISSUE TITLE
Mobile Version horizontal to vertical

### ISSUE THREAD

**Issue by ManfredHeindl** [GavickPro/Music-Free-Responsive-Joomla-Template#115]
hello,
here is my problem.

if i visit my site (tablet) in horizontal positions. the size of the modul "mainbody/component" is right.
so i turn my tablet to vertical Position and return to horizontal, the size of the "mainbody/component" is wrong.
the size of the mainbody is now 100percent of the tablet Screen

found this with google chrome mobile version.

**Comment by bkrztuk** [comment]
Could you show me your site URL ? It is always easier to check case on live site.

**Comment by ManfredHeindl** [comment]
i'm not online at the time. please wait a few days.
you can see it also on the live site by gavick demo.

http://demo.gavick.com/free/may2012/

klick on the link "Linking Park talks about the new Allbum". so if the site is loaded, switch from horizontal to vertical and return it. now you can see the effect.
