### ISSUE TITLE
Can not use preffix by music free template

### ISSUE THREAD

**Issue by laci0815** [GavickPro/Music-Free-Responsive-Joomla-Template#116]
Hi, i installed joomla 3.0.3 and the template music free v.3.8 (great template). Now i will create some custom modules with suffix "dark" ore "color2". I created a new module and opened "Options>Advanced Options". In the column "Module Class Suffix" i typed in "dark". In the Frontend i had no changes. What i did wrong? I don´t use K2. Is this the problem? I hope somebody can help me. Sorry for the bad english. URL: http://bachtalia.webseiten.cc/

**Comment by bkrztuk** [comment]
You've used wrong suffix name, you need to use ' dark' with the space before name not 'dark'

**Comment by laci0815** [comment]
Ok, but when i use this with space. I can´t see the module in the Frontend.

**Comment by ManfredHeindl** [comment]
you must set the suffix in the backend.
Module Custom HTML - Advanced Options - Module Class Suffix.  ' dark' with space before name without quote.
that's it

**Comment by laci0815** [comment]
I did it. But when i set this i can´t see the module in the Frontend.

**Comment by bkrztuk** [comment]
So you surely do something wrong because when I've added suffix via firebug yesterday it was working fine on your site, please look >> http://d.pr/i/CzR1

**Comment by laci0815** [comment]
Ok?! I will try it again today afternoon. Thanks!

**Comment by laci0815** [comment]
Here my options. See Attachment. And i cant`t see the modul...
![shortcut](https://f.cloud.github.com/assets/4083111/350431/d00b2522-a01c-11e2-8e1d-1abc2a124e05.jpg)

**Comment by laci0815** [comment]
Here the second screenshot?! The module is there but i can´t see it.
![shortcut2](https://f.cloud.github.com/assets/4083111/350460/217e0ffe-a01e-11e2-8adf-5c3f5986d803.jpg)

**Comment by bkrztuk** [comment]
The  script is not working properly, in console you can see several errors. Our template use jQuery library but in your installation it is not included so probably you made some custom changes or install some extension which remove jQuery.

**Comment by laci0815** [comment]
Ok, i put a clean installation on my server http://website.bachtalia.webseiten.cc/
at first i istalled the tamplate and created a new Modull. Suffix: " dark"! The same Problem! Now i enabled Error reporting: System default! I get this:

Strict Standards: Non-static method JSite::getMenu() should not be called statically, assuming $this from incompatible context in /xxxxxx/xxxxxxxx/xxxxxxxx/web/templates/gk_music_free/lib/framework/helper.layout.php on line 178

Strict Standards: Non-static method JApplication::getMenu() should not be called statically, assuming $this from incompatible context in /xxxxxx/xxxxxxxx/xxxxxxxx/web/includes/application.php on line 569

Is this a problem with the server? Sorry but i don´t take custom changes or installed extensions. I have no idee what happend....

**Comment by bkrztuk** [comment]
Please configure your server according to Joomla! requirements so disable display_errors option in PHP configuration.

**Comment by laci0815** [comment]
I did it, but still the same problem. I installed the quickstart version, it works fine.
