### ISSUE TITLE
different module positions dependent on suffix ?

### ISSUE THREAD

**Issue by responsive-cms** [GavickPro/Music-Free-Responsive-Joomla-Template#117]
Is it possible, to have one module, and it reacts like:
suffix onlydesktop = position sidebar
suffix onlytablet = position mainbody_bottom
?

Cause at the moment i have 2 modules (type= empty/custom content), which have the identic content.
1 has suffix onlydesktop and position sidebar.
1 has suffix onlytablet and position mainbody_bottom.

I do so, cause i want the modules displayed in full width in tablet-view (and not as half sized which is the standard behaviour from the tablet.css), as you can see here http://goo.gl/enUcJ
And i have 8 modules of this kind, so i need always to update the content 2times.
If e.g., i want the module in onlymobile at a diff. position, i would have 3 modules.

**Comment by bkrztuk** [comment]
No this is not possible to have one module on two different positions, but you can always duplicate module, publish on different positions and hide for desktop, tablet or mobile.
