### ISSUE TITLE
Zoom off

### ISSUE THREAD

**Issue by mgarda** [GavickPro/Music-Free-Responsive-Joomla-Template#118]
Hi!
Hi! I not like the picture zoom effect.
How do i switch off this function?

BR, Milan

**Comment by bkrztuk** [comment]
Please open file gk.stuff.css from template/css directory and find this part of code 

<pre><code>.nspArt .nspImageWrapper:hover img {
    -webkit-transform: scale(1.2) rotate(-7deg);
    -moz-transform: scale(1.2) rotate(-7deg);
    -ms-transform: scale(1.2) rotate(-7deg);
    -o-transform: scale(1.2) rotate(-7deg);
    transform: scale(1.2) rotate(-7deg);
}</code></pre>

then just remove it.
