### ISSUE TITLE
Admin Error and Modules failing to appear - advice please

### ISSUE THREAD

**Issue by footibet** [GavickPro/Music-Free-Responsive-Joomla-Template#119]
Dear all, I am really enjoying the Music Free Template - I get good feedback from users too.

However, I have started having a couple of issues.

Admin Error: When I log in to the Admin area via www.footibet.com/administrator/ I get an internal server error and the page fails to load. When I go in via my host's site (footibetcom.ipage.com/administrator/) I have no problems. 

Modules not loading: On the front page the modules sometimes fail to load until I clear the cache. This appears to occur after I have optimized my mysql tables. But it has also happened when I have added a new module.

What are the best options for fixing these two issues? Would it be best to install a new copy of the template and reinstall the content? - If so how would I do that best.

Many thanks for your help as always.

Andrew

**Comment by bkrztuk** [comment]
Hi,

First issue is not related with template but with your hosting/domain settings. The cache problem may be related with wrong cache configruation, did you use cache configured like here >> http://www.gavick.com/documentation/joomla-extensions/extensions-for-joomla-1-6/gk-cahce-plugin/

**Comment by footibet** [comment]
Hi, the GKExt cache was not enabled but I have only just started experiencing problems. I'll let it run for a while and see what the effect is. Additionally do you advise enabling CSS Cache, Css Compression and javascript compression?

Many thanks for your excellent help.

Andrew

**Comment by bkrztuk** [comment]
This are advanced options and remember that enabling compression and cache may cause that you will not see CSS changes immediately.

**Comment by footibet** [comment]
Ok, I enabled GKExt cache and it completely killed the menu. I have disabled it again to ensure the site continues to work.

I don't make any changes to the CSS - does that mean that enabling the CSS Cache and Compression is a safe option?

Happy to DM you an admin user name and password if you have time to pop in the back end and have a play.

Once again, many thanks

Andrew

**Comment by bkrztuk** [comment]
Yes it is safe. Did you configure cache like it is described at wiki or just enabled gk extended cache plugin ?

**Comment by footibet** [comment]
I have enabled GK cache in the plug in menu and the template advanced menu. When I enabled the GK extended cache plug in it killed the menu. I have disabled the GK Extended Cache plug in to ensure users can still visit the site.

**Comment by footibet** [comment]
Still having problems. Just created a new module and the sidebar loads the modules but doesn't show them. Optimized SQL files, cleared the cache and then refreshed the browser - all of the modules now show. 

Could the recent K2 update have something to do with it. Or could there be a SQL database error?

**Comment by bkrztuk** [comment]
It can be related with DB problem because, surely when you get problems from back-end. Did you try to restore site from some backup package ? Please also run global check-in process.
