### ISSUE TITLE
rss feed (Syndication) does not work

### ISSUE THREAD

**Issue by responsive-cms** [GavickPro/Music-Free-Responsive-Joomla-Template#120]
i am using the gk_music_free_quickstart_J!25.zip with up to date files from here/github.
But the rss feed does not work. How to fix this?

feedvalidator:
http://feedvalidator.org/check.cgi?url=http%3A%2F%2Fwp1137341.server-he.de%2Fwww.synapsenkitzler.de_2012%2Findex.php%3Fformat%3Dfeed%26type%3Drss 
result:
//
Sorry
This feed does not validate.
Server returned HTTP Error 500: Internal Server Error [help]
line 1, column 0: XML parsing error: <unknown>:1:0: no element found [help]
In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendation.
Feeds should not be served with the "text/html" media type [help]
//

i tried this too:
- tried with the preinstalled templates
- overwrite the server-joomla-installation with new from a clean 2.5.9 zipfile:
  /modules/mod_syndicate
  /modules/mod_feed
  components/com_newsfeeds 
- "The reason was that I turned on the "System - Cache" plug-in with "Enable browser cache". After disabling it, everything was back to normal. " http://forum.joomla.org/viewtopic.php?p=2665331 
- install extension Ninja RSS Syndicator:

**Comment by bkrztuk** [comment]
Could you just check this issue on default template like Beez ? You are talking about default Joomla! RSS ? We're not override this part so this code should be generate by core Joomla! code.

**Comment by responsive-cms** [comment]
"Could you just check this issue on default template like Beez ?"
I did. That what was i meant with "tried with the preinstalled templates".

"You are talking about default Joomla! RSS ?"
Yes, the default joomla RSS.

"We're not override this part so this code should be generate by core Joomla! code."
Maybe the gk_music_free_quickstart_J!25.zip has some broken/... files? Would be great if anybody else who installed this, can check if the rss works fine. I tried a new, blank joomla + gk_music_free_J!25.zip, and it woks fine, so its not my server/setting or so.

**Comment by responsive-cms** [comment]
I used the template in blank joomla install and now the rss works.
