### ISSUE TITLE
Joomla 3.03 sidebar modules no longer showing up

### ISSUE THREAD

**Issue by alkaline1** [GavickPro/Music-Free-Responsive-Joomla-Template#121]
This template is just awesome and is a pleasure to work with on Joomla 2.5.
On Joomla 3.0.3 I am unable to show any module on sidebar position whereas the modules are showing up on any other positions like toolbar or others.
Is it just me that has this problem?
Would be great if someone can decline this issue or can confirm the same
Thanks for your answer
Greetings
Marcus

**Comment by footibet** [comment]
Sounds similar to my issue a couple of tickets below. If you refresh the cache they should come back - but looks like there is a glitch. Just need a full time fix as this keeps happening to me. See footibet.com

**Comment by alkaline1** [comment]
All right I will check this out but since mine is a brand new installation with just a few test articles I believe this should be further investigated. Thanks for replying will inform you.by tomorrow about any update

**Comment by footibet** [comment]
Might be related to some code in the php files and/or the latest k2 of joomla updates. I don't think the number of articles matter. That's just data. The error appears to be in the server side code - should think it's easy to fix if you know where the code has fallen down.

**Comment by bkrztuk** [comment]
@alkaline1 could you provide me URL to page where some modules are published on this position ?

**Comment by alkaline1** [comment]
Hi bkrztuk, thank you for investigating. the site Name is called http://www.gfdev.de and there should be at least 4 modules appear on the sidebar. I will send you 8or I will try it) PM within admin Access Details so you can have a look into the backend yourself.
cheers
Marcus
Edit: I am unable to send you a pm, at least I found no way....

**Comment by footibet** [comment]
Hi, it is the same problem I have mentioned in the ticket below yours. If you clear the system cache and refresh the browser they should appear. Also I found the GK Extended cache was causing a problem for some reason.

**Comment by footibet** [comment]
Also, the modules are there you just can't see them. Try putting your mouse over where they should be - it reacts as if they were there.

**Comment by alkaline1** [comment]
Generel Caching / GK caching is not enabled here and it cannot be a K2 Problem since this is a plain Joomla Installation with just the template applied on it. K2 is not installed. I tried to delete Caches however the modules still disapear.
Marcus

**Comment by bkrztuk** [comment]
Did you disable jQuery library ? I'm asking because I see several console error and this is why the script can't work.

**Comment by alkaline1** [comment]
Not i am Aware of. I have had a look and found nothing that says it is switched of. I think by default something is excluded:
![2013-04-15_09-59-07](https://f.cloud.github.com/assets/4138586/379558/8091cd3a-a5a2-11e2-8308-361b4d20ebbc.png)

**Comment by alkaline1** [comment]
I am going to re-install the test environment. Let's see if this will help....

**Comment by bkrztuk** [comment]
Did you use global Joomla! cache ? If yes please disable it. As I can see all compression are disabled so it shouldn't be a problem. Please let me know after installation and if it is possible try to run quickstart package.

**Comment by alkaline1** [comment]
new db, brand new installation, template installed and...no sucess. everything is default now, caching is disabled. Believe me, on version 2.5.9 everything was running fine, no prob at all. quickstart has not been installed; I want the start as clean as possible

Edit: installed it again on 2.5.9 working well... see here http://template.gfdev.de/ ...must be a version 3 problem I guess

**Comment by bkrztuk** [comment]
Did you use quickstart package for J!3.0 ? I've tested package and here is result >> http://d.pr/i/Hl3A (all is working fine)

**Comment by alkaline1** [comment]
Quickstart is working well, alos here (I just re-installed it on J 3) but I wanted to have something clean not using K2. At least for me it seems to be very hard to just use the template and configure it as I have done it in J 2.5, but on J 3.
So feel free to close this issue as the quickstart is running well. Thanks again for your help and patience
