### ISSUE TITLE
hide k2 categories from under main menu

### ISSUE THREAD

**Issue by raquel85** [GavickPro/Music-Free-Responsive-Joomla-Template#123]
Hello, i have a lot of categories on k2,  and i don´t want to show them all under the main menu, they appear in a row by default on the white space under manin menu, i don´t know what is the position, toolbar maybe?  Is there a way to hide them? i´m sure is quite simple, but i just can´t find where is the parameter, some help me please!

**Comment by bkrztuk** [comment]
Could you give me URL to page where this categories are visible ?
