### ISSUE TITLE
Full screen width images

### ISSUE THREAD

**Issue by Rubiking** [GavickPro/Music-Free-Responsive-Joomla-Template#124]
Hi,

I'm trying to create a design that use a full screen width images, like this one: http://matthewdwilliams.com/   . As you can see there is an image that go from side to side, and the better approximation that I did, is to put an 1600px image into a custom html module with the margin and padding 0, but anyway, If I strech the module to 1600px (as my monitor) some horizontal scroll appears and you must go from left to right... It is possible to do this? any help will be greatly appreciated.

Thanks in advance

**Comment by bkrztuk** [comment]
Could you provide URL to site with the problem ?

**Comment by Rubiking** [comment]
Yes, is www.pixellink.cl 
But, there is a little problem that for the moment I can't solve, is that when I want to modify some items, I use Firebug for find where and in which file is the attribute, so in all .css files I dont have problems, but when Firebug says that is in file "pixellink.cl" I dont have a clue where is it... In this "file" there is an attribute called "#gkPage > #gkContent" and is related to the padding & width of the images, so if I put "padding:0px" and "width: 100%" the images are semifull width, but doesn't go from side to side, and, I doesn't know which file have this code line... 

Thank you for your time

**Comment by Rubiking** [comment]
Well, seems that I discover how to go from side to side changing some parameters and with the help of firebug, but, I still doesn't know where is the "#gkPage > #gkContent" (for the large image) and ".masonry > .box.one, .masonry > .box" (for the logo image), if I put width: 100% and padding: 0px, the problem is solve but I must find where are this code located, I will really aprettiate if you can help me to find it out.

Thanks

**Comment by bkrztuk** [comment]
Probably the only way is to remove padding from 

``` css
.masonry > .box { padding: 0 !important}
```

**Comment by Rubiking** [comment]
Seems that I did it, at least the images works fine now... but other problem appears (menu), I think that is better to open other issue for this.

Thank you for your help.

**Comment by bkrztuk** [comment]
Ok, this one will be closed.
