### ISSUE TITLE
Menu Problem

### ISSUE THREAD

**Issue by Rubiking** [GavickPro/Music-Free-Responsive-Joomla-Template#125]
Hi all, 

I'm looking to create a top menu with only 3 main items (maybe individual menus will do the trick), one in the left, one in the middle and the last in the right corner, but I doesn´t know how to do this, for example for the right item I have created a only 1 independent menu item in the "create account" section,  and for the left and I "delete" the logo element (in template manager) and this is in the left, but... how can I put the last menu item in the middle?? I have tried to put in other positions like lang, menu1,2,3..10, login etc. but at most, I will appear above of the right menu item... There is some way to add a position, or use the logo position as a valid position?

My page is www.pixellink.cl/respaldo

Thanks in advance

**Comment by bkrztuk** [comment]
Template support only one menu position 

[Module positions](http://demo.gavick.com/free/may2012/index.php/template/lorem-ipsum/template-articles/module-positions)

and all that you need is to select some menu name in template settings to show menu items in this area

**Comment by liviupr** [comment]
Hello,
The main menu does not show at all, even if it is selected in the template settings. What are the settings for the module position?

**Comment by liviupr** [comment]
I have solved the problem. If you already had a menu created, before you have changed the template, your menu items wont be recognized by the template. You have to open each menu item and save it once again, then it will appear on the top menu.

**Comment by bkrztuk** [comment]
Thanks for solution, yes probably the template still keep old settings and this is why important is to save again the configuration.
