### ISSUE TITLE
500 - An error has occurred.

### ISSUE THREAD

**Issue by tony73** [GavickPro/Music-Free-Responsive-Joomla-Template#126]
hi, I'm new :). 
I installed the gk music free quickstart J! 25 but when I go on Template Manager, and I click on gk_music_free - Default tells me "500 - An error has occurred. Error loading form file"

What does it depend this? 

I also enabled "System - GK Cache" and "System - GK Extended Cache" I do not know if it depends on this, however I can not get into the configuration template. How can I fix?

**Comment by tony73** [comment]
ok I solved it, for those who have this type of problem is an error closing "</ field" to "templateDetails.xml" in line 254. Practically should be closed in this way </ field> .

**Comment by bkrztuk** [comment]
Thanks for posting solution, I'll include fix in next template version. What J! version you use ?

**Comment by tony73** [comment]
now I'm using joomla 2.5

**Comment by bkrztuk** [comment]
Issue related with >> https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/issues/128#issuecomment-17476768
