### ISSUE TITLE
Tablet Smartphones menu mode

### ISSUE THREAD

**Issue by Rubiking** [GavickPro/Music-Free-Responsive-Joomla-Template#127]
Hi all,

It's possible to disable the "compact" menu feature in lower resolutions?, I mean, if the resolution is low enougth, all the menu transform into a "3 lines icon" that works like a one menu item... So, It's possible to disable this feature? or eneable at, lets say, 100px width (for making unavailable at standard resolutions)

Thanks in advance

**Comment by bkrztuk** [comment]
You need to open file css/menu/menu.css and remove media queries for menu, code like : 

``` css
@media screen and
```
