### ISSUE TITLE
Bug in templateDetails.xml

### ISSUE THREAD

**Issue by ManfredHeindl** [GavickPro/Music-Free-Responsive-Joomla-Template#128]
hello,
there is a bug in the templateDetails.xml

at the line 254: </fiel
change to: </field>

affected
gk_music_free_quickstart_J25 
gk_music_free_J!25

**Comment by bkrztuk** [comment]
I don't see problem at code in repository, please look >> https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/blob/master/gk_music_free/templateDetails.xml

**Comment by ManfredHeindl** [comment]
i've downloaded all files from gavick

**Comment by tony73** [comment]
ManfredHeindl - is an error closing "</ field" to "templateDetails.xml" in line 254. Practically should be closed in this way </ field> .

**Comment by ManfredHeindl** [comment]
thanks i've done

**Comment by bkrztuk** [comment]
Today I'll re-create packages to update this one at gavick.com, hope this resolve this issue.
