### ISSUE TITLE
Width of the module TOP?

### ISSUE THREAD

**Issue by tony73** [GavickPro/Music-Free-Responsive-Joomla-Template#129]
how can I increase the width of the module TOP? I always remains the usual size of the modules in the sidebar. I would like to insert a slideshow so it must be as wide as the whole page. 
Thanks in advance

PS: sorry but I do not speak English well

**Comment by bkrztuk** [comment]
You can't choose different width for blocks other than content area. With masonry layout you can choose only default width for block and change it for content on some ItemID's.
