### ISSUE TITLE
nomobile and onlymobile suffixes dont work

### ISSUE THREAD

**Issue by beresattila1** [GavickPro/Music-Free-Responsive-Joomla-Template#130]
Hi.
I'm  using music free responsive template in http://www.hdmobil.hu  
i dont know why but mobile suffixes dont work in my page.
nothing.
no onlymobile, no nomobile.
There is  the "space" before the suffix, so there is another problem.
I'm using slidebar module for menu.(there is a plus icon.Click on it and a menu will slide to left) i want to use 2 slidebar. one for the desktop, tablet view, and one for the mobile view.
but the suffixes dont work.

can you help me please?

sorry for my bad English.

**Comment by bkrztuk** [comment]
Please give me the name of the module where did you set suiffx and the URL to page where I can see it. On the homepage I don't see any module with this kind of suffix.

**Comment by beresattila1** [comment]
the module name is "Nagymenu" .  Its a Slidebar module.Found here : http://extensions.joomla.org/extensions/style-a-design/modules-panel/22903

My page is www.hdmobil.hu.

**Comment by beresattila1** [comment]
are you see what i mean ?

**Comment by beresattila1** [comment]
anybody can help?

**Comment by bkrztuk** [comment]
For me all is working fine, please look at destkop mode >> http://d.pr/i/I15n

and for the tablet/mobile one >> http://d.pr/i/iysv

**Comment by beresattila1** [comment]
Yes.
it's solved by     Mr. teitbite .
Thanks for everybody.
Im very happy now.

2013/5/9 Bart³omiej Krztuk notifications@github.com

**Comment by obedaviles** [comment]
How did you resolve the problem... I'm stock at this to... @Gavick_Rockwall_Template 

Thanks: Keep The Good Work.

**Comment by beresattila1** [comment]
I dont remember.
Sorry :-(
2014.02.21. 21:39 ezt írta ("obedaviles" notifications@github.com):

**Comment by bkrztuk** [comment]
Maybe you are using this suffix for some special positions where modules don't have 'box' class. Could you tell me which module have the suffix set and where it is visible? Did you add the space before suffix name?
