### ISSUE TITLE
Perhaps disable responsive?

### ISSUE THREAD

**Issue by saynez** [GavickPro/Music-Free-Responsive-Joomla-Template#131]
Hello
Perhaps disable the responsive layout of this template?
Not found in the Admin settings such.
I apologize for my English.

**Comment by bkrztuk** [comment]
Music Free template use masonry layout so there is no Responsive Layout ON/OFF swither, you can remove all styles from tablet.css and mobile.css files but then of course it will be not working well on smaller screens.
