### ISSUE TITLE
Resize or cut images and videos in the articles

### ISSUE THREAD

**Issue by LegionGeth** [GavickPro/Music-Free-Responsive-Joomla-Template#132]
Hi to everyone, sorry for my english.
I have a problem: every images, or videos that I insert in an article comes "out" of the "margins". So I have to resize every content for the preview in homepage, but when you open the specific articles you see the images very little. 
There is a way to automatically resize the images depending on the size of the articles, or at least cut the images, so it does not come out?
Ps: the problem exists also in the modules near the articles :(
Thanks for every answer! ;)

**Comment by bkrztuk** [comment]
Maybe your editor just add the dimensions to image ? Could you give me URL to some page where problem exists ?

**Comment by LegionGeth** [comment]
This is the homepage: http://www.punto3production.com/ Now is offline, use username demo password d3m0 to enter ;) As you can see, if you use two columns, everything comes out of the article, also the video. Please help me!! :)

**Comment by LegionGeth** [comment]
Sorry but I can't keep the website offline, this is a screenshot of the problem:
http://img404.imageshack.us/img404/491/problemtwb.jpg
And this is the second problem, as you can see the windows of the social networks are above (or some parts, below) the video
http://img855.imageshack.us/img855/7274/problem2v.jpg
Thanks ;)

**Comment by ivanwongtf** [comment]
Hello,
I also have a similar problem that the picture and words out of the frame
Here is the screenshot:
http://i.imgur.com/4pPIptk.png
If you could not see clearly from the screenshot, here is the link
http://www.justdoevil.info/admintest

Thanks and sorry for interrupting

**Comment by bkrztuk** [comment]
@LegionGeth Please unpublish facebook module for tests, probably masonry script can't compute the module dimensions properly. I see also some extension for images on your site (jcemediabox-zoom-image) could you check results without this plugin ? I see from code that images have 

``` css
max-width: 100%
```

rule so all should be fine.
