### ISSUE TITLE
error.php

### ISSUE THREAD

**Issue by ManfredHeindl** [GavickPro/Music-Free-Responsive-Joomla-Template#133]
the error page 404 shows correct
the error page dosnt work correct.

example 403 message:
TPL_GK_LANG_ERROR_INFO TPL_GK_LANG_ERROR_DESC
TPL_GK_LANG_CONTACT_WEBMASTER

**Comment by bkrztuk** [comment]
What J! version you use ? I've checked and the messages are included in language file >> https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/blob/master/gk_music_free/language/en-GB.tpl_gk_music_free.ini

Please try to update template lang file in root/languages/en-GB directory.

**Comment by ManfredHeindl** [comment]
i use the newest Version of the template. i also found the tags in the language.ini and the tags in the error.php. 

![403](https://f.cloud.github.com/assets/2233128/495429/375d2cc6-bbc4-11e2-927c-6c5912b5a580.png)

**Comment by bkrztuk** [comment]
Could you show me your site URL ? The regular one and for the error page ?

**Comment by ManfredHeindl** [comment]
my site is not online at the moment. i will upload it in the next week

**Comment by bkrztuk** [comment]
Ok so please publish site online because in 99.9% we can't help without seeing _live_ site
