### ISSUE TITLE
Images resize problems in IE8

### ISSUE THREAD

**Issue by ivanwongtf** [GavickPro/Music-Free-Responsive-Joomla-Template#134]
Hello,
When i am using IE8 to browse my website, images can't resize to a suitable size and they break out from the frame.

Here is the screenshot when using IE8:
http://i.imgur.com/zJUmOxk.png

Here is the normal screenshot when using chrome:
http://i.imgur.com/46sD8rT.jpg

Link: http://www.justdoevil.info/admintest

I hope you can help me to solve the problem, sorry for my poor English, Thank you!

**Comment by bkrztuk** [comment]
Please try to use this fix https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/commit/037d19884929cbf475f1e012c62a7f709e001102

**Comment by ivanwongtf** [comment]
Thanks, the problem of NSP has fixed,
but there is another problem still exist,the image and the word in mainbody has break out

Here is the screenshot:
http://i.imgur.com/lyacXOA.png

PS:This problem also exist in other browser.

**Comment by bkrztuk** [comment]
What you mean by other browsers ? I've checked your site on Chrome and can't see a problem  >> http://d.pr/i/Umn6

**Comment by ivanwongtf** [comment]
Yes, the problem not exist on Chrome, but it also exist on Firefox and Opera
Screenshot:
http://i.imgur.com/e0QAoyC.png

PS:This problem will not exist when the width of the image of article not larger than frame

**Comment by ivanwongtf** [comment]
The problem still exist, can anyone help me please?

**Comment by bkrztuk** [comment]
The problem is not related with images but with parent container, please try this code

``` css
.itemContainer {max-width: 100%}
```

**Comment by ivanwongtf** [comment]
The problem of photo break out has solved, thank you.
But i encounter that there is other problem in IE8...
http://i.imgur.com/DPXLGOr.png
The photo of nsp do not appear and there is a dislocation error(i showed them in the photo)
I don't think that i had changed any code of the page...so i don't understand why these problem will appear...
Sorry to disturb you again...

**Comment by bkrztuk** [comment]
I've checked clean demo version on IE8 and I don't see this kind of problems.

**Comment by ivanwongtf** [comment]
Sorry for late, i fixed the problem which is the photo of nsp do not appear.
However, i got other problem because i used gk4 news pro to replace the original one(k2container) on Homepage, the white background got dislocation error while watching in IE8
Here is the screenshot:
http://i.imgur.com/FZmh58u.png
Website:
http://www.justdoevil.info

**Comment by bkrztuk** [comment]
Sorry but I've visited your home page and don't see this module.

**Comment by ivanwongtf** [comment]
Because the module will show articles randomly... so that made you thought those are two different module

Here is the full screenshot while watching in Chrome:
http://i.imgur.com/GjtIzEF.jpg

Here is the IE8 one:
http://i.imgur.com/5jOUjD4.png

PS:The modules which encase by a red frame in the pictures are the same module, hope you can understand! Sorry for my poor English

**Comment by bkrztuk** [comment]
Please try with this code in ie8.css file

``` css
#gkContent .box {overflow: visible!important}
```

**Comment by ivanwongtf** [comment]
Sorry, i tested it, but this code doesn't work.

**Comment by bkrztuk** [comment]
Please use this one : 

``` css
#gkContent > div { overflow: hidden !important}
```

this works for sure, result you can see here >> http://d.pr/i/YXJG

**Comment by ivanwongtf** [comment]
Thanks, the problem was solved.
But i am sorry to say that i got other problem in IE8,

Here is the screenshot: http://i.imgur.com/tVSXGUl.png
Some of thumbnail images of this module do not  narrow to a regular size
Blue frame is the regular size and Yellow frame is the wrong size
Again, this module will randomly show articles.

Sorry to bother you, i think this should be the last problem.

**Comment by bkrztuk** [comment]
Direct URL to page with problem is much more useful that screenshot, please provide me URL to page from attached file.

**Comment by ivanwongtf** [comment]
Sorry, forgot to give you the link

Link:http://www.justdoevil.info/article/relax/youtubeshare/item/283-diffraction-of-water-wave.html

**Comment by bkrztuk** [comment]
The problem is related with IE render mode, you can try to add 

``` css
.nspArt img.nspImage {
 min-width: 100%!important;
width: 100%!important;
}
```

for IE8 css file only.

**Comment by ivanwongtf** [comment]
I am sorry but the problem still exists after adding this code.

**Comment by bkrztuk** [comment]
That's all that we can do for IE8

**Comment by ivanwongtf** [comment]
ok, i understand and thank for your help.
