### ISSUE TITLE
Hover help

### ISSUE THREAD

**Issue by mangawill** [GavickPro/Music-Free-Responsive-Joomla-Template#135]
Hi there,
I need help applying hover functions to my joomla 
![bwm hover help](https://f.cloud.github.com/assets/3379990/547868/060ba092-c2d3-11e2-9165-2c1914171a51.jpg)
site. I want to add these kind of hovers from: http://designshack.net/articles/css/5-cool-css-hover-effects-you-can-copy-and-paste/

to the images on the attached

**Comment by bkrztuk** [comment]
You just need to create own CSS rules for this elements, additional code you can in override.css file. Of course this demands base knowledge of CSS.
