### ISSUE TITLE
problem changing copyright text

### ISSUE THREAD

**Issue by beginner12** [GavickPro/Music-Free-Responsive-Joomla-Template#138]
Hi Dziudek,

you wrote…
The layouts/blocks/footer.php is a path to file in the template directory on your server.

Just that my layout folder of your template does not have any footer.php file?

What am I doing wrong?
(Joomla 3.x)

Thank you fpr your help.

**Comment by bkrztuk** [comment]
J!3 version have the same file structure, footer.php is in layout/blocks directory, please look here >> https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/blob/J!3.0-compatible/gk_music_free/layouts/blocks/footer.php

**Comment by beginner12** [comment]
Dear Bartłomiej,

my problem is, that my layouts/blocks-folder of your template meet_gavern does not contain any footer file.

I downloaded it a second time and its still the same.

?
I work with Joomla 3.1

Blue skies
Helga

Am 26.05.2013 um 23:03 schrieb Bartłomiej Krztuk notifications@github.com:

> J!3 version have the same file structure, footer.php is in layout/blocks directory, please look here >> https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/blob/J!3.0-compatible/gk_music_free/layouts/blocks/footer.php
> 
> —
> Reply to this email directly or view it on GitHub.

Helga Kleisny
Roman kostenlos als E-Book veröffentlichen? http://www.kleisny.de/de/e-books-erstellen.html
Bartłomiej Krztuk notifications@github.com

**Comment by bkrztuk** [comment]
The problem is because you are writing in music free repository and don't mentione nowhere before that you are using meet gavern. Footer code you can find here >> https://github.com/GavickPro/Meet-Gavern/blob/master/meet_gavern/layouts/default.php

**Comment by beginner12** [comment]
Thank you Bartłomiej for your help, that works. And I am very sorry if I did something wrong. I am not a geek and mainly learning by doing. Which is hard but fun.

And I do love your template, sorry that I had never mentioned that, it is one of the few that can also work with different language (German and English) pages in J3. 
Defining the main menu position in favsomething only lets the user use one language for the menu and I need 2. Which your template does wonderfully.

Blue skies to you guys
Helga

Am 27.05.2013 um 09:40 schrieb Bartłomiej Krztuk notifications@github.com:

> The problem is because you are writing in music free repository and don't mentione nowhere before that you are using meet gavern. Footer code you can find here >> https://github.com/GavickPro/Meet-Gavern/blob/master/meet_gavern/layouts/default.php
> 
> —
> Reply to this email directly or view it on GitHub.

Helga Kleisny
Roman kostenlos als E-Book veröffentlichen? http://www.kleisny.de/de/e-books-erstellen.html
