### ISSUE TITLE
Need Help with GkToolBar on Gavick Music Free Joomla Template

### ISSUE THREAD

**Issue by EmanuelFromFlorence** [GavickPro/Music-Free-Responsive-Joomla-Template#139]
Hi i cannot find this section that Chrome inspector locates in my site at line 
/:44

on Gavick Music Free Template for Joomla 3.0

body #gkPageTop, body #gkToolbar, #gkFooter {
padding-left: 0px;
padding-right: 0px;
margin-left: 0px!important;

I need to input and modify 
padding-left to 32 px
and
margin left to -32

Is anyone here willing to help me?
Thanks i will really appreciate ^^

**Comment by EmanuelFromFlorence** [comment]
This happens only when i resize or load to the "tablet" dimension 
here is the link
www.cooperam.com/Rame
https://www.dropbox.com/s/th1k4j9v40uss1f/2013-05-31%2023.08.56.png

 ...as you can see the image on top doesn't end as on the desktop
you have a white space beside...
Can you help me?

I need to edit these lines
/:44

on Gavick Music Free Template for Joomla 3.0

body #gkPageTop, body #gkToolbar, #gkFooter {
padding-left: 0px;
padding-right: 0px;
margin-left: 0px!important;
where are them?

**Comment by EmanuelFromFlorence** [comment]
Basically i want this
https://www.dropbox.com/s/jv2lxxvqerx2yon/7.jpg

**Comment by EmanuelFromFlorence** [comment]
Is anybody here?^^

**Comment by bkrztuk** [comment]
This code from template code, please look at file `helper.layout.php` and this code : 

``` php
// CSS to add spaces for the page top
        $this->API->addCSSRule('body #gkPageTop, body #gkToolbar, #gkFooter { padding-left: '.$body_padding.'px; padding-right: '.$body_padding.'px; margin-left: '.(-1 * $body_padding).'px!important; }');
```

**Comment by EmanuelFromFlorence** [comment]
I think i did...modifying 3 css (menu,layout...)but i wanna try your method^^

let me understand..because i'm a new bie^^ i have to add that line to helper.layout.php?

but..first let me thank you ^^ for your great template and for being so kind to help me^^

**Comment by bkrztuk** [comment]
You just need to copy this line and set own padding value instead of `$body_padding` variable or just change in this line the body_padding value.

**Comment by EmanuelFromFlorence** [comment]
Ok..i did it but while it has worked on my Desktop (resizing ) it doesn't that much on Tablet (Ipad) and Smart phone (Iphone) so this is a Side by Side comparison to let you see better what i mean,
by the way i can live with it ^^ but your beautiful and INCREDIBLY free would be even better (its hard^^!) 
if adjusted ,in my opinion,to stick totally the top image from a side to another,but i understand it could be just
my personal need and not shared with others..so..here is the link
https://www.dropbox.com/s/me048j76tt0rugz/Side%20By%20Side%20MusicFree%20Devices%20Comparison.jpg

**Comment by EmanuelFromFlorence** [comment]
This is how i modified on line 115 (..) the helper.layout.php

```
    ............// CSS to add spaces between modules on the mainbody postion
    $this->API->addCSSRule('#gkContent .box { padding: '.(2* $grid_spaces).'px 0 0 0!important; }');


    // CSS to add spaces for the page top
    $this->API->addCSSRule('body #gkPageTop, body #gkToolbar, #gkFooter { padding-left: 28.7'.$body_padding.'px; padding-right: '.$body_padding.'px; margin-left: -28.7'.(-1 * $body_padding).'px!important; }');



    // CSS to avoid problems with the K2/com_content columns on the smaller screens
    $this->API->addCSSRule('@media screen and (max-width: '.floor(($grid_base * $content_width) * 0.8).'px) {
    #k2Container .itemsContainer { width: 100%!important; } 
    .cols-2 .column-1........
```

Did i make correctly?^^
Thanks (please don't be too cryptic 'cause i'm a new bie^^)

**Comment by bkrztuk** [comment]
No, if you want to modify this value please just use 

``` php
 $this->API->addCSSRule('body #gkPageTop, body #gkToolbar, #gkFooter { padding-left: 50px; padding-right: 50px; margin-left: 50px!important; }');
```

and just change the 50px example value to your own one.

**Comment by EmanuelFromFlorence** [comment]
ok...so basically helper works for desktop.tablet and mobile?

**Comment by EmanuelFromFlorence** [comment]
PS.( i know its off topic ..sorry)
Why on Ios Chrome Music says it doesn't recognize the browsere?
How to remove the message to appear again?

**Comment by bkrztuk** [comment]
Could you show me a screen with this issue ? I'm asking because I've checked template on latest Chrome and can't see the problem.

**Comment by EmanuelFromFlorence** [comment]
yes for sure^^
let me edit the Dropbox link

**Comment by EmanuelFromFlorence** [comment]
yes for sure^^

while you wait..

do you think i shall be allowed to ask you to help us with our site ,even if its your template is free, while paying a fee for the customization i'm tryin to do?

2013/6/5 Bartłomiej Krztuk notifications@github.com

**Comment by EmanuelFromFlorence** [comment]
https://www.dropbox.com/s/ok8fl59ypzfq7s2/Chrome%20Iphone4%20issue%20.PNG

https://www.dropbox.com/s/rvpc5qsk0luhjxs/Chrome%20Ipad%20issue.png

here they are^^

**Comment by bkrztuk** [comment]
This is kind of Joomla! notice message, could you check the issue on default Beez/Prostar template ?

**Comment by EmanuelFromFlorence** [comment]
I did it,
you're right,
so its joomla related isn'it?
how to solve it?

**Comment by EmanuelFromFlorence** [comment]
I did it,
you're right,
so its joomla related isn'it?
how to solve it?

2013/6/5 Bartłomiej Krztuk <notifications@github.com <javascript:_e({},
'cvml', 'notifications@github.com');>>

**Comment by bkrztuk** [comment]
Yes it looks like Joomla! related issue when you get it on default template. Please look here >> http://forum.joomla.org/viewtopic.php?f=706&t=774242
