### ISSUE TITLE
Using module variation suffix

### ISSUE THREAD

**Issue by kmohandas** [GavickPro/Music-Free-Responsive-Joomla-Template#140]
Hi

The module variations as suggested in http://demo.gavick.com/free/may2012/index.php/template/lorem-ipsum/template-articles/module-variations are not reflecting on the output.

Since I am new to Joomla, could you please advise whether had I need to do something else apart from the suggestions as given in the above link?

Thanks, Mohandas

**Comment by bkrztuk** [comment]
Please make sure that you've used the space before suffix name like ' color' not 'color'. Could you provide URL to page where some suffix is not working ?

**Comment by kmohandas** [comment]
Hi, 

I used a space before suffix name in "Module Class Suffix" but could not get the relevant result. 

The link is www.thejewelleryexpo.com. I have used " HOT" suffix in "Next Events" module. This is for your information. 

Thanks in advance for your valuable suggestions.

**Comment by bkrztuk** [comment]
You need to use lowercase like 'hot' not HOT

**Comment by kmohandas** [comment]
It worked. Thanks again !!
