### ISSUE TITLE
Module variation for K2 items that behave like separated modules

### ISSUE THREAD

**Issue by creatiwebs** [GavickPro/Music-Free-Responsive-Joomla-Template#141]
Hi there!

I downloaded this great template for using it specially with my K2 items and showing them on my frontend. When configuring the News Show Pro GK4 module with data source K2 Categories and layout = " nsp", mode = normal I can show all the K2 items in only ONE column, and not as they were separated modules, like shown in the default home (when using the quickstart pack).

I mean, I need to show like each K2 Item is a different Pinterest pic (of course has no relation with Pinterest than the look&feel) so that mooMasonry order them nicely as it does with dfferent modules, but not in this case where it is showed in only one column without adjusting to the screen size.

Thanks!

**Comment by bkrztuk** [comment]
The only way is to publish separate module for every item and select item by ID in News Show Pro settings.

**Comment by creatiwebs** [comment]
Thanks for answering bkrztuk!
How bad to hear that. Do you think/know if it is technically possible to make some changes to that module to manage this?

Thanks!

**Comment by bkrztuk** [comment]
In Joomla! it is not possible that one module is visible on front-end as several modules. One module can have one HTML output, no matter what kind of module you use.

**Comment by creatiwebs** [comment]
Sure, I understand that, but what if by using CSS I give each K2 Item the behavor of a module like it is working right now? I mean it's only changing the template (which could not be less) and telling each K2 image using the News Show Pro to behave like a module, with mooMasonry and all the stuff.

Thanks!

**Comment by bkrztuk** [comment]
I don't think it is possible because NSP is loading in masonry box, in short words I have no idea how you want to include masonry box inside another masonry box.
