### ISSUE TITLE
selector for child elements in mobilemenu

### ISSUE THREAD

**Issue by responsive-cms** [GavickPro/Music-Free-Responsive-Joomla-Template#142]
I want to have the aliasnames of the menu in the URL for the articles. For several reasons I will not use the hidden menu workaround or SEF extensions. And in the menu I do not want to display any childcontent of the menu items.

So I change css for desktop mainmenu not to show childcontent, which works fine:

.gkMenu > ul div.childcontent-inner {
    display: none;
}   

But for the tablet/mobile menu, i can not find the locator, as it seems not to use ul li but only "select". But the childcontent is displayed with some margin, so it should be possible to locate it. But Firebug shows "select" for both: menu items, and menu items childcontent? 
For testing i tried following, but does not work:

.gkMobileMenu > ul div.childcontent-inner {
    display: none;
}   

and

.gkMobileMenu select.haschild{
    display: none;
}   

and

select.haschild {
    display: none;
}

and

select.childcontent-inner {
    display: none;
}

So how can i locate the childcontent in the mobile menu?

**Comment by bkrztuk** [comment]
Please open file **default.php** form layout directory and find this line

``` php
$this->mobilemenu->genMenu($this->API->get('startlevel', 0), $this->API->get('endlevel',-1));
```

then replace it to 

``` php
$this->mobilemenu->genMenu($this->API->get('startlevel', 0), $this->API->get('endlevel',1));
```

**Comment by responsive-cms** [comment]
Thank you for the quick response. I did, but it does not have any effect.?
check: http://wp1137341.server-he.de/www.synapsenkitzler.de_2013/

**Comment by bkrztuk** [comment]
Please try with this 

``` php
$this->mobilemenu->genMenu($this->API->get('startlevel', 0), 1);
```

**Comment by responsive-cms** [comment]
thx, but no effect too.?

**Comment by bkrztuk** [comment]
Could you provide me FTP details?

**Comment by responsive-cms** [comment]
you mean so you can login to the ftp account for the website?

**Comment by responsive-cms** [comment]
?

**Comment by bkrztuk** [comment]
Yes exactly, you can use mail [bkrztuk(at)gavick.com]

**Comment by bkrztuk** [comment]
Please open file layout/default.php and in line 89, find this: 

``` php
$this->mobilemenu->genMenu($this->API->get('startlevel', 0), $this->API->get('endlevel',-1));
```

and replace with 

``` php
$this->mobilemenu->genMenu($this->API->get('startlevel', 0), 0);
```

This is for sure solution for your problem. I want to make this changes in your installation but your FTP access don't allow me to save files.

**Comment by responsive-cms** [comment]
Pefect, works. Thank you very ! much. :-)
