### ISSUE TITLE
Rockwall Customize

### ISSUE THREAD

**Issue by mangawill** [GavickPro/Music-Free-Responsive-Joomla-Template#144]
Hi id like to change up the rockwall template to look like my skeleton

![skeleton](https://f.cloud.github.com/assets/3379990/736220/405a1164-e30f-11e2-8490-368ee8a88e3b.png)
Rockwall currently looks like this
![rockwall](https://f.cloud.github.com/assets/3379990/736227/7f1c59fc-e30f-11e2-88ae-c7f320632c76.jpg)

Id just really like to add the header part, and move the menu below the header

**Comment by dziudek** [comment]
Sorry but it is not the Rockwall issues section - please use our official forum for your questions: http://gavick.com/forums
