### ISSUE TITLE
Footer does't work in Safari

### ISSUE THREAD

**Issue by followreference** [GavickPro/Music-Free-Responsive-Joomla-Template#145]
Hi there,
The footer doesn't show up in Safari, even in the original demo version.
What's wrong with the code?

![screen shot 2013-07-02 at 17 34 53](https://f.cloud.github.com/assets/4922864/737724/e0283002-e334-11e2-8492-3d4b39cd7582.png)

**Comment by bkrztuk** [comment]
I've checked temlate on latest safari and here is the result >> http://d.pr/i/TqCX

**Comment by followreference** [comment]
I noticed that I have no problem with the footer in 6.X version, but in 5.1.9, as I said before, the footer just doesn't show up...

**Comment by bkrztuk** [comment]
This is particular browser rendering bug, the footer is working in other browsers without any problems. My advise is to update Safari browser.

**Comment by followreference** [comment]
You can't update to Safari 6.0.X unless you have Mountain Lion.

**Comment by dziudek** [comment]
But you can update to Safari 5.1 - as I see on this browser the problem doesn't exist. Sorry but we won't prepare an update for the rendering bugs in the browser which has less than 0.5% of the browsers market.
