### ISSUE TITLE
Music Free template in tablet mode on web

### ISSUE THREAD

**Issue by kfrench5** [GavickPro/Music-Free-Responsive-Joomla-Template#146]
Apologize if this was already covered...

Having issues with the template. It's in tablet mode on the web. how do I correct this using Joomla 2.5 

url: http://mogulsmag.com/ 

Thanks in advance,

**Comment by bkrztuk** [comment]
Could you tell me where exactly is the problem ? Or attach some picture with description ? I've visited your site using iPad and I don't see any issue.

**Comment by kfrench5** [comment]
This is my view on my computer... a lot of empty space to the right.... 
![screen shot 2013-07-09 at 7 01 53 am](https://f.cloud.github.com/assets/4734241/767626/172383c0-e887-11e2-94ad-8b11d5618c8c.png)

**Comment by bkrztuk** [comment]
Previously you wrote about tablet view now about the desktop one, so where is the problem ? Did you try to publish some more modules on the site because on empty home page it is hard to detect anything. My advise is also to use quickstart package instead of clean template.

**Comment by kfrench5** [comment]
I tried... this is the error msg I get: 
JInstaller: :Install: Cannot find XML setup file

**Comment by bkrztuk** [comment]
How to use quickstart you will find here >> https://www.gavick.com/documentation/joomla-templates/templates-for-joomla-1-6/quickstart-installation-for-joomla-1-6/
