### ISSUE TITLE
module overlay and vertical scrollbar

### ISSUE THREAD

**Issue by responsive-cms** [GavickPro/Music-Free-Responsive-Joomla-Template#147]
sidebar elements (modules) are overlaying, + resulting in horizontal browser-scroll-bar:
1)
if the browser-wdth is between 809-824 px
The Tablet min. width at the moment is 800, if i change it f.e. to 700, the same problem occurs at browser-window-width from 709 px to 724px.
see http://www.zukunftsmusik.eu/temp/screenshot-module-overlay-sidebar_2013.07.05.jpg
2)
in general tablet.css view
see www.zukunftsmusik.eu/temp/screenshot-module-overlay-sidebar_tablet-view_2013.07.09.jpg

for testing:
i deleted all custom css code, with no effect.
By giving those modules a module-class-suffix without a blank space, the problem does not occur.

livesite: http://wp1137341.server-he.de/www.synapsenkitzler.de_2013/test

tested in latest desktop+mobile (Android) version of:
Firefox, Opera, Chrome 
and IE 8

**Comment by bkrztuk** [comment]
Please publish instead of this two modules some lorem ipsum text for tests

**Comment by responsive-cms** [comment]
done, same problems, see
http://wp1137341.server-he.de/www.synapsenkitzler.de_2013/test

**Comment by bkrztuk** [comment]
Debugging with enabled compression is also quite difficult ....

Please try to add to tablet.css and mobile.css this code : 

``` css
#gkPage > .box.loaded {max-width: 50%!important}
```

and if this doesn't help disable css compression and cache.

**Comment by responsive-cms** [comment]
Oh, didn´t know that. css compression and css cache are disabled now.
Thank you. Now, 
related to topic 2), in tablet/mobile view, no more module overlaying. :-) But suffix double and full does not have any affect now. See box "lorem test 4 double" and "lorem test 5 full".
related to topic 1) problem still exists.

**Comment by bkrztuk** [comment]
The screen resolution is set to 810px and there is no overflow, please look >> http://d.pr/i/Zb0s

**Comment by responsive-cms** [comment]
Hi. I didn´t see the notification mail. Thx for your answer.

"The screen resolution is set to 810px and there is no overflow,"
Do you have a tip what i can do to solve this?

**Comment by bkrztuk** [comment]
Did you check my screenshot ?

**Comment by responsive-cms** [comment]
Yes.

**Comment by bkrztuk** [comment]
And could you mark the problem on screenshot ?

**Comment by responsive-cms** [comment]
Ah, sorry, my english...
Now i understand what you mean.

Yes, no more overlaying, as i wrote in https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/issues/147#issuecomment-20858394 
and "related to topic 1) problem still exists." = horizontal browser-scroll-bar:
See screenshot www.frazy.tv/temp/screenshot_2013-09-04-horizontal-scroll-bar.jpg
But only in Firefox and Opera. IE and Chrome is ok.

**Comment by bkrztuk** [comment]
URL to screenshot is not working.

**Comment by responsive-cms** [comment]
yes, i changed the url and go live.
the scrollbar is gone now. don´t know why.

but now i have again the overlay problem. As the modules with text only worked fine, as you can see modules with content do overlay. Any idea?
Screenshot: 
http://www.frazy.tv/images/diverse/debugging/screenshot-2013.09.08-module-overlay.jpg

**Comment by bkrztuk** [comment]
The only solution is to add additional media queries for this resolution which you use to test the layout. If you decide to set 800px for tablet mode it is obvious that no one from desktop mode will have window size in 809-824 pixels wide ... You can add your own media queries in override.css file.

**Comment by responsive-cms** [comment]
This sounds to me, that 800px for tablet mode is not usual/recommended?

**Comment by bkrztuk** [comment]
Of course that this is common resolution but your problem is 

> > if the browser-wdth is between 809-824 px

And belive me there are no desktop devices with this resolution. Anyway, I've provided you a solution - you need to add additional media queries for this screen size (between 809 and 824px)
