### ISSUE TITLE
Menu (duplicate description)

### ISSUE THREAD

**Issue by joomfatti** [GavickPro/Music-Free-Responsive-Joomla-Template#148]
First, thank you very much for this excellent template!/ I am new user of joomla

 'll do 2 separate questions. This is the first
I want to eliminate that little sign with the description of the menu item. (seems to occur with "mouse over" 
 Is it possible? / Where is the code to modify? 
attached screenshot (sorry for my English)

![menu1](https://f.cloud.github.com/assets/5103466/867286/ca588802-f6e5-11e2-852f-4a6f4bee5d91.jpg)

**Comment by bkrztuk** [comment]
There is no option to remove title attribute from menu item; this mouse over text is generated by browser based on menu item title attr.

**Comment by joomfatti** [comment]
In first place: Thanks a lot for your fast reply !!!

There is the URL (is under construction,  when I finish I will publish it) http://5minutosradio.com/ServidorPruebaJoomla/

I take this opportunity to ask another 2 questions: 

1)how to make my secondary pages look like in this example: http://demo.gavick.com/free/may2012/index.php/responsive-template (An item has a column width on the main page, but the same item has another column width on inside page) 
is there any way to assign a different template settings for each page? I know it can be done in joomla. How do I have to do with your template?

2) at top of the page (login/registrer module)  “sign in” and the icon are missing ( I guess it's because my menu is very wide)  ¿ is possible to make a menu with many items without changing “login/registrer” module position?

this is all for now . thank you very much  !!!!

**Comment by bkrztuk** [comment]
1) Please use this option http://d.pr/i/dKX5 and change content width for particular menu items or components in your case you should use com_k2

2) I don't see Sign In in top area of your site but I suspect that this is disabled right now. The only solution is to decrease space between menu items.

**Comment by joomfatti** [comment]
Bartlomiej:

1) : I changed the values ​​in "content width" but I can not solve the problems (nothing happens). Do not worry, I will try another solution. Thanks anyway.

# 2) (login/registrer module)  “sign in” -----> I will reduce spaces between menu items or size.  Solved THANKS !

3) the original question remained unanswered:

I seend screenshot again: ( problem: space between columns of txt y photo “item k2”, I would also like to reduce the sizes of the titles of the K2 articles (items)) URL:http://5minutosradio.com/ServidorPruebaJoomla/ in which folder is the code?

# 

if I need your help in the future I will ask again. 

many Thanks and  sorry for my english.. //

**Comment by joomfatti** [comment]
1) Please use this option http://d.pr/i/dKX5 and change content width for particular menu items or components in your case you should use com_k2 /// I DID IT WELL !!! WORKING THANKS A LOT !!!
