### ISSUE TITLE
space between K2 items (mainbody)

### ISSUE THREAD

**Issue by joomfatti** [GavickPro/Music-Free-Responsive-Joomla-Template#149]
Second question: where is the code to make more space between the items without having to place them in different modules? / Items are located on the main page. at mainbody section ///  send screenshot / sorry for my English. greetings from Argentina
![item1](https://f.cloud.github.com/assets/5103466/867313/321abb3a-f6e7-11e2-848d-a8fdd0249691.jpg)

**Comment by bkrztuk** [comment]
Please provide me URL to this page.

**Comment by bkrztuk** [comment]
Any updates ?

**Comment by joomfatti** [comment]
Bartlomiej excuse me,  I read your message today 

URL: http://www.cincominutos.info/ServidorPruebaJoomla/index.php/actualidad  (in this example items “gratis en avion” and “fin de feria” , the columns are close together)

http://www.cincominutos.info/ServidorPruebaJoomla/index.php/ocio Here in this example items “Quilmes rock 2013” and “Blancanieves sobre hielo”  same thing

Sorry 4 my english. Thanks a lot !

**Comment by bkrztuk** [comment]
Please add this code to **override.css** file in root/templates/gk_template_name/css directory :

``` css
.itemList article {margin: 10px !important}
```

and then just remember to enable "Use override CSS" option in template advanced settings tab.

**Comment by joomfatti** [comment]
Great. thank you very much again !!!

**Comment by bkrztuk** [comment]
I'm glad I could help you.
