### ISSUE TITLE
template enhacement : better css styling / menu params (GavickPro)

### ISSUE THREAD

**Issue by ghost** [GavickPro/Music-Free-Responsive-Joomla-Template#15]
additional description for menu item / major menu item.

**Comment by dziudek** [comment]
I've added support for the descriptions in the major menu item in this commit: https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/commit/f13fedfa7d41892e12fdea13bff71264c5bb07ea

**Comment by ghost** [comment]
okay, thanks @dziudek
