### ISSUE TITLE
Please Help me I can't find to edit and delete the module footer o copryght

### ISSUE THREAD

**Issue by oligo1** [GavickPro/Music-Free-Responsive-Joomla-Template#151]
Please Help me I can't find to edit and delete the module footer o copryght my site: http://camelap.com.mx/muestra/
![captura de pantalla 2013-08-01 a las 12 14 19](https://f.cloud.github.com/assets/5140369/895519/2ab1baca-face-11e2-8258-46a5650c8298.png)

**Comment by bkrztuk** [comment]
All is exaplained here, please look >> http://www.gavick.com/documentation/joomla-templates/templates-for-joomla-1-6/how-to-change-pages-footer/
