### ISSUE TITLE
Gavick Music Free: problems with iPad

### ISSUE THREAD

**Issue by naboman** [GavickPro/Music-Free-Responsive-Joomla-Template#153]
The submenu items appear creased always.

But really all items fit without problem inside with iPad screen

Here like it is shown in Windows (any browser)
![submenuissue-windows](https://f.cloud.github.com/assets/5196731/937635/126c8948-00e3-11e3-8580-552d0e8f7b36.jpg)

Here like it is shown in iPad
![submenuissue-ipad](https://f.cloud.github.com/assets/5196731/937634/12723dc0-00e3-11e3-9696-bfa69fbf44b3.jpg)

Thx

**Comment by bkrztuk** [comment]
Could you show me your site URL ? It is always easier to check CSS/HTML code on live site.

**Comment by naboman** [comment]
Here you are:
http://estudiocreativosevilla.com/pruebas/montear/
but you can test it with any demo of this template:
http://demo.gavick.com/free/may2012/

To see this submenu items, you  have to log in (with an iPad):
user: montero
password: 123123

Thx

**Comment by bkrztuk** [comment]
This is a responsive template and this is normal that you have different view on mobile and desktop device. This is how it was designed.

**Comment by naboman** [comment]
but in a Samsung galaxy tab 2 is shown the complete submenu, with all the items... but in an iPad it shown with little bars...

Is possible showing submenu elements in an iPad?

thx

**Comment by bkrztuk** [comment]
Please change tablet resolution in first template settings tab, when device have different screen resolutions it is possible that on one device full version is loaded and at second the tablet version.

**Comment by naboman** [comment]
thx.
I changed it but nothing happens
![tablet](https://f.cloud.github.com/assets/5196731/1137798/ce9b04de-1c66-11e3-9b4f-f4f81f20c3bb.jpg)

**Comment by bkrztuk** [comment]
For me all is working fine >> http://d.pr/i/Cq7i
