### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by nasrolog** [GavickPro/Music-Free-Responsive-Joomla-Template#155]
Salem,
j'utilisele template Music-Free-Responsive-Joomla pour mon site www.nasrolog.com
merci beaucoup
salem
N.Akacha.

**Comment by bkrztuk** [comment]
Please translate your message to english language.

**Comment by nasrolog** [comment]
sorry,
am using Music-Free-Responsive-Joomla template in my new website  www.nasrolog.com
thanks a lot and good luck.
Nasreddine.
