### ISSUE TITLE
Change text in the button "read more"

### ISSUE THREAD

**Issue by oligo1** [GavickPro/Music-Free-Responsive-Joomla-Template#156]
I need help please to change the text of "Read More"
![captura de pantalla 2013-08-19 a las 09 56 05](https://f.cloud.github.com/assets/5140369/986814/4321357a-08e0-11e3-95e9-96b3d55d968b.png)

**Comment by oligo1** [comment]
please helpmeeeee

**Comment by NormanUK** [comment]
See following file:
/language/en-GB/en-GB.mod_news_pro_gk4.ini
Line: 17

```
MOD_NEWS_PRO_GK4_NSP_READMORE="Read more"
```

Or if you are using different language then copy this file to your language folder and rename it to your language code en-GB part and than make your changes.

See you around...

**Comment by oligo1** [comment]
thanks for the answer!  Where I can modify the language of the forms of record?
![captura de pantalla 2013-08-20 a las 10 12 28](https://f.cloud.github.com/assets/5140369/994376/7b2852a2-09ab-11e3-87c4-35b06c8f26e1.png)
![captura de pantalla 2013-08-20 a las 10 12 17](https://f.cloud.github.com/assets/5140369/994377/7b444eda-09ab-11e3-801c-74b6083d7b5f.png)

And as the text modifies or to eliminate "hot" and "top"  
![captura de pantalla 2013-08-20 a las 10 16 45](https://f.cloud.github.com/assets/5140369/994392/bdb604d4-09ab-11e3-9536-024cfe062392.png)

**Comment by bkrztuk** [comment]
Please check languages/en-GB/com_users.ini file.

**Comment by oligo1** [comment]
please i need change the text or hide this texto "HOT"
![captura de pantalla 2013-08-21 a las 09 49 35](https://f.cloud.github.com/assets/5140369/1001745/163b4928-0a71-11e3-9d4b-c4243b03923c.png)

**Comment by oligo1** [comment]
i need modify this text "User Registration"  you can help me?
![captura de pantalla 2013-08-21 a las 09 51 17](https://f.cloud.github.com/assets/5140369/1001753/39f91764-0a71-11e3-85f0-613d02041c74.png)

**Comment by bkrztuk** [comment]
Badge : music_free/templates/gk_music_free/images/style1/badges.png

Registration: langauges/en-GB/com_user.ini or it is just meni item name.
