### ISSUE TITLE
Main Content Full width

### ISSUE THREAD

**Issue by FlyRide** [GavickPro/Music-Free-Responsive-Joomla-Template#158]
Hello,

This is about applying a full width display for the main content module on specific pages.  This to offer the the best viewing for a Kunena forum and a JEvents calendar.

Tried to follow the explanation on http://www.gavick.com/forums/music/full-page-content-option-in-music-free-26641.html but without success.

Is there a step by step process to follow?  Or another method?

Thanks,
Christophe

**Comment by bkrztuk** [comment]
You need to use this option >> http://cl.ly/image/2d3U0Q2Q2G1n
Please check your menu item IDs realted with this pages and set width to 10 for this ID in template settings.
