### ISSUE TITLE
mouse hover description Issue 

### ISSUE THREAD

**Issue by hosnyben** [GavickPro/Music-Free-Responsive-Joomla-Template#159]
hello, thank your for your solution to all issues ( that's work for me too ) . Now I have a probleme that I connot found a solution 

when a put the mouse on some areas it's appear a description as it's in the photo
![sans titre](https://f.cloud.github.com/assets/5375990/1075574/a94fb028-14d0-11e3-933a-de8469a65f01.png)

thank you!

**Comment by bkrztuk** [comment]
I can't help you without seeing the live code and site.
