### ISSUE TITLE
Bug after changing the footer's position

### ISSUE THREAD

**Issue by ivanwongtf** [GavickPro/Music-Free-Responsive-Joomla-Template#160]
I had asked that how to make the position of footer bar set to "relative", here is the related issue which was closed:
https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/issues/78

However, i encounter a bug when browsing with firefox.
I put these code in the template.css from copying in the tablet.css file :

```
@media (max-width: 1024px) {
// footer code from tablet.css file here
#gkFooter {
    position: relative;
}

html body {
    padding-bottom: 0!important;
}
#gkFooter {
    bottom: 0!important;
    box-sizing: content-box!important;
    left: 0!important;
    max-height: 41px;
    overflow: hidden;
    position: relative!important;
    right: 0!important;
    top: 0!important;
}
}
```

They work well in other browsers(e.g. Chrome) except Firefox. I found that it is out of place in Firefox.

Here is the screen shot:
http://i.imgur.com/gFSjzW2.jpg

and here is the link:
http://www.justdoevil.info

Sorry for my poor English.

**Comment by ivanwongtf** [comment]
Problem was fixed

**Comment by bkrztuk** [comment]
It is impossible to check your problem without your site URL
