### ISSUE TITLE
Social API – Facebook – send button - field is cutted

### ISSUE THREAD

**Issue by responsive-cms** [GavickPro/Music-Free-Responsive-Joomla-Template#161]
If u are logged in in facebook and click on "send", the apperaing window is not fully displayed / cutted.

livesite:
http://www.frazy.tv/music/whistleblower-song
screenshot:
http://www.frazy.tv/images/diverse/debugging/screenshot-fbsendbutton_2013.09.08.jpg

btw.: the g+ send field is displayed fine.

**Comment by bkrztuk** [comment]
Please add this code to _override.css_ file in root/templates/gk_template_name/css directory :

``` css
#gkContent,
#gkSocialAPI { overflow: visible !important}
```

and then just remember to enable "Use override CSS" option in template advanced settings tab.

**Comment by responsive-cms** [comment]
Perfect. Thx a lot!
