### ISSUE TITLE
Submit A Weblink Not Working

### ISSUE THREAD

**Issue by MsShona** [GavickPro/Music-Free-Responsive-Joomla-Template#162]
I've tried to add the "Submit A Weblink" item to a menu, and the resulting link does not work. It brings up a 403 Error.

I noticed that this also doesn't work on the Demo site. Although no error comes up...the page just doesn't load.

**Comment by bkrztuk** [comment]
Could you check whether the same happen on default Joomla! template like Beez ?

**Comment by MsShona** [comment]
Good call! Same error in the default template as well. I'll move over to Joomla's site to see if there is a fix over there. Thanks so much!
