### ISSUE TITLE
Removing Site Name From 'Create Account' Registration Form

### ISSUE THREAD

**Issue by MsShona** [GavickPro/Music-Free-Responsive-Joomla-Template#163]
The 'Create Account' link is in the login module position (in the upper right top of the template). However, I do not see an option to modify it in the module manager. I know that with menu items, you can specify whether or not the site title prints on the page. In this case, the 'Create Account' link is not a menu item.

Is there a way to prevent the site title from showing up above (like as a title) to the user registration form?

**Comment by bkrztuk** [comment]
Register link you can disable via template settings >> http://d.pr/i/ezq3

**Comment by MsShona** [comment]
Interesting, I did not know the control for that was there....thank you. However I would still like to have the link active. I just would rather not have the website title print on top of the registration form. The registration form prints without it (it instead says "Registration Form") when clicking the link listed under the registration link on my user's menu. If I could get the "Create Account" link's form to show like it does, that would be great.

http://doiluvu.net/index.php/members/registration-form vs. http://doiluvu.net/index.php?option=com_users&view=registration

**Comment by bkrztuk** [comment]
If you want to change the link for this register page you need to modify template code, please find this part in template/layouts/default.php file : 

``` php
<?php if($this->API->get('register_link', 1) && $userID == 0) : ?>
            <a id="btnRegister" href="<?php echo $this->API->URLbase(); ?>index.php?option=com_users&amp;view=registration"><?php echo JText::_('TPL_GK_LANG_REGISTER'); ?></a>
            <?php endif; ?>
```

and replace this part 

``` php
index.php?option=com_users&amp;view=registration
```

**Comment by MsShona** [comment]
That worked - thank you!
