### ISSUE TITLE
Facebook Like button at category blog view

### ISSUE THREAD

**Issue by serhatnarin** [GavickPro/Music-Free-Responsive-Joomla-Template#165]
Is there an easy way to show facebook like button to add each article in a category blog view at K2 or built in articles component? 

Just imagine 2 columns 5 rows articles with pages... 
every article has its own like button just like read more button...

look forward receiving a compact solution if possible

**Comment by MsShona** [comment]
Go to the Category in K2. Go to the Parameters on the right side of the page. Expand the area that says "Item View Options". In the area that says "Social Sharing" next to where it says "Facebook Button" select "Show". I think that will give you what you are looking for.

**Comment by serhatnarin** [comment]
Thank you so much Shona for your reply. 
Though this is not what I am looking for. It shows the like button at each item's page. 
This is why I wrote "in a category blog view" 

just like attached sample.
![likes](https://f.cloud.github.com/assets/4801794/1197671/e57820be-24e1-11e3-9765-6ead29fe9f27.png)

**Comment by MsShona** [comment]
I'm far from being an expert with this template, but I do not see where you can natively change the location of the Facebook like, or any of the other social sharing buttons to a different location other than the end of the article. Maybe this person is using a third-party plugin? There are plugins out there that will allow you more flexibility with placement. Like this one for example: http://extensions.joomla.org/extensions/social-web/social-share/facebook-share/16441

**Comment by bkrztuk** [comment]
Our social buttons work only with Joomla! articles but you can disable our social api features and use some 3rd party extension to display buttons in different place.
