### ISSUE TITLE
Bootstrap Not Working In Module Parameterss

### ISSUE THREAD

**Issue by MsShona** [GavickPro/Music-Free-Responsive-Joomla-Template#166]
I downloaded a third party module and published it into the 'bottom' module position. The module parameters use bootstrap to control the width by allowing you to choose how many columns the module should occupy. However, this doesn't seem to work. I have another module published to the bottom position and was able to get the desired layout by putting "double" into the module class suffix. However this module doesn't have this option.

Any ideas on how I can get the module to span more than one column?

**Comment by bkrztuk** [comment]
Music free is not bootstrap based template. Column size you can specify by suffix, please read this article >> http://demo.gavick.com/free/may2012/index.php/quick-guide

**Comment by MsShona** [comment]
Ok. I just went with another extension. One that has the field to modify the module suffix. Thanks!
