### ISSUE TITLE
Free Music Responsive Template

### ISSUE THREAD

**Issue by commculture** [GavickPro/Music-Free-Responsive-Joomla-Template#169]
Hi,

We have downloaded the free music responsive template and installed it on our site but when we view Jomsocial on our site it does reduce to fit the screen.
We have checked and it would appear that the width does not adjust for the iPhone.

Is this something you could help us with.

Thanks
Carly

**Comment by commculture** [comment]
Hi,

Can anyone help with this?

Thanks
Carly

**Comment by bkrztuk** [comment]
Sorry but it is impossible to help you without seeing a website. JomSocial as a 3rd party extension is beyond our support but firstly I need to look at your website.
