### ISSUE TITLE
Typography issue - search highlight mess up numblocks style

### ISSUE THREAD

**Issue by konradm1** [GavickPro/Music-Free-Responsive-Joomla-Template#17]
As in this topic https://www.gavick.com/forums/gavick-request/gk-typography-search-highlight-mess-up-numblocks-style-17856.html?p=83185#p83185

If we add this under  'p.numblocks span' selector : 

p.numblocks span.highlight {
font-size: 15px;
position: static;
width: auto;
display: inline;
}

should fix issue.

**Comment by dziudek** [comment]
Fix added :)

@bkrztuk - please include this fix in all Gavern 2.11/3.4 templates.
