### ISSUE TITLE
Something is wrong with bootstrap after update Joomla from 3.1.1 to 3.1.5

### ISSUE THREAD

**Issue by ghost** [GavickPro/Music-Free-Responsive-Joomla-Template#170]
Hi,
Thank you for you great job!
Really impressive template, that I've always seen on a number of websites.
After installation everything worked fine, but after upgrade Joomla from 3.1.1 to 3.1.5 something with bootstrap went wrong.
First, various field labels on the frontend stopped working. For example those for the contact pages.
Second, I faced the same problems when tried to edit with JCE from the frontend - label hints do not pop-up as usual in the JCE's form fields, and all interface looked strange.
I found that bootstrap stylesheets are not loaded in the head of the document.
When I added it manually, right layout and system buttons (images, readmore and so on) came back but labels popups.
I'd be very happy if you advice me how to adapt bootstrap and this template for the new Joomla version.

**Comment by ghost** [comment]
Well, I found this temporary workaround.

1) In the /templates/gk_music_free/layouts/blocks/head.php after

$this->API->addCSS($this->API->URLtemplate() . '/css/style'.$template_style.'.css');

add

$this->API->addCSS('media/jui/css/bootstrap.min.css');
$this->API->addCSS('media/jui/css/chosen.css');

2) After 

$this->API->addJS($this->API->URLtemplate() . '/js/gk.menu.js');

add

$this->API->addJS('media/jui/js/chosen.jquery.min.js');

---

**Comment by bkrztuk** [comment]
Our template don't use bootstrpa and that's why the files are not loaded. If you want to add bootrstrap CSS and JS your code is absolutely correct.
