### ISSUE TITLE
Website displays as tablet in new safari OSX mavericks

### ISSUE THREAD

**Issue by dpower717** [GavickPro/Music-Free-Responsive-Joomla-Template#172]
The website is loaded in a tablet version on the new OSX mavericks version.
The resolution for tablet is set to 800 px but the macbook resolution is way higher.
Can't figure out why it is loading the wrong version.

**Comment by bkrztuk** [comment]
Could you give me your site URL ? It is always easier to check CSS/HTML code on live site.

**Comment by dpower717** [comment]
Hi,

its http:// radu .nl

thanks

It's also on the demo website of music free.

**Comment by bkrztuk** [comment]
There is no problem for me on your website and on demo site >> http://d.pr/i/Q4ax I see regular desktop menu, maybe you wrongly understand the masonry layout but for sure the problem don't exist on latest OSX and Safari browser.
