### ISSUE TITLE
GK5/HTML Modules are Misplaced on Sidebar

### ISSUE THREAD

**Issue by himadri-ai** [GavickPro/Music-Free-Responsive-Joomla-Template#173]
I have became a huge Fan of GavickPro Templates, and decided to replicate Music (http://demo.gavick.com/free/may2012/) to my website www.edenage.com. 

I am using GK NewsPro 5 instead of 4.

All modules are misplaced on Sidebar position, I have rechecked that I have reproduced them properly from a Local Host quickstart Instance to my Hosting Space (No quickstart only Template). But they surely don't look like the Demo.

Please Let me Know where I am Going Wrong...

-- Himadri

**Comment by bkrztuk** [comment]
Some of your modules have wrong suffix, for example 'hot' without space before which change default 'box' suffix to 'boxhot' and cause problem with masonry layout. Please add space before suffix name in every module and this will resolve your problem.
