### ISSUE TITLE
google images

### ISSUE THREAD

**Issue by 8bitmuses** [GavickPro/Music-Free-Responsive-Joomla-Template#175]
Hi!
I'm experimenting with this joomla staff, and found your templates are most exciting over my search. So I installed - Music Free Responsive Joomla Template at: http://8bitmuses.com and it seems I can manage most of the stuff, but google don't want to index the images I uploaded. I change Robots.txt, still nothing.
Can you help me please?

**Comment by bkrztuk** [comment]
I don't think it is template issue, please look at solutions here >> http://forum.joomla.org/viewtopic.php?t=595556
