### ISSUE TITLE
Registration Form !! -- Warning Msgs and Forms Layout

### ISSUE THREAD

**Issue by himadri-ai** [GavickPro/Music-Free-Responsive-Joomla-Template#176]
Hi,

I have become a Huge Fan of Gavick Templates and trying to Learn Joomla with a LocalHost quickstart (Music J3!) and a Template only version in hosting account. Here I am trying to Replicate whats there in Quick Start in Hosting.

Website:: www.edenage.com
1. While doing Registration (signIn-->Create Acc) the Warning Messages for 'Pre-existing Email' ; 'Password didn't match' etc. are appearing at top of the Menu Bar, How we make it Inline to the Text Box.?
2. The Registration form is Showing K2 users registration, How do we enforce Joomla Registration form as in quickstart.?
3. Recaptcha Though enabled (with Keys) not showing in Registration Form
4. -- Bubble is showing HTML content. (Home Page- Scroll Down)
   -- Quote Block is showing without "quotation " marks

Pardon me , If I have too many Issues, But I know these might be easy solutions for the Person who knows..Please Help 

![regis](https://f.cloud.github.com/assets/5517381/1521215/5564a5fa-4b8e-11e3-8e87-89e31f2866b7.jpg)

**Comment by bkrztuk** [comment]
Hi,
1. Joomla! error messages are showing in one place and there is no option to move them inside component view.
2. You can disable K2 registration in K2 settings in backend, option is called 'Use K2 user profiles' or something similar.
3. If you use K2 register form it is probably K2 issue not template problem, please switch to Beez and compare results.
4. Could you give me your site URL ? It is always easier to check CSS/HTML code on live site.

**Comment by himadri-ai** [comment]
Hi,

Thanks a Lot for your response ..
Website URL :: www.edenage.com

#1 No Option!! , Then We need to hack the core files, am working on it..
#2 I have Solved myself as per you said.
#3 Its showing Recaptcha But not Validating (Could not Find Socket exception) , am working on it.
#4 Website URL :: www.edenage.com ... This will be a great Help !!

-- Himadri

**Comment by bkrztuk** [comment]
#3 could you check whether the same happen on Beez - default Joomla! Template ?

**Comment by himadri-ai** [comment]
Hi bkrztuk,

I have removed Captcha as of now..

Thanks, Himadri
