### ISSUE TITLE
position login withput modal, or position lang on all devices

### ISSUE THREAD

**Issue by Explorerik** [GavickPro/Music-Free-Responsive-Joomla-Template#177]
Hello I using Improved ajax login and register to autorization and registration. When I put this module to 'login' module position it opens in modal of module position, but Improved ajax login and register uses own modal (I getting modal in modal :D) . I put it to the 'lang' position and it works well, BUT it is doesn't shows in mobile layot. I need to delete modal from 'login' module position (make it as other positions) or make position 'lang' display at all devices. 
How can I do that?
Link: www.mainriff.ru
Best regards!

**Comment by Explorerik** [comment]
No ideas? Really need to fix it.

**Comment by bkrztuk** [comment]
The only way is to remove our code from gk.script.js which show login in pop-up window.
