### ISSUE TITLE
pics display of elements in K2

### ISSUE THREAD

**Issue by Loadlucas** [GavickPro/Music-Free-Responsive-Joomla-Template#179]
Hello,
I m using Music free template on (http://www.technical-security.be) and elements on categories are displaying pics in low resolution ... i ve check the  categories configuration and nothing weird ...
Any ideas ?

Thank you

Loadlucas

**Comment by bkrztuk** [comment]
Probably K2 generates thumbnails in low quality. The size of image inside K2 you can change in global K2 configuration.

**Comment by Loadlucas** [comment]
Hello
I didn't seen the K2 global configuration .... Did you think i must reload the pics after the global config change to retreive a good quality image or delete cache or something else ... 

Thank you and happy new year ...

**Comment by bkrztuk** [comment]
Yes you need to re-configure global K2 settings and then probably upload files again to overwrite old low quality thumbnails.

**Comment by Loadlucas** [comment]
Hi
Thanks for all the advice ... That help a lot !

Aldo Lucaselli - Loadlucas prod. -
Le 3 janv. 2014 16:12, "Bartłomiej Krztuk" notifications@github.com a
écrit :
