### ISSUE TITLE
Unable to log to joomla panel

### ISSUE THREAD

**Issue by teitbite** [GavickPro/Music-Free-Responsive-Joomla-Template#18]
After installation users cannot log to joomla panel. It's because 2 users got "admin" as login. After removing the one with ID 42 all works fine.

**Comment by bkrztuk** [comment]
@teitbite the problem occurs on latest version ? We had a problem with this issue and it was fixed several days ago.

**Comment by teitbite** [comment]
Looks like it. I've tried and installed this template not more than 2-3 days ago to check if user is right. Than I found that it's because of admin duplication. Till than there were 3 reports more.

**Comment by dziudek** [comment]
I've downloaded the package today and it is working fine for me - please check it now to be sure, but it should works fine now.

**Comment by teitbite** [comment]
Yes. I can see admin is renamed to gkadmin, so it ok now :)
