### ISSUE TITLE
Content width 0

### ISSUE THREAD

**Issue by Explorerik** [GavickPro/Music-Free-Responsive-Joomla-Template#180]
Hello! Really like this template! But i have 1 problem. I want to make some menu items without content block ( only with sidebar  modules ). What I have to do to be able to choose content width 0 in control panel? Thank you!
![2345432345](https://f.cloud.github.com/assets/5251740/1826833/0a99ef44-7212-11e3-8538-0fbe1d422d2f.png)

**Comment by bkrztuk** [comment]
The best solution is just hide this elements for particular pages (by default Joomla! always display _content_ area). more about this you will find here [http://www.gavick.com/documentation/general-questions/how-to-disable-content-on-selected-joomla-pages/](How to Disable Content on selected Joomla Pages?)

**Comment by Explorerik** [comment]
Thank you very much! It works! but code: 
.noMainbody #gkMainbody { display: none !important}  doesn't work. I changed #gkMainbody to #gkContent and it works! 
Thanks again for your answer!
