### ISSUE TITLE
Server 500 error while failed login

### ISSUE THREAD

**Issue by iosoft** [GavickPro/Music-Free-Responsive-Joomla-Template#183]
hello,

I am getting a Server 500 error while failed login.
http://my-lab.wink.ws/j25/index.php?option=com_users&view=login
now, without filling the username nor password, just click [Login]

Instate of error msg it is giving 500 error.

**Comment by iosoft** [comment]
May be Facebook login also failing due to the same reason, but not sure.

**Comment by bkrztuk** [comment]
Please check whether the same happen on default Beez template because I'm not sure that this is template issue.

**Comment by iosoft** [comment]
FB login not working.
Please help.

**Comment by iosoft** [comment]
Error msg: "Username and password do not match or you do not have an account yet."

**Comment by bkrztuk** [comment]
Did you get this error message only when you register using login with facebook or even with default login form? Did you configure your FB Login like it is described here » [url=http://www.gavick.com/documentation/joomla-templates/templates-for-joomla-1-6/how-to-implement-the-login-with-facebook-feature/]How to implement the Login with Facebook feature[/url]
