### ISSUE TITLE
gkPopupOverlay

### ISSUE THREAD

**Issue by serbitek** [GavickPro/Music-Free-Responsive-Joomla-Template#189]
2 small questions ... 

1 - in google crhome, when you click on sign in, the parameter gkPopupOverlay not work the first vez.When you click a couple, it works perfectly. 
In Internet explorer works perfectly. 

2 - when I login to facebook, it works perfectly, but when I logout, the facebook session is not closed  only  joomla.sesion  could fix this? 

thank you very much and sorry for the translation to English .. ;-)

**Comment by bkrztuk** [comment]
The option is called Login with facebook not login and logout with facebook :) and work only to authorize user to Joomla! but it is not related with any other facebook option so you need to logout on facebook if you want to quit session on this website.

**Comment by serbitek** [comment]
ok understood. 
with respect to the other problem .. any solution?

**Comment by iosoft** [comment]
I face the same issue -

1 - in google crhome, when you click on sign in, the parameter gkPopupOverlay not work the first vez.When you click a couple, it works perfectly.
In Internet explorer works perfectly.

**Comment by bkrztuk** [comment]
Any URL to your website?

**Comment by iosoft** [comment]
http://my-lab.wink.ws/j25/

problem in Google Chrome only.
actually your demo site also has the same issue.

http://demo.gavick.com/free/may2012/

**Comment by bkrztuk** [comment]
I've visited your website on latest chrome and can't see the problem with the pop-up, also on our demo all is working fine, please look → http://cl.ly/image/0I1p453M3l1h

**Comment by serbitek** [comment]
The problem was the downgrade of my google crhome .After upgrade, everything works ok 

Thank you.
