### ISSUE TITLE
problem changing copyright text

### ISSUE THREAD

**Issue by crisf9** [GavickPro/Music-Free-Responsive-Joomla-Template#19]
when I put my copyright text in the template features "footer elements" the link that is used as a placeholder "Free Responsive Joomla! Template" stays in the footer along with my text. the other text "Template Design ©" and  "GavickPro" get replaced just fine.

this only happened in the latest version (3.3.2) of the template. it worked fine before.

**Comment by dziudek** [comment]
Yes, I've got a request to leave this text always with the other footer texts. If you really need to remove this text, please edit file **layouts/blocks/footer.php**.

**Comment by snowantje** [comment]
I know the topic is closed but i have the same 'problem' as crisf9. I don't know where i can find layouts/blocks/footer.php... If i search in the template administration - Template manager/Styles I can find layout. But in here I see only the option "Blocks animation" off or on...  nothing else with blocks... where do I have to search for the file you mentioned here above. Do I have to be in Template manager/Templates? But then? 
Thank you a lot for your help!

**Comment by dziudek** [comment]
Hi,

The layouts/blocks/footer.php is a path to file in the template directory on your server.

**Comment by snowantje** [comment]
Hello!
Thank you for your answer. After quit a time i figured it out by checking the files at my FTP programma... 
Here I found the path and could finally change the file.
