### ISSUE TITLE
Update joomla version

### ISSUE THREAD

**Issue by pedorret** [GavickPro/Music-Free-Responsive-Joomla-Template#197]
Hi, I'm trying to use this template and use quickstart install on local and on web server. The joomla version of quickstart template is 3.0.3 and if I try to update on both installation all crashed and it's impossible to see the web.
How can I updated the joomla version?
I try downloading Joomla_3.4.0-stable-Update_Package overwriting the files but don't work.

**Comment by dziudek** [comment]
Hello,

This template is older than 3 years and is no longer supported.

**Comment by pedorret** [comment]
Ok, but why is available on the website in that case??  And this have no relation with joomla update
