### ISSUE TITLE
function : display latin extended google / squirell fonts

### ISSUE THREAD

**Issue by ghost** [GavickPro/Music-Free-Responsive-Joomla-Template#2]
is missing !

**Comment by dziudek** [comment]
In general it is not missing - it depends from following things:
- in the Google fonts you can add subset parameter to the font URL i.e for Open Sans:

``` php
http://fonts.googleapis.com/css?family=Open+Sans&subset=latin,latin-ext
```
- In the squirell fonts you have to generate a font-face kit with using specific subset on the font-face kit generator page.

Of course not all fonts supports this feature.

**Comment by ghost** [comment]
yeah, thanks @dziudek. it is understandable, unfortunately - not for everyone ;)
