### ISSUE TITLE
Align page to center when there is no module assigned to sidebar

### ISSUE THREAD

**Issue by donleegk** [GavickPro/Music-Free-Responsive-Joomla-Template#20]
Hi mate,

Currently when there's no module assigned to sidebar position, the main content is still aligned to left, this should be fixed to aligned to center instead, I have tried some solutions already but they didn't work so I have to ask here.

Thanks,

**Comment by bkrztuk** [comment]
Explained via Skype :) closed.

**Comment by Rittick** [comment]
can you explain the same to me... i am dealing with the same problem

**Comment by bkrztuk** [comment]
This is not the problem this is how moomasonry script is working. Template is designed to display modules always from left to the right side.

**Comment by Rittick** [comment]
What if i remove the masonry effectr from bottom position so that
bottom modules can be in center position.. Please assist

On 7/28/12, bkrztuk
reply@reply.github.com
wrote:

> This is not the problem this is how moomasonry script is working. Template
> is designed to display modules always from left to the right side.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/issues/20#issuecomment-7333439

## 

Best wishes
~rittick~
