### ISSUE TITLE
Problem with k2's categories top menu

### ISSUE THREAD

**Issue by ivanwongtf** [GavickPro/Music-Free-Responsive-Joomla-Template#21]
There is a k2's categories top menu under the main menu in this template,i had a problem about this.
Because i have many categories,so they made the menu very long,so i want to hide all the sub-category and just show the main category.I am a newbie of joomla so I don't know how to change this,can anybody help me?
Sorry for my bad English...

**Comment by bkrztuk** [comment]
Hi,

Next time for this kind of questions please use our forum gavick.com/forum ... so to cut menu list to one level you need to open this module settings via module manager, then under "Categories List (Menu) Settings" in field "Levels to render" set "1" value. This will hide all sub-categories and show only first level of menu.
