### ISSUE TITLE
menu improvements suggestion j! 2.5 and 3.0 : menu items

### ISSUE THREAD

**Issue by ghost** [GavickPro/Music-Free-Responsive-Joomla-Template#22]
the last menu items and its columns [ on the right ] should be expanded to the left !

---

co z aktualizacją tego szablonu do najnowszego wydania frameworka ?

**Comment by dziudek** [comment]
But this feature is implemented in the tempate - I've even checked the latest version now and I see that the menu appears correctly on the left side. Maybe the script on your installation isn't working?

---

Następna aktualizacja pojawi się w przyszłym tygodniu, ponieważ teraz pracujemy nad nowym komercyjnym szablonem a dodatkowo wersja 3.4 Music Free będzie zawierać przebudowaną górną część strony (toolbar).

**Comment by ghost** [comment]
will check again ... 

---

zrozumiałe. tę dla 3.0 kiedy planujecie wydać ? tam można by ponad pozycje logo i mainmenu, dodać jedną pozycję top lub podzielną top1/top2 ;)

**Comment by dziudek** [comment]
Wydamy wtedy kiedy J! 3.0 będzie dostępna ;)

**Comment by ghost** [comment]
możesz pokazać jak rozplanowałeś refaktoryzację tego układu dla music free ?

**Comment by dziudek** [comment]
Wszystkie informacje o układzie będą dostępne przy wydaniu wersji 3.4.

**Comment by ghost** [comment]
hehe dobre, pytasz o sugestie, wprowadzasz na ich podstawie zmiany i twierdzisz, że pokażesz je dopiero jak wydasz, tak jakby schemat układu lub zrzut ekranu był tajemnicą. 

pomijając już fakt totalnej olewki w stosunku do kontrybutora, bynajmniej dziwne podejście, być może dlatego jest tu aż 5 osób, nie licząc was z gavicka z czego 1 aktywna. no ... to powodzenia z takim podejściem. po co ten github ?

**Comment by dziudek** [comment]
Tak to wszystko jest tajemnicą, bo obecnie mam kilka wariantów i w wolnym czasie określam ich wszystkie za i przeciw - udostępnienie czegoś na githubie nie oznacza zezwolenia na traktowanie autorów jako teamu prywatnych programistów, którzy będa spełniać wszystkie zachcianki i wtrącania się w każdy detal ich pracy. Jeżeli ma się własną koncepcję - są inne sposoby, patrz: ostatni paragraf.

Ilość osób na githubie nie wynika z tego, że sugestie są olewane (chciałbym w issues Music Free zobaczyć olane sensowne sugestie) ale z tego, że ludzie uwielbiają brać za darmo i jeszcze narzekać (wystarczy zobaczyć ile osób szablon pobrało), zamiast ruszyć cztery litery i dodać coś od siebie - przy czym dodać coś od siebie, wcale nie oznacza zalewania sekcji issues kolejnymi postami, ale oznacza przede wszystkim skorzystanie z pull request - to jest prawdziwa kontrybucja w projekcie, bo wymaga ona realnego nakładu pracy a nie tylko gdybania, chcenia i narzekania w postach sekcji issues.

Ogólna konkluzja warta zapamiętania:

Jeżeli chce się przepchnąć jakiś własny pomysł to dużo szybciej zrobi się to przez pull request niż posuwając się do granicy upierdliwości w issues.

**Comment by ghost** [comment]
chłopie, kto cie tu naciska, gdyba i narzeka, jeden komentarz, jedna odpowiedź. kiedy jest wątpliwość - krótka dyskusja. nie wiem kto cie tam męczy całymi dniami i nocami i ... nawet nie próbuję w to wnikać.

zapytałem jak będzie w oparciu o te moje sugestie wyglądał układ, bo nie chcę tu duplikować czyjejś pracy. 

jeżeli dodaję sugestię, to wyraźnie piszę "sugestia", "pomysł" czy jakoś podobnie. nigdzie nie jest napisane "żądam".

nie wiem ile osób szablon pobrało, bo nie posiadam takich statystyk. podałem wam jedynie na tacy pewnego rodzaju rozwiązanie, którego ten szablon, jak i patrząc po nowych wydawanych komercyjnie - nie miały.

**Comment by dziudek** [comment]
Sugeruję przeczytać chociażby swój ostatni post i wyczuć jakie nacechowanie emocjonalne sobą reprezentuje, zamiast się dziwić moim odpowiedziom. Generalnie mamy EOT, bo naprawdę szkoda mojego cennego czasu na takie dyskusje.
