### ISSUE TITLE
 Can not change the font

### ISSUE THREAD

**Issue by jan09** [GavickPro/Music-Free-Responsive-Joomla-Template#28]
No matter what I set in the parameters, it changes nothing.
Must be something in "Body - selectors" - be entered or in "Header - selectors"?

Sorry for my bad english.

---

Egal was ich in den Parametern einstelle, es ändert nix.
Muss zwingend etwas bei "Body - selectors" oder "Header - selectors" eingetragen werden?

Schöne Grüße 

Jan

**Comment by bkrztuk** [comment]
Please paste here what selectors you have set in "Body" and "Headers" I'll check the code.

**Comment by jan09** [comment]
So far I have nothing entered in selectors. Must be entered something?

For example I want for the content and headlines the font: Verdana.
For the main menu a google font.

---

Bisher habe ich nix bei selectors eingetragen. Muss etwas eingetragen werden?

Zum Beispiel möchte ich für den Inhalt und Überschriften die Schriftart: Verdana.
Für das hauptmenü eine google-Schriftart.

**Comment by bkrztuk** [comment]
Yes you must specify some selectors to make it working. Please in "Body - selectors" use 'body' and change font, this should affect on base template font. More info you will find also on our wiki (wiki.gavick.com).

**Comment by jan09** [comment]
Ahh okay. So it's not as easy as I thought. I'm still learning ...
What should I configure to allow the main menu gets a different font?

**Comment by NormanUK** [comment]
For Main menu top level use below selector in your chosen font group.

<pre>
<code>
.gkMenu > ul > li
</code>
</pre>
