### ISSUE TITLE
styling / position : native joomla language switcher module

### ISSUE THREAD

**Issue by ghost** [GavickPro/Music-Free-Responsive-Joomla-Template#3]
is missing on all gk_templates !

**Comment by dziudek** [comment]
It will be added in the nearest update also for all GK templates (in Gavern 2.11/3.4) :)

**Comment by dziudek** [comment]
@bkrztuk - please add this issue for Gavern 2.11/3.4

**Comment by ghost** [comment]
thanks @dziudek. my suggestion is to add an expanded module at the top of the page ( e.g. somewhere before login / register section ). 

also, would be great to see ( at the same section ), additional module positions, called e.g. block1 and block2 prepared especially for k2store / j2store / redshop / vm shopping cart module ... and one empty, to be used by the administrator. 

these module positions, creates a complete solution, which we might call : front-end user toolbar.

what do you think ?

**Comment by dziudek** [comment]
@partizanpl - I'll analyze it, I'll report everything after implementation here :)

**Comment by ghost** [comment]
thanks @dziudek ;)

**Comment by dziudek** [comment]
- Typography small iconset to use in the new positions (element as [icon] + text which will shrink to [icon] on the mobile view)

**Comment by ghost** [comment]
u mnie stylu dla tego modułu nadal brak.

**Comment by dziudek** [comment]
@partizanpl - wygląda na to, że ten issue przepadł zamknięty przeze mnie przez pomyłkę, co widać po moim ostatnim komentarzu.

**Comment by ghost** [comment]
@dziudek to nic, jedynie odkopałem, ale funkcja na prawdę wyczekwiana.

**Comment by ghost** [comment]
jezzzu już guzików nie widze gdzie co napisane. włącz - wyłącz jak maszyna ...

**Comment by ghost** [comment]
dzięki.

**Comment by xristof** [comment]
Hi there. 

It seems that the language selector it is still not working (even in lang position). can you please suggest if there is any solution on this issue.

**Comment by dziudek** [comment]
@bkrztuk - please look tommorow at the problem above.

**Comment by bkrztuk** [comment]
@xristof please check whether your language switcher is working on default template 'Beez' because for it is problem with your language configuration not with the template. Language switcher should work on any position not only on 'lang'.
