### ISSUE TITLE
Modules in sidebar not loading with Image Gallery in K2 active

### ISSUE THREAD

**Issue by turbonium412** [GavickPro/Music-Free-Responsive-Joomla-Template#30]
Hi,

I have just installed the joomlaworks Simple Image Gallery Pro plugin. As soon as I load up images to a K2 item as an image gallery all but the first module in the sidebar disappear (or rather don't load). Apparently the image gallery plugin doesn't like moomasonry... Any ideas how to resolve this?

Thanks and kind regards,

Clemens

**Comment by dziudek** [comment]
Hi,

Could you provide an URL to your website with the described problem? Then I'll be able to tell more about the reason of you problems.

**Comment by turbonium412** [comment]
Hi Tomasz,

the website is still under development but the page it concerns is here for now:

http://komm.li/expotrade/index.php/k2-tags/2011-08-04-23-47-02/item

There should be two more modules loaded in the sidebar – they only load, if I take out the gallery.

Thanks for taking time to check it out!

Clemens

Am 25.08.2012 um 22:34 schrieb Tomasz Dziuda:

**Comment by turbonium412** [comment]
I just noticed that it seems to be related to the settings in the jw Simple Image Gallery Pro plugin. Certain popup engine settings and layout templates for the image gallery allow the page to load correctly while others do not. I'd still be interested to know where the problem is but if necessary I could work with one of the combinations that let the page and modules load correctly.

Thanks and kind regards,

Clemens

**Comment by dziudek** [comment]
It seems that some settings cause that the plugin loads code which cause JavaScript errors with the template code - that cause also problems with the sidebar. I suggest to use settings which doesn't cause the JavaScript conflict.
