### ISSUE TITLE
add suffix module

### ISSUE THREAD

**Issue by firosyd** [GavickPro/Music-Free-Responsive-Joomla-Template#31]
Hi,
I am not getting change the suffix module in the gavick free music template. I don't know the suffix's name to change the background of the module. I tried several names, but nothing results. Help me, please?
Thank you

**Comment by bkrztuk** [comment]
Hi,

All available suffixes you can find here http://demo.gavick.com/free/may2012/index.php/template/lorem-ipsum/template-articles/module-variations

**Comment by firosyd** [comment]
Thank you, guy. I'm going to test the modules. Great hint! Regards.
