### ISSUE TITLE
reCpatcha

### ISSUE THREAD

**Issue by ManfredHeindl** [GavickPro/Music-Free-Responsive-Joomla-Template#33]
tutorial:
i install "gk_music_free_quickstart_J25".
i make the setting in the recpatcha plugin.
reCaptch wors fine.

i install Joomla_2.5.6-Stable-Full_Package_German or Joomla_2.5.6-Stable-Full_Package.
i install gk_music_free.
i make the same setting like the gk_music_free_quickstart_J25.
reCpatcha is wrong. i see a blank rapctha window.

**Comment by dziudek** [comment]
The reCAPTCHA is working without the gk_music_free template (on the default Joomla! templates)? Because this problem can be not connected with the template Music Free.

**Comment by ManfredHeindl** [comment]
thanks for you answer.
in the gk_music_free_quickstart_J25 works all fine. gk_music_free template is on default.
in mod_gk_register i found this entry "<div id="gk_recaptcha"></div>.
but i cannot find a module or plugin called "gk_recaptcha"

**Comment by dziudek** [comment]
In general please don't use the mod_gk_register module with recaptcha, because due problem of creating two instances of reCAPTCHA on one page we have resigned from using this module.

**Comment by ManfredHeindl** [comment]
i dont use gk_recaptcha! its a DIV entry in mod_gk_register on line 47.
let me tell you what i done.
i copied the joomla.sql from the gk_music_free_quickstart_J25 to the Joomla_2.5.6-Stable-Full_Package_German.

reCaptcha works! i think the bug is in the "joomla.sql"

**Comment by dziudek** [comment]
No, probably you haven't specified the captcha engine in the site settings - please remember that you have to also set it in "Global configuration -> Site -> Default captcha" and in the "User Manager -> Options -> Component -> Captcha".

**Comment by ManfredHeindl** [comment]
thanks you so much for helping me.
