### ISSUE TITLE
footer all time 100% screen resolution, but moved

### ISSUE THREAD

**Issue by svanschu** [GavickPro/Music-Free-Responsive-Joomla-Template#34]
There's an CSS issue if not using all space of screen. http://www.diigo.com/item/image/25qjf/49wm

Setup columns 3 and footer is still 100% screen resolution.

**Comment by dziudek** [comment]
Could you provide an URL to your website? Are you sure that you have no syntax error in the page content? I'm asking, because I've checked the demo page with sidebar modules disabled (I've left only the article) and I see that all is fine with the footer.

**Comment by svanschu** [comment]
Problem the website is inside private campus network and without a account you can't access :/

The footer looks same with SobiPro, XMap, redEvent and Kunena. And else I have not changed anything at the template, only backend options the template provide …

**Comment by dziudek** [comment]
Please validate the website HTML code and please look for the unclosed tags in the validation results.

**Comment by svanschu** [comment]
I used a pretty empty page and there are only two issues: 

Line 7, Column 44: Bad value title for attribute name on element meta: Keyword title is not registered.
 <meta name="title" content="Alle Menüs" />

 Line 13, Column 843: Bad value only screen and (max-width: 1000px), only screen and (max-device-width: 1000px) and (-moz-max-device-pixel-ratio: 1.5), only screen and (max-device-width: 1000px) and (-o-max-device-pixel-ratio: 1.5/1), only screen and (max-device-width: 1000px) and (-webkit-max-device-pixel-ratio: 1.5), only screen and (max-device-width: 1000px) and (max-device-pixel-ratio: 1.5), only screen and (max-device-width: 2000px) and (-moz-min-device-pixel-ratio: 2), only screen and (max-device-width: 2000px) and (-o-min-device-pixel-ratio: 2/1), only screen and (max-device-width: 2000px) and (-webkit-min-device-pixel-ratio: 2), only screen and (max-device-width: 2000px) and (min-device-pixel-ratio: 2) for attribute media on element link: Expected a letter at start of a media feature part but saw - instead.
…only screen and (max-device-width: 2000px) and (min-device-pixel-ratio: 2)"  />

I don't think that they issue this …

**Comment by dziudek** [comment]
no, these issues are strictly connected with the prefixed functions in the media queries. But without the URL I cannot help more :/

**Comment by svanschu** [comment]
The computed style of the footer is 1905px, when I disable position fix, the computed width is 960px.

Running chromium 20 Fedora, could it be a feature which is not correctly implemented in that chrome version? Hmm in Opera (11.60) and Firefox it is also.

I only could open a remote with Teamviewer …

**Comment by dziudek** [comment]
The only thing you can do is moving the footer before 

``` html
</body>
```

 set for it position:static, set padding-bottom:0 for body, and remove padding from the gavern framework logo.

You can also set:

``` css
margin: 0 -16px!important;
width: auto!important;
```

for the footer element to expand it for the 100% width. And that's all what I can suggest. If the footer doesn't appear at the bottom, then it means that it is a more complex problem with the structure, which is a custom work beyond our support.

**Comment by svanschu** [comment]
Would it help sending you a static copy of the site? Or do you want backend also?

**Comment by dziudek** [comment]
yes, you can send it to dziudek[at]gavick[dot]com but I'll be able to work with it at the earliest in Sunday, because currently we are busy with releasing the new template.

**Comment by svanschu** [comment]
Ok will send you. We want to release earliest on Monday, so don't rush. It's a small bug …

Edit: Send it. Thx

**Comment by dziudek** [comment]
I've checked your website and it seems that you shoulde make following change in the layouts/default.php file:

``` php
    <?php $this->layout->loadBlock('footer'); ?>
</div>
```

to:

``` php
</div>  

<?php $this->layout->loadBlock('footer'); ?>
```

**Comment by svanschu** [comment]
Ok now it looks not buggy ^^ Thx.

Will that get into release?

**Comment by dziudek** [comment]
In general it isn't a common problem but to avoid it in some cases I've added this change to repo: https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/commit/4d3059ea7468a1073f45f969f2752b52c037d5f5
