### ISSUE TITLE
Uncaught TypeError: Cannot call method 'getElement' of null 

### ISSUE THREAD

**Issue by svanschu** [GavickPro/Music-Free-Responsive-Joomla-Template#35]
// toolbar action
    if(document.id('gkToolbar').getElement('ul')) { --> Uncaught TypeError: Cannot call method 'getElement' of null 

gk.script.js line 117

**Comment by dziudek** [comment]
You're right - please change this line to:

``` js
if(document.id('gkToolbar') && document.id('gkToolbar').getElement('ul')) {
```

I'll add this fix in the nearest update for this template.

**Comment by svanschu** [comment]
It works. Thx!
