### ISSUE TITLE
jQuery should get loaded first not last

### ISSUE THREAD

**Issue by svanschu** [GavickPro/Music-Free-Responsive-Joomla-Template#36]
Else it breaks othe components JS like redEvent etc. 

http://www.diigo.com/item/image/25qjf/19nq --> Pushin select venue
result: http://www.diigo.com/item/image/25qjf/a6e3

**Comment by dziudek** [comment]
jQuery isn't a part of this template so it isn't a template related problem - the problem is caused by the component which loads the jQuery.

**Comment by svanschu** [comment]
Ok that's strange, because if I use beez 20 jQuery is not loaded and if I use your template jQuery get's loaded over google api

**Comment by dziudek** [comment]
So maybe some module which is loaded in our template uses jQuery? And on the beez20 template there is no module position with this module so the jQuery isn't loaded?

**Comment by svanschu** [comment]
Hmm since I changed the JS Error from the other ticket [#35], the js of Kunena and redEvent works also again …
