### ISSUE TITLE
Increasing the height of the footer bar

### ISSUE THREAD

**Issue by turbonium412** [GavickPro/Music-Free-Responsive-Joomla-Template#38]
Hi,

is there a way to increase the height of the footer bar without overlapping the main content? I need to place several modules in the footer bar of the template. When I increase the height of the footer bar in css, the bottom of the main content is – obviously – partially covered by the footer bar. Is there a way to avoid that?

Thanks and kind regards,

Clemens

**Comment by dziudek** [comment]
The only way is changing the positioning of this footer from fixed to static, but it will need also a lot of additional CSS adjustments which are beyond our support.
