### ISSUE TITLE
Changing and using fonts uploaded

### ISSUE THREAD

**Issue by V1ns** [GavickPro/Music-Free-Responsive-Joomla-Template#39]
I would like to replace BebasNeue with another font, Droid Serif. It is available both in GoogleFonts and FontSquirrel and I uploaded the kit to a new directory in the font folder. So I have two folders, BebasNeue and DroidSerif, each containing their respective files.

When using Squirrel option, I can choose the added font from within the drop-down list of the the template's font option in the backend but it doesn't take effect on the website.

If I link from Google Fonts, my preferred font displays correctly in Chrome but not in Firefox and IE9. So I'd like to just use the Squirrel option. Are there any other files I need to edit for the new font to take effect when I choose it in the Squirrel option in the backend? Which files and where?

**Comment by dziudek** [comment]
Please make sure that the DroidSerif directory contains the stylesheet.css file and if in the CSS rules it uses font-family name as "DroidSerif" not i.e. "DroidSerifRegular".

**Comment by V1ns** [comment]
The DroidSerif stylesheet.css came with the kit. I'll try editing it to what I think you mean. Thanks for your fast response.

**Comment by V1ns** [comment]
It worked for me by renaming the references to DroidSerif-Regular and DroidSerifRegular in the stylesheet to just DroidSerif. I also deleted the other font variants - bold, italic, bold-italic.

So now my stylesheet.css looks like this,

/\* Generated by Font Squirrel (http://www.fontsquirrel.com) on August 29, 2012 10:16:42 PM America/New_York */

@font-face {
    font-family: 'DroidSerif';
    src: url('DroidSerif-webfont.eot');
    src: url('DroidSerif-webfont.eot?#iefix') format('embedded-opentype'),
         url('DroidSerif-webfont.woff') format('woff'),
         url('DroidSerif-webfont.ttf') format('truetype'),
         url('DroidSerif-webfont.svg#DroidSerif') format('svg');
    font-weight: normal;
    font-style: normal;

}

It used to be longer with separate @fontface block for each font variant. My issue is now solved. Thanks a lot.

**Comment by V1ns** [comment]
But what will happen to the new font directory and its contents if the whole template is auto updated to the latest version? How do we keep it intact despite the update?

**Comment by dziudek** [comment]
As I know the files shouldn't be changed - the files should be merged.
