### ISSUE TITLE
template bug : main menu duplication with tablet / mobile view

### ISSUE THREAD

**Issue by ghost** [GavickPro/Music-Free-Responsive-Joomla-Template#4]
i'm not sure of the validity of this report because i don't know too much about the project planning and lifecycle, but...

template bug : main menu duplication for both - expanded menu positions with tablet / mobile view. 

for a better view - please check out attached url : http://imageshack.us/photo/my-images/16/menuexpanded1.jpg/

in my opinion, each module ( menu module ) position is ( or should be ) prescribed for a different menu module ... or not ?

**Comment by dziudek** [comment]
It is a one common element - text "Menu" with the background image at right and currently there is no plan to put the second module menu there.

**Comment by ghost** [comment]
ouch ! heheh sorry ... my "fault" ;) by using two different icons, i was expecting two different actions. lol, i had no idea that it is one module area. so, it is a usability error ;) 

---

tak między nami. przydałoby się repozytorium na git, dla istniejących i nowych modułów w linii gk_5. może nie w zakresie kodowania, chociaż myślę, że sporo ludzi dorzuciłoby pliki lokalizacyjne, ale w zakresie kilku usprawnień. przemyśl to. nie sądzę, aby takie działanie ingerowało w pracę kierownika projektu, a na pewno pozwoliłoby właśnie jemu, selekcjonować bardziej przydatne funkcjonalności.

**Comment by dziudek** [comment]
To check if it is an usability error we need definitely bigger range of users ;)

---

Generalnie koncepcja opublikowania na repozytorium publicznym modułów z linii GK5 jest dyskutowana i w najbliższym czasie zdecydujemy czy to zrobić. Jest sporo mocnych argumentów "za" ale też kilka mocnych "przeciw" ;)

**Comment by ghost** [comment]
sure, you should wait for customers feedback ... if it comes ;) 

---

jasne, to jedynie luźna sugestia. niemniej, trudno jest wam coś sugerować kiedy na gk_wiki nikt nie publikuje moderowanych komentarzy. nie do końca wiem gdzie zgłaszać pomysły, a refaktoryzacja kilku elementów funkcjonalnych i nazwijmy to "dobrych zasad", w niektórych przypadkach, przydałyby się.  nie traktuj tego jako pouczenie, po prostu  ... rozmawiamy :)

**Comment by dziudek** [comment]
Na wiki komentarze są publikowane jeżeli zostaną uznane za przydatne pod wzgledem dodania ich do wcześniejszych/późniejszych ToDo ;) I są sprawdzane względnie często ;)

**Comment by ghost** [comment]
z tym bywa różnie. chociażby korzystając z efektów - przy okazji niczego nie ujmując waszym modułom czy frameworkowi ! mówię to nie jako zwykły użytkownik, ale projektant aplikacji z prawie 15 letnim stażem, ale to rozmowa nie na forum publiczne, bo po co ? 

[...] i mówię to dlatego, że sam z nich korzystam i korzystają moi klienci. tak jest po prostu łatwiej o czym doskonale wiesz. nie mam też na myśli upychania funkcji, a bardziej ... lepszą organizację tych dodatków czy też szablonów.

**Comment by ghost** [comment]
przy okazji wczorajszego spotkania ze znajomymi, zaznaczam, że są to zwykli użytkownicy stron internetowych nie zaś administratorzy - w oparciu o opinię których chciałbyś skonfrontować użyteczność tego rozwiązania. 

próba nie była wysoka, 7 osób, kobiety i mężczyźni, wiek 33 - 42 lata, wykształcenie wyższe, na co dzień korzystający z sieci, entuzjaści e zakupów. 

efekt, potwierdza moje spostrzeżenia. pod stylem, który nazwałeś "tłem" szukano skrótów do kategorii sklepu. ( ja zwyczajnie zamieniłem w quickstart kategorię, lokalizując je w menu sklep).

wiem, że to marginalne badanie i nie tak globalne jak myślicie o tym szablonie, ale daje do myślenia ... i teraz zmuś administratora, żeby przedstawił ci pełen raport z podobnego działania jak to, nic nie znaczące moje, albo do tego, żeby tworzył układ chociażby w oparciu o te znaczniki, które w widoku mobilnym, tworzą wspólnie z odnośnikami społecznościowymi, kolejny blok i ... w pewnym momencie zwykły użytkownik, odwiedzający waszą stronę demo, zaczyna "macać" ją w nerwach gdzie popadnie, nie wyłączając tego całego bloku, należącego do menu głównego. 

taki właśnie krótki wniosek. uważasz, że może być zasadny ?

**Comment by dziudek** [comment]
Osobiście przyznam, że pod wpływem naszej dyskusji tutaj zacząłem się zastanawiać nad innym rozwiązaniem:

zamiast tworzyć dwa obszary aktywujące dwa różne menu, zauważyłem, że w prosty sposób można zmniejszyć nagłówek strony w wersji mobilnej: 
- przyciski rejestracji/logowania zamieniamy w ikony
- obecną belkę z menu zupełnie usuwamy
- ikonkę będącą obecnie tłem belki z menu przesuwamy do góry do prawego narożnika i przypisujemy jej działanie przycisku od menu głównego strony.

Dzięki temu opisany w tym wątku problem znika, a przy okazji nagłówek strony jest dużo efektywniej wykorzystany w trybie mobilnym.

**Comment by ghost** [comment]
dokładnie, mało tego ! w samym nagłówku, w widoku mobilnym masz możliwość umieścić pozostałe funkcje, które tutaj nazwaliśmy roboczo "front-end toolbar", tym bardziej, że każda z nich jest rozwijana. co o tym sądzisz ?

**Comment by dziudek** [comment]
Tak, dokładnie o tym samym pomyślałem :)
