### ISSUE TITLE
masonry sufix jeden i pół

### ISSUE THREAD

**Issue by ghost** [GavickPro/Music-Free-Responsive-Joomla-Template#40]
kiedy patrzę na ten obrazek 

http://demo.gavick.com/free/may2012/images/demo/Moomasonry1.png

wydaje się to możliwe ( element 08 ), jednak w szablonie dostępne są jedynie : pół, jeden, dwa, trzy i cztery.

**Comment by bkrztuk** [comment]
Grafika przedstawia ogólną ideę działania skryptu moomasonry (<i>The following image compares the traditional layout with float with the layout generated by MooMasonry</i>). Dostępnie suffixy wymienione są niżej :

half
one
double
triple
fourfold
