### ISSUE TITLE
Missing Color/style III language string

### ISSUE THREAD

**Issue by NormanUK** [GavickPro/Music-Free-Responsive-Joomla-Template#43]
We need to add third color/style option language string as it is missing in "en-GB.tpl_gk_music_free.ini".

TPL_GK_LANG_COLOR_3="Style III"

**Comment by bkrztuk** [comment]
Fixed https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/commit/b855d044e5da5cfb871764925ed4738ac7d110e5
