### ISSUE TITLE
zmiana wielkości czcionek

### ISSUE THREAD

**Issue by ghost** [GavickPro/Music-Free-Responsive-Joomla-Template#44]
parametr " włączony na wybranych stronach " - odnosi sie do wyłączenia i na odwrót - wyłączenie, aktywuje go.

**Comment by dziudek** [comment]
Właśnie sprawdziłem tą opcję i z tego co widzę wszystko działa poprawnie - w quickstarcie Font-size switcher jest wyłączony na stronie głównej i stronach komponentu K2 - co jest zgodne z ustawieniami w panelu - "Disabled on selected pages" i com_k2 oraz itemID 101 jako strony gdzie ma być wyłączony.

**Comment by ghost** [comment]
hmmm, ja nigdy nie buduję projektu z quick-start'a. być może szablon + dodatki instalowane od podstaw coś mutują ;). zrobię drugą instalację i powiem czy problem się powtarza, ale pewnie w okolicy jutra.
