### ISSUE TITLE
Some errors occurred while populating the database: No database schema exists for this database type

### ISSUE THREAD

**Issue by mikimonmikimon** [GavickPro/Music-Free-Responsive-Joomla-Template#45]
In step 4 of the installation i get this message:

Some errors occurred while populating the database: No database schema exists for this database type

any idea???

thanks''''¡¡¡¡¡¡

**Comment by dziudek** [comment]
Hi,

Which database driver did you selected for the install?

**Comment by mikimonmikimon** [comment]
hi¡¡¡¡ 

mysql

**Comment by dziudek** [comment]
Did you tried to install with mysqli? If it will also fail, please try to reupload the quickstart files, because probably some SQL files was uploaded wrongly.

**Comment by mikimonmikimon** [comment]
i've tried with mysqli, then i've reupload the quickstart files and the same error. I´ve installed it in my computer just to try and everything is ok, but when i upload the quickstart files and try to make the process in the host that i have i get that message, it's very strange and frustrating.

My host server is freehostia.com

**Comment by bkrztuk** [comment]
@mikimonmikimon  please check your database max packet length, in short words the maximum size of query. If everything is working fine on localhost it is surely hosting issue.

**Comment by mikimonmikimon** [comment]
There's no other posible reason, i'm trying to contact my webhost, thanks a lot for the answers¡¡¡
