### ISSUE TITLE
how to show Category description on content page.

### ISSUE THREAD

**Issue by kdji123** [GavickPro/Music-Free-Responsive-Joomla-Template#46]
I dont know if its right to ask this question here.
but it`s really important for me to show the description of the current category in all the articles.
presently if show parameter is selected in the category menu than it is visible on the category blog layout page but not on the article page.

The reason is that  there is no code to call this description in 
{ \templates\gk_music_free\html\com_content\article\default.php}

as I dont have any programing skills so I dont know what to put in.

Please Help,

Regards
thank You

**Comment by NormanUK** [comment]
You can add below php code in where you want to display category description. See below link.
http://pastebin.com/Esq2sBTR

use below class to style your element.

<pre>
.categorydesc { }
</pre>

See you around...
