### ISSUE TITLE
Social location not floating right

### ISSUE THREAD

**Issue by tlovering** [GavickPro/Music-Free-Responsive-Joomla-Template#47]
From looking at your module diagram (http://bit.ly/OvhvFI) it looks as though the Social position should float right, but when I place a module in there it aligns left, and crashes in to my Toolbar menu (www.portlandrfc.com).

Please let me know what I'm doing wrong. Thanks!

**Comment by dziudek** [comment]
Hi,

You have to add the " social" suffix (with the space at the beginning) for this social icons module - it should helps.

**Comment by tlovering** [comment]
Perfect! Thank you.
