### ISSUE TITLE
Error 404 in mainmenu

### ISSUE THREAD

**Issue by mikimonmikimon** [GavickPro/Music-Free-Responsive-Joomla-Template#48]
I've installed the template, but now i get error 404 when i link articles in mainmenu, any idea?

thanks¡¡¡

**Comment by dziudek** [comment]
Hi,

If you have enabled the SEF urls, please check if the htaccess.txt file was renamed to .htaccess

**Comment by tukoz** [comment]
Hi, we encouter the same issue on whatever is _category_ related (blog, list etc), on a test site (Joomla 2.5.7, Vm 2.0.10, GK Music free 3.5) that we're finishing soon.
Of course tried with disabled SEF, checked the DB, rebuilt menus... but couldn't solve the issue atm.
Might as well be a misconfiguration somewhere.

BTW many many thanks for the template it is fun to work with + appreciated by testers till now :)

**Comment by dziudek** [comment]
@lliseil could you provide me an URL to your website?

**Comment by tukoz** [comment]
@dziudek sorry for answering late.

URL is http://guixmodel.net/
The menu item that errors is the eight one "_Le blog_", along with its sub-menu, and same entry in the (en cours) footer menu.

**Comment by dziudek** [comment]
@lliseil - something must be messed up in your settings - as you can see the 404 error is displayed on the totally differen theme etc. There is no way that due the template the urls won't work.
