### ISSUE TITLE
idea : print friendly & pdf button

### ISSUE THREAD

**Issue by ghost** [GavickPro/Music-Free-Responsive-Joomla-Template#5]
replacing native joomla's print and 'print to pdf' plugin.

source : http://www.printfriendly.com/

**Comment by bkrztuk** [comment]
I've compared the printfriendly version to our overrided layout and don't see many differences. In some cases default layout is much better and cleaner this printfiriendly version. In addition scripts weights 10 KB and need to be load on every page. 
@dziudek  what do you think about this ? 
@partizanpl  could you tell me where do you see 'print to pdf' icon on any Joomla version higher that 1.6 ? It is removed from CMS, since Joomla 1.6.

**Comment by ghost** [comment]
@bkrztuk the difference you'll find in the options of printed content. with 'print frindly' you can incl. / excl. - necessary / unnecessary content. 

if you compared both, print me the same with joomla! ... of course using the same method of choice ... and of course print me to pdf.

---

ad.2 próbujesz szukać dziury w całym ? zupełnie nie potrzebnie.

**Comment by bkrztuk** [comment]
In my humble opinion there is no way to use printmefriendly with Joomla. Why ? Becuase of lot of content in modules, I've opened first page of template and test it with printmefriendly, please just check what you get if you try to print this page >> http://demo.gavick.com/free/may2012/index.php/template/lorem-ipsum/template-articles/module-variations

All modules content without an article ... in Joomla default print page there is always way to customize view in print.php page. Maybe there is some better tools to make this. I've checked printmefirendly options but don't see nowhere any options to customize this script for selected CSS selectors etc.

**Comment by dziudek** [comment]
In general I see much bigger problem than the ones mentioned in this discussion: http://www.printfriendly.com/pro ;)

**Comment by bkrztuk** [comment]
I think that the price and the script results make this idea totally unacceptable in our templates :)

**Comment by dziudek** [comment]
@partizanpl - to be clear - we want to add only these features which are free. It is not good when user discover that some of the nice features included in the template needs a fee (even if it is small fee).

**Comment by ghost** [comment]
ok guy's, your choice. it was only a suggestion / idea. and this is true @dziudek - you should invite more template users to the github ... definitely :)

**Comment by dziudek** [comment]
@partizanpl - yes, definitely :) I'll make a few things to get more users here soon :)

**Comment by ghost** [comment]
sure. e.g built-in [ template panel ] rss reader for this specific channel ... of course with the possibility to enable or disable it ... somewhere in the code ;)
