### ISSUE TITLE
Pagination Issue

### ISSUE THREAD

**Issue by studio204** [GavickPro/Music-Free-Responsive-Joomla-Template#51]
Pagination shows incorrect after the page 7. You can see it even in demo after changing blog layout options to show 1 article per page, there will be 11 pages. After the page 7 it shows back and forward navigation, but not page numbers.

**Comment by dziudek** [comment]
Hi,

Could you check your page with this commit: https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/commit/49fa7c6d9be7db5957b01dfe150aaf67296308e2

It seems that now Joomla! stores max. 10 pages in the:

``` php
$list['pages']
```

what causes the problem - could you verify if on the bigger amount of pages it is true - that Joomla! stores max. 10 pages in the mentioned array? If it stores only 10 pages then you should see in the pagination always max. 10 pages using the updated pagination.php file.

**Comment by dziudek** [comment]
Solved: https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/commit/a767217f469ad4e19b282ab0b2c882c0034dd904
