### ISSUE TITLE
Pictures blur in IE9/Mozilla/Chrome (perfect in IE8)

### ISSUE THREAD

**Issue by dpower717** [GavickPro/Music-Free-Responsive-Joomla-Template#52]
If an K2 item contains in image, the preset image size does not work and image becomes blurry.
The images in the sidebar works smooth.

Position : Mainbody
Item published / not featured

**Comment by dziudek** [comment]
Hi,

The images are scaled up to 100% of the container width always in this responsive layout. If you really need - you can increase the thumbnail size to avoid this effect.

**Comment by dpower717** [comment]
Hi,

So the options in the backoffice for image size does not have any effect ?
Because when i choose small/medium/large/ image size in IE8 the size changes correctly.
However in IE9 it doesnt workt at all.

(is there any way to upload screenshots?)

**Comment by dziudek** [comment]
Maybe on IE9 you see the cached version? Because if the image is sized to the other size in IE8 then it means that it is changed in the page structure what should works also for other browsers.

**Comment by dpower717** [comment]
Just re-checked and that is not the issue. (check if new page exist every time a visit the website)
Strange thing is that it also works good in IE10 (beta).

I think it blur because of the setting (image size medium = 200x200PX), IE8 handles the setting correct but the other browser don't understand stretch out the picture from 200x200 to a full 100% image.

**Comment by dziudek** [comment]
As I remember IE8 have disabled the:

``` css
max-width: 100%;
```

CSS fragment, because it cause that images disappears in IE8.
