### ISSUE TITLE
Weird behaviour when Tabs GK5 activated

### ISSUE THREAD

**Issue by tukoz** [GavickPro/Music-Free-Responsive-Joomla-Template#53]
Hi, we're having a weird behaviour in a gk music free web site when Tabs GK5 activated.

It happened once in September after updating Joomla to 2.5.7. Updating the template solved this issue.
Happened once again a few days ago, while what we did was limited to editing a few modules (no updates)
Happened on both the production host and on the local LAMP server.

Versions:
- gk_music_free Template 3.5 (20 Sep 2012)
- mod_news_pro_gk4 3.3.1
- Tabs GK5 1.2 

Activating Tabs GK5 alters the markup code (1), renders the whole page unusable:
- screenshot: tabs gk5 should be located in Main_bottom, and other modules in Sidebar position. http://imm.io/GGF5
- screenshot: same page without Tabs gk5: all is fine. http://imm.io/GGG3

What we've done so far without it changes the issue:
- Updated: GK Music Free template, Tabs GK5 (and NSP GK4)
- Changed the position: same issue, even with the Tabs GK5 in the breadcrumbs ;)
- Played a bit with GK Music free template options, 
  e.g. deactivating Mootools library on pages where the module shows up side down, didn't change.
- Disabled any css override that we've done
- Disabled about every other single plugin,
- Uploaded a newly donwloaded-dezipped Joomla 2.5.7

An admin access to the website is feasible.

Please forgive us if this post is unrelated in this place, and instruct us where to post.

(1) Markup:

Normal page:

``` html
<!DOCTYPE html>
<html lang="fr-fr">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0">
...SNIP SNIP...
});
     // ]]>
     </script>
<!-- End Cookie Consent plugin -->
</head>
<body data-tablet-width="760" data-mobile-width="480" data-blocks-animation="1" data-content-width="3" data-loading-translation="Loading">
<div id="gkPageWrap">
    <section id="gkPageTop">

          <a href="./" id="gkLogo">
...SNIP SNIP...
```

Same page with Tabs GK5 activated:

``` html
<div id="gk-tabs-118" class="gkTabsGK5" data-config="{'activator':'click','animation':'0','animation_speed':'1000','animation_interval':'10000','animation_type':'slide_horizontal','animation_function':'Fx.Transitions.linear','active_tab':1,'cookie_save':'0','auto_height':'1','module_height':'200'}">
    <div class="gkTabsWrap vertical">
                <ol class="gkTabsNav">
                          ...SNIP SNIP...                           
        <div class="gkTabsContainer">

<div class="gkTabsItem active">
    <!DOCTYPE html>
<html lang="fr-fr">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0">
    ...SNIP SNIP...
    // ]]>
     </script>
<!-- End Cookie Consent plugin -->
</head>
<body data-tablet-width="760" data-mobile-width="480" data-blocks-animation="1" data-content-width="3" data-loading-translation="Loading">
<div id="gkPageWrap">
    <section id="gkPageTop">

          <a href="./" id="gkLogo">
```

**Comment by dziudek** [comment]
First of all please check if it depends from the Tabs module content. i.e. If the Tabs module contains the text only, the problem appears?

**Comment by tukoz** [comment]
'morning dziudek
That's interesting:

GK Music free, Tabs GK5: Problem disapears when:
- tabs: xhtml
- tabs: VirtueMart {Featured,Random,Best_sales} product module, and no category filter

Problem comes when:
- tabs: VirtueMart _Last products_ module 
- tabs: VirtueMart any product module WITH Category filter
  Which tells why the issue appeared as soon as we configured Tabs GK5 modules to show LAST products or those from specific categories (both needed features).

I'll now test with another template, now that you allowed us to narrow the issue.

EDITed to add Last products as a causing the issue as well as making use of Vm category filter.

**Comment by dziudek** [comment]
Probably these modules cause some structure errors i.e. contains som unclosed tags or uses some operations on the page buffer what cause the problem. The best solution - don't use it in the tabs module to avoid these problems.

**Comment by ramchos** [comment]
Hi,
I've the same problem and noticed that this type of behaviour occurs on Virtuemart Featured products module where there are no featured products selected. Can this be fixed writing something like "There are no featured products at the moment" text if the list of featured products is empty?

**Comment by dziudek** [comment]
Sorry but Virtumart Featured Product isn't our module - please ask their developers.

**Comment by ramchos** [comment]
This behavior occurs when the module is empty. Here is the solution i've used for myself and it works.
Add in helper.php after line 107 for($i = 0; $i < count($this->config['tabs_data']); $i++) {
These lines
if (JModuleHelper::renderModule(array_shift(JModuleHelper::getModules($this->config['tabs_data'][$i]->content) ) ) == "" ){
                $tabEmpty = true;
            }
            else {
                $tabEmpty = false;
            }
            if($this->config['tabs_data'][$i]->published == 1 && ($this->checkAccess($this->config['tabs_data'][$i]->access, $access)) && !$tabEmpty) {

The tab will appear only if it has contents.
