### ISSUE TITLE
How can I deactivate the next-button for jumping to another articel?

### ISSUE THREAD

**Issue by YesYesYo** [GavickPro/Music-Free-Responsive-Joomla-Template#54]
I would like to deactivate the next-button in the articels in the music free template from GavrickPro.
I Think the solution will be really easy but currently I don`t find the solution by oneself .

Thanks for help.

**Comment by dziudek** [comment]
Hi,

Please disable the pagination plugin ;)

**Comment by YesYesYo** [comment]
Wow, thats fast :)
Okay i will try it

**Comment by YesYesYo** [comment]
thanks! it works :)
