### ISSUE TITLE
How can I deactivate the mainbody on individual sites? (Template music free)

### ISSUE THREAD

**Issue by YesYesYo** [GavickPro/Music-Free-Responsive-Joomla-Template#56]
Hey Ho,

is it possibel to deactivate the mainbody on individual sites? I would like to have on selected sites only modules. Is there a feature for this in the template music free or is it necessary to change the code?

**Comment by bkrztuk** [comment]
The easiest ways is to use 'Suffix for pages' feature and create some suffix like <code>noMainbody</code> where you hide mainbody on CSS. Then suffix you can set to menu items/components.
