### ISSUE TITLE
How to change the margins between category listed items

### ISSUE THREAD

**Issue by dpower717** [GavickPro/Music-Free-Responsive-Joomla-Template#57]
Hi,

How to increase the margins in a two colums subcategory like :

http://demo.gavick.com/free/may2012/index.php/k2-tags/2011-08-04-23-47-02/latest-items-two-columns

I have a problem that the text is almost near the second column.

**Comment by dziudek** [comment]
Hi,

Where do you have this problem? On K2 or in the com_content component?

**Comment by dpower717** [comment]
Hi,

The issue is on K2.

**Comment by dziudek** [comment]
If it is K2 then you should have the same spaces as in the demo - could you provide an URL to your website?

**Comment by dziudek** [comment]
Now I see a reason of your problem due your e-mail - the spaces are available currently only on the latest items view. I'll work with it to fix it in the next version also for the non-latest item view.

**Comment by Jartsan** [comment]
I have same problem and need urgent help for it. Here example page: http://checkfinland.ru/index.php/shopping/k2-tags/shops/departmentstores

It should same as in this demo: http://demo.gavick.com/free/may2012/index.php/k2-tags/2011-08-04-23-47-02/latest-items-two-columns

Also title font size.

Thanx, Jari

**Comment by trixden** [comment]
Why in the sample output everything correctly, and we can not do it again? What is our problem? dziudek passed 5 months. We expect an update? I know the code. Tell me though, would that have changed?

I apologize. Google Translator
