### ISSUE TITLE
Login with Facebook issue

### ISSUE THREAD

**Issue by nico25** [GavickPro/Music-Free-Responsive-Joomla-Template#61]
Resently i download  this template with de Quickstart  package... All seems to be well but i can´t  make the login whit facebook works... I configure my app  in facebook and it seems to be fine whit that, but de log in with facebook not do anything.. Please i need some help.... Thanks in advance

**Comment by bkrztuk** [comment]
Please check your configuration with this tutorial, surely something is missing <code>https://www.gavick.com/documentation/joomla-templates/templates-for-joomla-1-6/how-to-implement-the-login-with-facebook-feature/</code>

If the problem come back after checking all steps please let us know.

**Comment by nico25** [comment]
hello, I check all the steps in the tutorial and nothing happened i do not really know what is the problem please help me ... Thanks in advance!

**Comment by bkrztuk** [comment]
@nico25 please provide URL to your site.

**Comment by nico25** [comment]
http://zonaestereo.com.ar/sitio/

**Comment by nico25** [comment]
Let me know if you need something else

**Comment by bkrztuk** [comment]
In firebug console I get information from fb script that your applicaiton type don't allow to use login feature. Are you sure that you app type is set to "Login with facebook" ?

**Comment by nico25** [comment]
Yes is set to "login with facebook"...

**Comment by bkrztuk** [comment]
So the keys are wrongly copy/paste to template plugin settings. Can I see the screnshot from APP configuration page (in facebook) ?

**Comment by nico25** [comment]
yes of course let me do it

**Comment by nico25** [comment]
you can see it here http://zonaestereo.com.ar/facebook.jpg... thanks

**Comment by bkrztuk** [comment]
<pre>In the field, “App Domains”, type out the root of your domain, such as: “www.gavickmagazine.com”</pre>

Please configure URL to root of your site so http://zonaestereo.com.ar

**Comment by nico25** [comment]
I allready do that but when i save it i got this error 

Error
App Domains: http://zonaestereo.com.ar should not contain protocol information.

**Comment by bkrztuk** [comment]
You don't have any other fb application configured for this domain ? Please remove all the previous ones and leave only this with root URL as a domain.

**Comment by nico25** [comment]
http://zonaestereo.com.ar/sitio/ have a clean joomla instalation... I have other domains in my server but i working with other facebook app

**Comment by bkrztuk** [comment]
So this is causing problems, there are few applications on one domain which is not allowed by facebook. www.domain.com/folder is not a domain it is subdomain.

**Comment by nico25** [comment]
Ok i will erase the instalation in my domain and i will come back with the results (sorry for my bad english)

**Comment by nico25** [comment]
Hi bkrztuk i made a clean instalation in my domain, i put the codes for my facebook app and it work. Also change my Facebook App permissions:

Default Activity Privacy: Only Me

Auth Token Parameter: URI Frafment

I hope this post helps to other rookies like me ... Many thanks from Argentina!!

**Comment by N1ckfm** [comment]
I knew the answer, I don't know if it is usefull for somebody, when you put your domain try to not put http:// or www. only:  forexample.com   and "configuration" enable: "Client OAuth Login " and in "configuration" add plataform and select web site and put your website with http://forexample.com/home/index.php    and It will be work!   for mi works fine :) so I hope that it can help to others

**Comment by iosoft** [comment]
Thanks N1ckfm. Atleast someone replied.

Anyway, I am using SLogin ext for Joomla now. It has many types of Social login support WITHOUT any Bug.
