### ISSUE TITLE
"Error 404/Error link" after clicked logo

### ISSUE THREAD

**Issue by ivanwongtf** [GavickPro/Music-Free-Responsive-Joomla-Template#62]
HI,

I encountered a problem about a logo in my website.
The problem occurs after I entered a article. When I clicked the logo at the upper left corner, it is linking to a 404 error page instead of my home page. I don't know whether it is a bug or it is my falult.
For example,
when I entered a article 'http://www.justdoevil.info/index.php/technology/androidprog/item/200-android-periodic-table-merck-pte-hd'
When I click the logo, it will go to 'http://www.justdoevil.info/index.php/relax/googledoodle/item/'.
but there is no this page, so that it will get a error 404.

So I want it to turn to my home page when I click the logo.
Sorry for my poor English, hopefully you can understand and help me.

**Comment by ivanwongtf** [comment]
The problem still exist,can anybody help me?

**Comment by dziudek** [comment]
I'm sorry I forgot to close this issue with link to this commit: https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/commit/18836cd8182e0e891497c3ea650f771e271cf083
