### ISSUE TITLE
hover animation cannot be disabled

### ISSUE THREAD

**Issue by dpower717** [GavickPro/Music-Free-Responsive-Joomla-Template#64]
When i turn off the hover animation it still works on the website no matter if it is turned on or off.
On IE8 it works fine.

**Comment by dziudek** [comment]
Hi,

Where did you disabled the hover animation? I don't see options like this in the template settings. There is only an option to disable the blocks animation, but it is connected with animation on the window resize.

**Comment by dpower717** [comment]
aah i understand now, so than i must edit the css style and set de degree value to 0.

**Comment by dziudek** [comment]
Exactly ;)
