### ISSUE TITLE
Fixed menu

### ISSUE THREAD

**Issue by mauricelogic** [GavickPro/Music-Free-Responsive-Joomla-Template#66]
I love this template. Is there a quick way to fix the menu to the top when users scroll? Thanks.

**Comment by dziudek** [comment]
Hi,

I don't recommend the fixed menu for responsive templates, because on the mobile devices the:

``` css
position: fixed;
```

causes a lot of problems.

**Comment by mauricelogic** [comment]
Okay cool. Thanks.
