### ISSUE TITLE
Facebook box problem

### ISSUE THREAD

**Issue by studio204** [GavickPro/Music-Free-Responsive-Joomla-Template#67]
There is a problem with Facebook buttons. When I click Like or Send, a box should appear with text area and send or cancel buttons. But the box appears partially only, so the Send and Cancel buttons are not visible.
Please take a look at http://demo.gavick.com/index.php?month=May&year=2012&type=free and try to click any Facebook button.

I have 2 sites using this template (it's really great!), and both have this problem.

**Comment by dziudek** [comment]
Hi,

Please apply fix from this commit: https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/commit/15fbe5b617ed4d05c95bd04e6af0235315fcf3f9

**Comment by studio204** [comment]
Yes, I tryed. I replaced Layout.css with new one. Unfortunately, no effect both with my site and with quick start demo. When I click Send button, only part of the FB box is visible.

**Comment by dziudek** [comment]
Please provide me an URL to your website, because without it I won't be able to help. On the demo there is an old version, because we are updating the files in the specific time periods.

**Comment by studio204** [comment]
Please take a look here
http://improvisers.ru/sudnik
and here:
http://kinoart.ru/blogs/pro-to-chto-ostalos-ot-razuma
(at kinoart.ru I had to change margin in joomla.css to 235px as temporary solution, but it is not good idea)

**Comment by dziudek** [comment]
Sorry but it seems that you haven't replaced the layout.css file properly - I still see the:

``` css
#gkContent {
    overflow: hidden;
}
```

on your code.

**Comment by seanoregan** [comment]
Hi,

First of all thanks for the template, it's gone down really well with the members of our choir. Did this issue get resolved because we still have the same problem even after applying the fix. Please see http://www.singinginthecity.co.uk/

Thanks,
Sean
