### ISSUE TITLE
Music Free gkFooter non sticky in google chrome

### ISSUE THREAD

**Issue by funkygee** [GavickPro/Music-Free-Responsive-Joomla-Template#69]
![shot_147](https://f.cloud.github.com/assets/446817/7115/f09e97d6-43e9-11e2-80ec-e8a113164ae2.jpg)
I discovered this issue that the gkFooter div does not sticks to the bottom of the page, only in google chrome. It flows randomly upwards as the user scrolls up and down. I found that this happens only in google chrome on pages where I use the supersized background slideshow for joomla. 
Thanks. Keep up this great project!

**Comment by bkrztuk** [comment]
Could you show some screenshot with this problem ? Did you notice this problem in our demo server ?

**Comment by funkygee** [comment]
I attached an image. This time just "blinked", so was not visible continously, but sometimes strikes thru the screen, flows up, only in chrome, and only on pages where the fun supersized for joomla exist. The other pages working like a charm with no problems. On the right side down you can see the color style selectors, those are still remain at the right place. When you scroll the mouse, it blinks or flows up then down. I think it should be some interference with the script? Or between them. I use also Jqueryeasy for Joomla for tweaking the scripting policy. The template is centered, all modification were made only in the template backend. I'm testing it on my localhost and find it very robust except these small issues. ( Not my first issue with G.Chrome mouse scrolling, previously I could not zoom in-out a flash in google chrome, but this is not related to this template, just a remark.) 
Thanks is advance.

**Comment by bkrztuk** [comment]
In my opinion this problems comes from 3rd party extensions or your customization issue. I've checked our template on demo.gavick.com and I don't see this behavior.
