### ISSUE TITLE
Problems installing gk_music_free_J!25

### ISSUE THREAD

**Issue by bernatcatala** [GavickPro/Music-Free-Responsive-Joomla-Template#70]
I have problems installing the gk_music_free_J!25 template in a joomla 2.5

I can't install the packs gk_music_free_quickstart_J!25 and gk_music_free_rest_files_J!25 (can't find the xml configuration file)

**Comment by bkrztuk** [comment]
rest_files package need to be firstly unzipped and there you can find plugins/modules for template. The quickstart package contains Joomla!, template and all extensions and <b>can't</b> installed via extension manager. If you look here you will find all informations :  
http://www.gavick.com/documentation/general-questions/quickstart-or-templates-installation/
http://www.gavick.com/documentation/joomla-templates/templates-for-joomla-1-6/quickstart-installation-for-joomla-1-6/

**Comment by bernatcatala** [comment]
thanks
