### ISSUE TITLE
Responsive images only work in Google Chrome, not Firefox or IE9

### ISSUE THREAD

**Issue by karusellimedia** [GavickPro/Music-Free-Responsive-Joomla-Template#71]
Hi, 

I've been testing Music Free template and noticed that only Google Chrome can resize images on fly, Firefox or IE9 does not do that. 

Check this out: http://www.viikonvinkit.fi/area51 (do not wonder to any other pages, template is working on that page only)

I tried frontpage blog (now in use) and RAXO modules, same result. Am I missing something? 

Regards,

Jukka M.

**Comment by bkrztuk** [comment]
I've checked your page on latest Chrome browser and don't see any problem - could you mark this wrong image on this screenshot ? http://d.pr/i/QVHt

**Comment by karusellimedia** [comment]
The problem is not with Chrome, it is with Firefox and IE. The image is in third article in the blog, the one that has shoes and boxes with numbers.

**Comment by bkrztuk** [comment]
In my opinion the problem is somewhere in your article/code because w3c valide service shows missing nav element, please just check http://validator.w3.org/check?uri=http%3A%2F%2Fwww.viikonvinkit.fi%2Farea51&charset=%28detect+automatically%29&doctype=Inline&group=0

In addition, the problem not exist on our demo server http://demo.gavick.com/free/may2012/index.php/template/lorem-ipsum/articles/category-blog

**Comment by karusellimedia** [comment]
Now I created a clean article and noticed the picture is cropped not resized with Firefox or IE. Also got a few errors with validator that could relate to problem with mozilla. Please check again.

**Comment by bkrztuk** [comment]
Your editor is adding widht & height values to image but without 'px'  part or you specify wrongly dimensions when you add image (the best it to leave widht/height area blank). Please add this code to override.css 

<pre><code>
section img { width: 100% }</code></pre>

and enable override css option in template advanced settings - this should fix your problem.

**Comment by karusellimedia** [comment]
Excellent, thanks! Now it works great. I'm using JCE-editor, it might need some tuning...
