### ISSUE TITLE
Two Questions: Social API and Realigning Images with K2

### ISSUE THREAD

**Issue by MikeEy** [GavickPro/Music-Free-Responsive-Joomla-Template#72]
First Question: I clicked the Pinterest button and Tweet button to OFF under Social API in Admin of Template, BUT it still shows up under articles. However the others such as Google +1 do disappear if I have them set to OFF. Is this a bug/kink? 

Is there a way I can remove the code from a file to make them disappear, if so, what file do I go in and what code should I remove. I do not want these to show up at all!

---

Second Question: I forgot how to make an image float to the right or left of the article. I also want it underneath the title. Right now, my image is Fully Blown up to the max and above the title and article. 

Do I have to do a template override? I forgot how to do that. 

I hope someone will please help me out with these two questions. I want to open up my site before Jan 1st.

Thanks in advance!

**Comment by bkrztuk** [comment]
Is your template up to date ? I've disabled Pinterest and Twitter in Social API area and it is working properly - I don't see buttons in article content (http://d.pr/i/X2iY)

Second issue - you need to make proper changes in override.css file (template/css) directory and then enable option "Use override CSS" in template advanced settings tab. To move image below title you need to modify K2 article view not only use CSS. Proper file you will find in template/html/com_k2 directory.

**Comment by MikeEy** [comment]
Wow, thanks for the fast response back, along with taking the time to help! When I go under the Template Manager: Edit Style and click the Updates Menu at the bottom right, it checks to see if there are any new updates and then says: "Your Template is up to date"  I guess this is the version: Gavern v.3.5 

I will google for instructions of how to do the template override. I tried it a year ago but have a short memory! :)

**Comment by MikeEy** [comment]
I did everything correct with the override, etc. and it's working perfectly! 

Thanks again!!
