### ISSUE TITLE
quickstart gk_music_free_j30 hangs

### ISSUE THREAD

**Issue by comnfo** [GavickPro/Music-Free-Responsive-Joomla-Template#73]
hi,

i am trying to install the quickstart package for gk_music_free_j30 but it just hangs but creating database tables bar keeps moving but nothing else happens. i checked the database file and it did create a database almost 7mb but the installation did not complete. permissions set to 755 and 644.

i have successfully install joomla 3.02 and music_free template separately on same server with no issues or errors. apache 2.4 php 5.4 mysql 5.5.

please advise.

thanks.

![joomlaerror](https://f.cloud.github.com/assets/3145930/34974/f20b3bb8-516a-11e2-83cc-7b0dd8ce59ba.png)

**Comment by bkrztuk** [comment]
I'm uprading my local server to check package on similar configuration - I'll let you know about results. Do you have any other server to test ? Did you try to re-download package ?

**Comment by bkrztuk** [comment]
For me the latest qucikstart package installing without any problems. Here is my PHP version http://d.pr/i/Jf1d . Please try re-download package and install again.
