### ISSUE TITLE
Music free template with different BASIC SETTINGS

### ISSUE THREAD

**Issue by isb05m** [GavickPro/Music-Free-Responsive-Joomla-Template#74]
Hello,
 I need to know why in my  Music free template  there isn't setting in Template Manager  to turn off the "Show mainbody on frontpage" setting. 

![Music Free](https://f.cloud.github.com/assets/3273536/67251/1c0b85ac-5ef5-11e2-90e5-6eb0158eb109.jpg)

![mainbody](https://f.cloud.github.com/assets/3273536/67252/1c2fc7aa-5ef5-11e2-9b98-0fdcb4883e61.JPG)

**Comment by dziudek** [comment]
Hi,

This option is not necessary, because since Gavern 3.0 the mainbody module position is used only when module appears on the frontpage mainbody.
