### ISSUE TITLE
Item Links does not work - Music-Free-Responsive-Joomla-Template

### ISSUE THREAD

**Issue by kathuk** [GavickPro/Music-Free-Responsive-Joomla-Template#75]
I would need a small help on this package.

I have installed this Joomla gk_music_free_quick start_J!30. 
There was no errors in the process. But item link does not show correct page. In the version 3.00 it shows a dummy page without any css styles.

In version 2.5 it shows 404 error.
I have enabled http rewrite and it didn't help.

Is there anything I need to configure in Joomla?

**Comment by bkrztuk** [comment]
Could you show me example page with problem ?

**Comment by kathuk** [comment]
All the pages which links to K2 itesm have this proble
If I click on sub links in main page. it try to navigate to the url like below. It's different in version 2.5 and 3.0

2.5:
404 error

3.0
This show a plain html page without any css style.

**Comment by bkrztuk** [comment]
Did you try to reinstall K2 extension ? The problem occurr also with Joomla! content ?

**Comment by kathuk** [comment]
Thanks for the quick response.

No I didn't try. Do you think I need to download latest K2 with all the fixes?

**Comment by kathuk** [comment]
NO the problem only for K2 items. Joomla articles working fine.

**Comment by kathuk** [comment]
I have installed latest K2 components now. Problem still there.

**Comment by kathuk** [comment]
I can see below difference in my demo site compare to  gavick demo site URLs. There is additional folder in the path "k2-tags". 

http://demo.gavick.com/free/may2012/index.php/k2-tags/2011-08-04-23-47-02/categories/item/82-nickelback-take-the-road-less-traveled

http://abc.com/index.php/2012-11-12-16-08-25/categories/item/1-nickelback-take-the-road-less-traveled

Not sure this is because the way the items are configured in the K2.

**Comment by bkrztuk** [comment]
Please disable SEF URL's. What is your PHP version ?

**Comment by kathuk** [comment]
Great! Disabling SEF fixed the issue.
My PHP version is 5.3.6

Working SEO settings now.

Search Engine Friendly URLs - No
Use URL rewriting - YES
Adds Suffix to URL - YES
Unicode Aliases - YES

Is this recommended or workaround for this particular problem?
Thanks for quickly responses and fix the issue!

**Comment by bkrztuk** [comment]
This is more Joomla!/server issue than our template - please try with clean Joomla! from joomla.org and if the problem with K2 come back please contact with your hosting company.

**Comment by kathuk** [comment]
Thanks for the help.
