### ISSUE TITLE
Invalid token after successful registration

### ISSUE THREAD

**Issue by borogul** [GavickPro/Music-Free-Responsive-Joomla-Template#76]
Hello, I'm using the music free template with K2 component and for login i'm using the K2 user module. I have put the module in the log-in position of the template and when a user insert the right credentials the login is successful.
Now, if the user makes a mistake, it gives the classic password or username error and loads the module in the mainbody of the template and not ofcourse in the login position. 
When the module is in the mainbody, even if the user inserts the right credentials, the login gives the "Invalid token error", then hitting back in the browser and refreshing the page, the user is signed in successfully. 

Any ideas why this error occurs? Could it be because the module is loaded in a different location from that specified? 

The cache is not enabled, redirection plugin is enabled, cleared the cache of my browser, checked the expiration time of the login tokens, and know i'm sort of ideas. 
I must mention that i get the same error with the default joomla login module too. 
Thank you in advance for any help.

**Comment by bkrztuk** [comment]
Could you check the same on default template like Beez ?

**Comment by borogul** [comment]
bkrztuk, thank you for the reply. In fact i had not try that and now i see that i get the same error so it's not a templates problem. To be honest, i have tried to write in the K2 forum too as i have tried various things found about joomla and didn't work. 
You can close this thread but i'd appreciate if you could give me any hint on where to search in order to resolve this problem.

Thank you very much,
Antony
