### ISSUE TITLE
Is it possible to make several articles as shown on the mainpage?

### ISSUE THREAD

**Issue by irosan** [GavickPro/Music-Free-Responsive-Joomla-Template#77]
Is it possible to make several articles as shown on the mainpage? If yes, how? ![3maincontent](https://f.cloud.github.com/assets/3290615/73288/b174f8d6-6039-11e2-8344-fdbd108998fb.png)

**Comment by dziudek** [comment]
Hi,

Sorry but there is no way to display articles in this way without big changes in the tempate core code.
