### ISSUE TITLE
A suggestion of Low-resolution Screen

### ISSUE THREAD

**Issue by ivanwongtf** [GavickPro/Music-Free-Responsive-Joomla-Template#78]
I got a inconvenient problem that when browsing the website which using this template.

As you know, there is a toolbar(gkFooter) at the bottom of this template. It is not a  problem in wide-screen, but it will make the website too crowd if i am browsing with a low-resolution screen, such as 1024x768. 

So i have a suggestion that let it hide the toolbar automatically when the user who browsing with a Low-resolution Screen but show it when the mouse near the  bottom.

I hope that you will accept my suggestion, thank you!

**Comment by dziudek** [comment]
Hi,

If it is a problem for you, then I suggest to copy the footer css code from the tablet.css file where the footer is placed at the bottom of the page  and place it in additional media query like:

``` css
@media (max-width: 1024px) {
// footer code from tablet.css file here
}
```

**Comment by ivanwongtf** [comment]
As dziudek said,
I put these code in the template.css from copying in the tablet.css file :

```
@media (max-width: 1024px) {
// footer code from tablet.css file here
#gkFooter {
    position: relative;
}

html body {
    padding-bottom: 0!important;
}
#gkFooter {
    bottom: 0!important;
    box-sizing: content-box!important;
    left: 0!important;
    max-height: 41px;
    overflow: hidden;
    position: relative!important;
    right: 0!important;
    top: 0!important;
}
}
```

They work well in other browsers(e.g. Chrome) except Firefox. I found that it is out of place in Firefox.

Here is the screen shot:
http://i.imgur.com/gFSjzW2.jpg

and here is the link:
http://www.justdoevil.info

Thanks for your help
