### ISSUE TITLE
Module map for Music Free

### ISSUE THREAD

**Issue by gavhd** [GavickPro/Music-Free-Responsive-Joomla-Template#79]
I have your Music Free J!3.0 quickstart template installed.
How can I access the module map?
Thank you.

**Comment by bkrztuk** [comment]
Hi,

What you mean by module map ? Template/quickstart not include any map module.

**Comment by bkrztuk** [comment]
You mean module positions ? >> http://demo.gavick.com/free/may2012/index.php/template/lorem-ipsum/template-articles/module-positions

**Comment by gavhd** [comment]
Yes, I do.

The Joomla! tutorials offered by www.CloudAccess.net refer to them as “module map.”

I am looking forward to get our website up and running.

Heinz Dinter, PhD • Editor & Publisher
Grand Lifestyle Club™
PO Box 558250 • Miami, Florida 33255 USA
305-600-4655 • 305-606-9626 (M) • HDinter (Skype) • 305-600-1213 (Fax)
 http://www.grandlifestyle.com/ www.GrandLifestyle.com •  mailto:HDinter@GrandLifestyle.com HDinter@GrandLifestyle.com • www.EvergladesEden.org
www.facebook.com/heinzdinter • www.twitter.com/heinzdinter • www.linkedin.com/in/heinzdinter 

Education • Information • News • Action — Read • Meet • Heed • Succeed

 http://www.grandlifestyle.com/ 3bannerpurpleem     http://www.evergladeseden.org/ EExlogoem
