### ISSUE TITLE
template enhancement : mod_gk_register as an integral part of the template

### ISSUE THREAD

**Issue by ghost** [GavickPro/Music-Free-Responsive-Joomla-Template#8]
module register as an integral part of the template.

**Comment by dziudek** [comment]
We have abandon using this module in last template due problems with recaptcha, there is no way to use two instances of recaptcha on one page, what causes a lot of problems with 3rd party components.

**Comment by ghost** [comment]
sure -  this conflict is really well known. sorry about that ... my fault.
