### ISSUE TITLE
No Bullets on unsorted lists

### ISSUE THREAD

**Issue by borogul** [GavickPro/Music-Free-Responsive-Joomla-Template#80]
I'm using K2 for articles etc but i have an issue with bullets in unsorted list, when inserted with tiny editor because they don't show, instead if i create an article with joomlas' default it seems to work fine. Now i say it seams because event there it shows only disks and not circles or squares but i don't mind if they can at least enter only disks.

I'd like that users where able to make unsorted lists at least using the formating from the tiny editor without having to enter code lines manually as <ul class="gkBullet1" etc. Is that possible?

Thank you in advance,
Antony

**Comment by dziudek** [comment]
@bkrztuk - please implement a fix for UL lists styling from the latest Gavern updates.
