### ISSUE TITLE
Russian Language pack

### ISSUE THREAD

**Issue by gajason** [GavickPro/Music-Free-Responsive-Joomla-Template#81]
Hi all.

Is there a possibility to download somewhere a Russian language pack for this template?

Thanks in advance.

**Comment by bkrztuk** [comment]
Hi,

No we don't provide language packs but you can easily translate all template settings all strings you can find in root/langauge/en-GB/en-GB.tpl_gk_music_free.ini file.

**Comment by gajason** [comment]
Re[2]: [Music-Free-Responsive-Joomla-Template] Russian Language pack (#81)

Hello Bartłomiej,

Thank you!

Hi,
No we don't provide language packs but you can easily translate all template settings all strings you can find in root/langauge/en-GB/en-GB.tpl_gk_music_free.ini file.
—
Reply to this email directly or view it on GitHub. 
 

-- 
Best regards,
 Jason                            mailto:gajason2@gmail.com
