### ISSUE TITLE
Page suffix doesn work...

### ISSUE THREAD

**Issue by martin001** [GavickPro/Music-Free-Responsive-Joomla-Template#82]
Hello,
I want to create individual Mainbodys for Menus. The Page class suffix won't show in Html (Firebug).  I found the tutorials about inserting sth. into the index.php <head> area but I can't  find it in the gk-music-free template. 

In addition I wanted to use Googlewebfonts and I need to insert a code into index.php <head> as well...

Can someone help me?

**Comment by dziudek** [comment]
Hi,

In the template code you can assign a Page Suffix class for mainbody (to specific menu item IDs or components) - check the "Features" tab.

You can also use the google web fonts through the template options (please check the "Fonts" tab).

**Comment by martin001** [comment]
Hey dziudek, thank you for your reply. 
We solved the typo problem via @font face, but good to know about the google option...

The page suffix still doesn't show up on the page html (firebug).  I tried the Module-Features-Tab:

Suffixes for pages  
ItemID/Option:116  (I inserted the ID of the submenu where I want to address the Mainbody, or contentpane/componentheading. I also tried the Title instead of the ID Number..)
Suffix:   pc   (spacepc)

Result:  I can define a body class that only works on the home page but not on others. That means I can find it  on www.mypage.de   but not on any   www.mypage.de/index.php/....  That is why I thought the change in the Index.PHP might be important.

I also tried inserting the suffix using the Menu Manager - Page Display Opions- Page Class.

Result:  I can define contentpane and componentheading classes but they also only show on the home page...

any ideas?

**Comment by dziudek** [comment]
Sorry but now I don't understand what is the problem - as you wrote - the CSS class appears in the body element, so all is ok.

**Comment by martin001** [comment]
No. I try to explain:
I marked a certain Menu Item with a suffix. This page is not supposed to be the "Home" page. But the suffix only shows in the HTML if the page is marked "Home"  in the Menu Manager. As soon as I use any link within the website e.g. to any other menu item (that is marked with that suffix) the suffix is gone.... 

www.name.de                                           ----- suffix shows in Html,   CSS possible
www.name.de/index.php/themen/suchen     ------ suffix does not show in Html, (I am sure I marked the right menu item ID)

Hope this makes it clear...?

**Comment by dziudek** [comment]
If you marked a specific menu item with a suffix then it is normal that on other menu items this suffix won't appear. These suffixes works this way - it appears only on the page which is connected with specific menu item or component (if you specify the component name instead of the menu item ID).

**Comment by martin001** [comment]
I know!  My problem is still not clear to you. I try again:

I mark a certain Menu Item ID with a suffix, let us say the "Main Menu/Themen/Suchen".  The suffix does not appear in HTML of that page.

If I mark that Menu Item (Main Menu/Themen/Suchen) "Home" in the Menu Manager that Menu Item appears on the "Home" page (www.name.de)  and under the menu link (www.name.de/index.php/themen/suchen). In the one case (Home) the suffix works,  in the other the same menu item with the same suffix it does not work. clear?

in general: the page suffix does not work within the template.  (--> as soon as the index.php is used in the address the suffix is gone....)

Clear?  Does the page suffix usually work in the gk-music-free template?

**Comment by dziudek** [comment]
I've created the following configuration: 
![conf](https://f.cloud.github.com/assets/22004/106375/28dcb28c-69f5-11e2-8a71-c4fb538181de.png)

The menu item ID = 101 is "Home"

The menu item ID = 436 is "Search" placed on: index.php/template/lorem-ipsum-ii/search

In both cases I see that the page class suffix is added:

Home:
![home](https://f.cloud.github.com/assets/22004/106398/fdb762cc-69f5-11e2-82fd-7f699a4af699.png)

Search:
![search](https://f.cloud.github.com/assets/22004/106399/06961708-69f6-11e2-92d7-d2466df2f75f.jpeg)

**Comment by martin001** [comment]
Hey Djuidek,
Thank you very much for all that .... I tried again and checked on some different menu items and it generally works. I found my problem:   The Menu Item I want to add a suffix to is Menu Level 2. 
But I marked the Menu to end at Level 1 in the Template Manager.

If I change the "End Item Level" to 2  the page suffix works fine.... 
![Bildschirmfoto vom 2013-01-29 16:03:31](https://f.cloud.github.com/assets/3368491/107274/4868a57c-6a25-11e2-9b61-fd5e889fcdc3.png)

My problem now is that I wanted to disable the direct link to the Menu Items on Level 2 for the user so that those pages only can be adressed by certain links but not via the Main Menu.....

If you understand this new problem and there is a easy may to achieve this, please tell me...  Otherwise I will find another way...
In any case:  Thank you again!
