### ISSUE TITLE
Module width and space

### ISSUE THREAD

**Issue by mangawill** [GavickPro/Music-Free-Responsive-Joomla-Template#83]
Hi,
I have an issue with my sidebar modules. They were in 3 rows under my mainbody home slideshow. Now they're squashed in 2 rows and increasing the home page height. This happened randomly after i reset some of the modules.
![Modules](https://f.cloud.github.com/assets/3379990/96916/7169ed5e-66d4-11e2-8b49-0d0127835f72.jpg)

**Comment by dziudek** [comment]
Hi,

Probably it is cause by fact that in the 3-columns mode the width of the players is too big.

**Comment by mangawill** [comment]
So what should I do next?
Sent from my BlackBerry® wireless device

-----Original Message-----

**Comment by dziudek** [comment]
In general you should set the video width to width which is lower or equal of the column width in the 3-columns layout.

**Comment by mangawill** [comment]
I unpublished the header slide and just left the sidebar modules and it was
still the same. Also undid all the overrides and replaced the current css
file with the original one... Nothings happening..

**Comment by mangawill** [comment]
Oh nevermind figured out the issue! Thanks so much for your help. Should
have just read your message properly the first time :D !
Cheers
