### ISSUE TITLE
Sidebar modules are not showing

### ISSUE THREAD

**Issue by Crimby** [GavickPro/Music-Free-Responsive-Joomla-Template#84]
Hi all,

I am trying to get modules visible in the Sidebar position.
I have loaded two modules just for test but both aren't showing.

Since i kinda just started the website it's still in test modus. Please have a look at www.techweetjes.nl/test 

All positions are working fine, except the sidebar (which is kinda the best feature).

When checking the site in IE9, i got the following info, i don't know if this has anything to do with it.

Bericht: 'jQuery' is niet gedefinieerd (is not defined)
Regel: 10
Teken: 1
Code: 0
URI: http://techweetjes.nl/test/templates/gk_music_free/js/gk.scripts.js

Bericht: Object wordt verwacht (Object is expected)
Regel: 1
Teken: 1
Code: 0
URI: http://techweetjes.nl/test/templates/gk_music_free/js/gk.menu.js

**Comment by dziudek** [comment]
Hi,

It seems that your files are inconsistent with files from our repository. Please replace these files with the repository ones:

https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/blob/master/gk_music_free/js/gk.menu.js
https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/blob/master/gk_music_free/js/gk.scripts.js

it should helps.
