### ISSUE TITLE
category counter and social-menu

### ISSUE THREAD

**Issue by HerrStern** [GavickPro/Music-Free-Responsive-Joomla-Template#85]
how can i realize the menu as shown in the demo. esspecially the counting function is a very nice gimmick. furthermore i am looking for the soultion to realize the social-menu (as seen in the demo).
thank you for all help.

**Comment by dziudek** [comment]
Hi,

I suggest to install the quickstart of this template and check how we have configured the social icons module and the category list (it is a K2 module).
