### ISSUE TITLE
Sidebar modules are not ordering right

### ISSUE THREAD

**Issue by Crimby** [GavickPro/Music-Free-Responsive-Joomla-Template#86]
Hi all,

Finally got my sidebar modules to work, but now i have a second issue. I am using 5 modules in de sidebar and somehow i can't get them to get ordered well.
After the body, its showes modules in the following order:

mod 1, mod 2, mod 3
*****************_mod 4
***_**************mod 5

while i want to have as much on one page, i would like to have it like:

mod 1, mod 3, mod 5
mod 2, mod 4, *******

Is there any chance I can fix this? I guess the MooMasonry is not really working here.

The website is www.techweetjes.nl/test

don't pay attention to the errors in the module, I asked the host to fix is.

**Comment by dziudek** [comment]
Hi,

First of all please fix the problem with warnings, because it can cause syntax errors which cause your problems.

**Comment by Crimby** [comment]
Hi,

I got news from my host telling me they can't solve the CURLOPT_FOLLOWLOCATION option due to a high security risk. Is there any option to get rid of the error? The modules are working fine and the RSS feeds are showing correctly.

Besides that, the above mentioned issue still excists.

**Comment by dziudek** [comment]
Could you try to put some other modules instead these with warnings? Because I think that the problem is caused by these modules due wrong HTML syntax. I think that if you remove these modules the problem will disappear.

**Comment by Crimby** [comment]
Yes then it works indeed. It seems to fail only with RSS feeds. Any tips for that? Besides not using RSS :-)

**Comment by dziudek** [comment]
My tip is: use only these modules which generates the correct HTML syntax ;)
