### ISSUE TITLE
gk_music_free_quickstart_J25 quickstart errors

### ISSUE THREAD

**Issue by snowball3r** [GavickPro/Music-Free-Responsive-Joomla-Template#87]
How do I install the gk_music_free_rest_J25 files? Just unzip and then copy into my www directory?

Secondly I installed joomla 2.5 then template fine locally on WAMP server, which worked fine. But when I try the quickstart install it gives the following errors...

( ! ) Strict standards: Declaration of JParameter::loadSetupFile() should be compatible with JRegistry::loadSetupFile() in C:\wamp\www\libraries\joomla\html\parameter.php on line 512
Call Stack
# Time    Memory  Function    Location

1   0.0011  145736  {main}( )   ..\index.php:0
2   0.1197  1805848 JSite->initialise( )    ..\index.php:30
3   0.1636  2469704 JApplication->initialise( ) ..\application.php:116
4   0.1638  2469992 JPluginHelper::importPlugin( )  ..\application.php:229
5   0.1638  2472712 JPluginHelper::_import( )   ..\helper.php:125
6   0.1742  2528632 plgSystemPlg_GKExtMenu->__construct( )  ..\helper.php:194
7   0.1744  2530016 JLoader::load( )    ..\helper.php:0

( ! ) Strict standards: Only variables should be assigned by reference in C:\wamp\www\plugins\system\k2\k2.php on line 320
Call Stack........................
 etc etc

**Comment by dziudek** [comment]
Hi,

The rest_files shouldn't be used if you're using the quickstart package. This package contains the PSD files and plugins packages which should be used only when you are not using the quickstart package.

The problem with warnings - please disable in your php.ini file showing the strict errors. In general the php.ini file should contain:

```
error_reporting = E_ALL & ~E_NOTICE & ~E_WARNING & ~E_STRICT & ~E_DEPRECATED
```

**Comment by peachhy** [comment]
Hi! 
Any other way to fix it? i tried the way above and didnt work

**Comment by dziudek** [comment]
Sorry but it must work, because the template doesn't override error_reporting through the ini_set function. So you have to did something wrong.

**Comment by peachhy** [comment]
my host created it under  the public_html/ folder, correct direction?

**Comment by dziudek** [comment]
I suggest to contact your host and ask for disabling displaying errors and redirect the errors to the error log file.
