### ISSUE TITLE
default.json

### ISSUE THREAD

**Issue by apo666** [GavickPro/Music-Free-Responsive-Joomla-Template#89]
I pressed load default.json.
That was a big mistake now all my setings are delteted.
Holy cow!

How can i get back my old settings.
Please help me!

**Comment by bkrztuk** [comment]
If you don't save before your configuration by pressing 'Save' button you can revert changes - this button load default template configuration.

**Comment by apo666** [comment]
Please could anyone help me?

**Comment by bkrztuk** [comment]
If you don't save your settings there is no way to revert changes.
