### ISSUE TITLE
template styling : complete support for K2 user module

### ISSUE THREAD

**Issue by ghost** [GavickPro/Music-Free-Responsive-Joomla-Template#9]
incl. log-in and profile styling.

**Comment by dziudek** [comment]
Added to our ToDo :)

**Comment by ghost** [comment]
kool!

**Comment by dziudek** [comment]
Fixed in: https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/commit/e784b6a89d4ac77a44aeb17a4d24dcd04f2b7838
