### ISSUE TITLE
Responsive issue

### ISSUE THREAD

**Issue by mangawill** [GavickPro/Music-Free-Responsive-Joomla-Template#91]
![bwmscreenshot](https://f.cloud.github.com/assets/3379990/123077/f544ed52-6eab-11e2-820d-5f9331696449.jpg)

Hi I need to know how to adjust the widths for wide screens. I editted this site on a much smaller screen and it doesnt adjust well to huge screens.

**Comment by bkrztuk** [comment]
Could you show us your site URL ?

**Comment by bkrztuk** [comment]
Could you try to unpublish this slideshow module and replace it with some other module for test ? I suspect that this is caused by this extension because it contains div element with <code>clear: both</code> attribute. Please let me know when you make this change.

**Comment by mangawill** [comment]
The problem's with the slideshow module, it was able to stretch but I've had a consistent issue with the slideshow, it doesn't respond well to different screens. Can you please suggest any slide modules maybe?
Sent from my BlackBerry® wireless device

-----Original Message-----

**Comment by bkrztuk** [comment]
Did you try to use Image Show GK4 ?

**Comment by mangawill** [comment]
No slideshowck 
Sent from my BlackBerry® wireless device

-----Original Message-----

**Comment by bkrztuk** [comment]
Maybe I don't understand your last response but Image Show GK4 is a slideshow module.

**Comment by mangawill** [comment]
I should probably use it. I installed a different slideshow to use in the mainbody.  
Sent from my BlackBerry® wireless device

-----Original Message-----

**Comment by mangawill** [comment]
DateTime::__construct(): Failed to parse time string (jerror) at position 0 (j): The timezone could not be found in the database

This poped up when i tried to install gk5 image! Please help

**Comment by bkrztuk** [comment]
This is template for Joomla 2.5 or Joomla 3.0 ?

**Comment by mangawill** [comment]
Joomla 3.0
Sent from my BlackBerry® wireless device

-----Original Message-----

**Comment by bkrztuk** [comment]
Are you sure you use extension for J!3.0 ? Could you give me access details ?

**Comment by mangawill** [comment]
Sure which access details do you need? Can I send you a direct message?
Sent from my BlackBerry® wireless device

-----Original Message-----

**Comment by bkrztuk** [comment]
I need access to administrator panel, please use <code>bkrztuk[at]gavick.com</code>

**Comment by mangawill** [comment]
Tried to send you that mail, it bounced back... Can you give me code suggestions for configuration.php ?

**Comment by bkrztuk** [comment]
Mail is proper so maybe it is something with your mail ... I can't help you until I can't see the message.

**Comment by mangawill** [comment]
Hi there,

Can you help with centering my modules and menu. On wide screens the template doesnt centre the items so its left with too much space on the right

**Comment by bkrztuk** [comment]
This how masonry script is working - you can't center menu and modules all layout is created from left to right side.

**Comment by mangawill** [comment]
I'm thinking of buying a really good template! Can you suggest any?
Sent from my BlackBerry® wireless device

-----Original Message-----

**Comment by bkrztuk** [comment]
please check lifetime Gavick license, then you will have access to all GavickPro templates from demo.gavick.com

**Comment by mangawill** [comment]
If I get the personal or business membership, do I still have ownership of the template forever?

**Comment by bkrztuk** [comment]
For downloaded template yes, only support time and access to new templates is time limited.
