### ISSUE TITLE
Module positions

### ISSUE THREAD

**Issue by DirkjanH** [GavickPro/Music-Free-Responsive-Joomla-Template#93]
I am testing the Music Free template. I try to change some modules, but I cannot find an overview of module positions. Where can I find it?

**Comment by bkrztuk** [comment]
Hi,

Please look here <code>http://demo.gavick.com/free/may2012/index.php/template/lorem-ipsum/template-articles/module-positions</code>

**Comment by DirkjanH** [comment]
Thanks, that helped a lot!

Best regards

Dirkjan Horringa

2013/2/5 Bartłomiej Krztuk notifications@github.com
