### ISSUE TITLE
Facebook api

### ISSUE THREAD

**Issue by DirkjanH** [GavickPro/Music-Free-Responsive-Joomla-Template#94]
In the Social API section of the Music Free template which I am testing it is possible to set up facebook connection by entering facebook data. Somehow this doesn't work. What is Facebook API ID? Is that the url (in my case facebook.com/trajecti.voces) or the ID number (i.e. 393859427364822)? Both don't make it work... Perhaps a tip to add some sort of description of expected data? Google+ and Twitter do work.

**Comment by bkrztuk** [comment]
APP ID you need to configure like it is described at this article <cod>https://www.gavick.com/documentation/joomla-templates/templates-for-joomla-1-6/how-to-implement-the-login-with-facebook-feature/</code>

**Comment by DirkjanH** [comment]
Hi!

I am getting as far as the Authentication - Facebook plugin. I don't have
it and can't find the ‘rest_files’ package mentioned in the article. Please
help!

Best regards

Dirkjan Horringa

2013/2/5 Bartłomiej Krztuk notifications@github.com

**Comment by bkrztuk** [comment]
To use Like button you just only need to configure APP ID in template settings, social API tab. How to generate APP ID you can find in mentioned article, you just need to create your own APP ID which is described step by step.

**Comment by DirkjanH** [comment]
Czesc Bartłomiej,

I tried this, but it doen't work yet. According to your instructions I made
an APP ID, 534083156623253, which I filled in in the template Social API
section, but Facebook doen't show up like Google+ and Twitter do. It should
refer to http://www.facebook.com/trajecti.voces. I wasn't asked for this
url when making the app id, so how can facebook know this connection?

Best regards

Dirkjan Horringa

2013/2/5 Bartłomiej Krztuk notifications@github.com

**Comment by DirkjanH** [comment]
Dear people at Gavick,

Until today I didn't get an answer to my question underneath. I am
seriously considering buying some of your templates, but I need some help
with the Facebook connection first. Please respond to my question.

Best regards

Dirkjan Horringa

2013/2/5 Dirkjan Horringa dirkjan@pellegrina.net

**Comment by bkrztuk** [comment]
Could you attach a screenshot with APP ID configuration ?

**Comment by DirkjanH** [comment]
Hi,

Here are two screenshots, one of the template Social API section and one of
the developer.facebook.com page. Hope they will help you to solve this
mystery.

Best regards

Dirkjan Horringa

2013/2/11 Bartłomiej Krztuk notifications@github.com

**Comment by bkrztuk** [comment]
Sorry but there is are no screenshots in your message ...

**Comment by DirkjanH** [comment]
![screenshot Music_free Social API](https://f.cloud.github.com/assets/3480028/157553/ddfe4f26-76c6-11e2-996a-c6ca4135ff61.jpg)
![screenshot developers facebook com](https://f.cloud.github.com/assets/3480028/157556/e338db64-76c6-11e2-817c-75a24362c856.jpg)

??? There are two jpg attachments, right? Ah, I see, when sending an email to Github the attachments aren't taken over, they are simply stripped... Well, here they are.

Best regards

Dirkjan Horringa

2013/2/14 Bartłomiej Krztuk notifications@github.com

**Comment by bkrztuk** [comment]
Ok now I see the screenshots but the most interesting part is missed :) I need to know how you configure domain, please tell me what you set in domain field.

**Comment by DirkjanH** [comment]
![screenshot facebook domain section](https://f.cloud.github.com/assets/3480028/158694/bb326e94-76f0-11e2-9895-c0a4eb0018c9.jpg)
does this clarify?

**Comment by bkrztuk** [comment]
Ok now I get all details and everything looks fine, please send me access to bkrztuk[at]gavick.com

**Comment by bkrztuk** [comment]
In your plugins list I can't see login with facebook authenitcation plugin, without this the login can't work ... please install and configure plugin (it is available in rest files package) and how to configure it you can find here https://www.gavick.com/documentation/joomla-templates/templates-for-joomla-1-6/how-to-implement-the-login-with-facebook-feature/

**Comment by DirkjanH** [comment]
Hi Bartłomiej,

I have installed it now. I seem to remember that somewhere in your
documentation it says the plugin is not needed when you just want to make
like buttons etc. (which I want), and don't really need the login option.
Anyway, at 'inloggen voor leden' (login for members) a facebook-button
appears, but nothing happens when I click it. And I still don't get
like-buttons.

Thanks for staying with me!

Best regards

Dirkjan Horringa

2013/2/15 Bartłomiej Krztuk notifications@github.com

**Comment by bkrztuk** [comment]
Ok now all looks fine except the buttons, is it possible to update template to latest 3.6 version before I start to modify code to find where is the problem ?

**Comment by DirkjanH** [comment]
Hi, I re-downloaded and reinstalled the template, but it still is 3.5.
Where do I find 3.6?

2013/2/17 Bartłomiej Krztuk notifications@github.com

**Comment by bkrztuk** [comment]
Could you provide me Ftp access via mail ? Remember to include link to this issue.

**Comment by bkrztuk** [comment]
I didn't get any access. Issue closed.
