### ISSUE TITLE
Box per new article?

### ISSUE THREAD

**Issue by mherbig** [GavickPro/Music-Free-Responsive-Joomla-Template#96]
Hi guys,
Hi guys,

I'm really new at Joomla, and so I was happy to get such a nice template for free.
But I have some problems to get it work. The template was installed successful, also the plugins.
My Joomla is not empty, I installed the examples, too.

What I want is that any new article is shown in a new box. What I got so far, is that a bunch of articles is shown in one and the same box. (see the image I attached)

Can you guys tell me, how to connect menus, articles and categories to get everytime I start a new article a new box?

Hope you can help me :)
Thx
![Unbenannt](https://f.cloud.github.com/assets/3491107/131483/4f0cc5d8-705c-11e2-96fc-82444453561a.jpg)

**Comment by dziudek** [comment]
Hi,

Sorry but it is impossible using easy changes, because the whole component content is placed always in one box. This kind of change needs deep changes in the template code which are beyond our support.

**Comment by mherbig** [comment]
Oh, but how does the demo do it? There a a lot of single boxes...

![Unbenannt](https://f.cloud.github.com/assets/3491107/135074/7140cb62-710c-11e2-8076-ecadd0998348.jpg)

**Comment by dziudek** [comment]
But these boxes are a separated modules ;)

**Comment by mherbig** [comment]
ahh, I said I'm a newbie :D ...okay, so I will try by adding a new module for each article :)
thanks, I will tell you if I was successful :D

**Comment by lospepitos** [comment]
Hi,
   I have a question related to module position for a first configuration.

![schermata del 2013-08-15 08 19 03](https://f.cloud.github.com/assets/5235187/967309/9f36c60c-0572-11e3-805d-7bdff899cdc7.png)

I start with a new joomla installation with content in the left zone (see attached).
I want try to add some boxes in right zone (for this example I can also use custom html module if is possible).

I try to create new module but I don't know the position for this module.
Please, you can help me?

**Comment by bkrztuk** [comment]
Module positions list is available here >> http://demo.gavick.com/free/may2012/index.php/template/lorem-ipsum/template-articles/module-positions

Please publish your modules on **sidebar** position.
