### ISSUE TITLE
Date and Timezone

### ISSUE THREAD

**Issue by mangawill** [GavickPro/Music-Free-Responsive-Joomla-Template#97]
Hi there,
Im having an issue with my time zone settings, this error keeps popping up:

500 DateTime::__construct(): Failed to parse time string (jerror) at position 0 (j): The timezone could not be found in the database

added this line to my .htaccess: php_value date.timezone "Africa/Johannesburg"

added this line to my configuration.php: public $offset = 'Africa/Johannesburg';

**Comment by bkrztuk** [comment]
Hi,

This issue is related with your server/Joomla! configuration not our template. Please check global Joomla! time settings ask provider about htaccess setttings.

**Comment by mangawill** [comment]
yeah they arent very helpful, need a code for my .htaccess

**Comment by mangawill** [comment]
Can you please send me your email address again

**Comment by bkrztuk** [comment]
Here is my mail bkrztuk[at]gavick.com

**Comment by mangawill** [comment]
Hi there, where is the php.ini located? Gonna try fiddle with the timezone codes on there.

**Comment by bkrztuk** [comment]
You need to ask your hosting company because this depends of server, usually users don't have access to this part.

**Comment by mangawill** [comment]
Can you give me a reference to any joomla experts to fix this?

**Comment by bkrztuk** [comment]
This can be changed only by your hosting company when you don't have access to this file. More help you should get from your hosting provider.
