### ISSUE TITLE
Centering modules and menu for wide screens

### ISSUE THREAD

**Issue by mangawill** [GavickPro/Music-Free-Responsive-Joomla-Template#98]
Hi there,

Can you help with centering my modules and menu. On wide screens the template doesnt centre the items so theres too much space on the right and everythings on the left

**Comment by responsive-cms** [comment]
i´m interested in, too. But more in center the whole site, than only the modules/menu.

**Comment by bkrztuk** [comment]
Template is designed to display modules from left to right side because this is how moomasonry script works. There is no way to achieve this effect without modifying template scripts and code.

**Comment by responsive-cms** [comment]
You can "pseudo-center" the whole site (template) by decrease / set the "Maximal number of columns" f.e. to 4.
Too sad, the gkFooter is not affected by this. Maybe @bkrztuk has a fix for this.
Check this screenshot (1688 x1058 in Firefox) http://goo.gl/Hoki0

**Comment by bkrztuk** [comment]
The footer is displayed with fixed position, please try to change position to relative and change width from 100% to some pixel value (+display: block).

**Comment by mangawill** [comment]
Is it possible for you to tell me exactly where to " "pseudo-center" the
whole site (template) by decrease / set the "Maximal number of columns"
f.e. to 4. " ?

On Mon, Apr 15, 2013 at 8:55 AM, Bartłomiej Krztuk <notifications@github.com

**Comment by responsive-cms** [comment]
gavick music free template settings, layout
